// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa-ts/core";
import type { z } from "zod";
import { GetStatusResponse } from "./schemas.js";

const route = createRouteRoot("/status");

export default route({
	get: createRoute({
		responses: {
			success: {
				status: 200,
				schema: GetStatusResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { ok: true } as unknown as z.output<typeof GetStatusResponse>,
			};
		},
	}),
});
