// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, defineRoute } from "@routa/core";
import type { z } from "zod";
import { GetStatusResponse } from "./schemas.js";

export default defineRoute({
	get: createRoute({
		responses: {
			success: {
				status: 200,
				schema: GetStatusResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { ok: true } as unknown as z.output<typeof GetStatusResponse>,
			};
		},
	}),
});
