// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const GetStatusResponse = z.object({ ok: z.boolean() });
