// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: src/routes directory

export const routaRoutes = [
	{
		"file": "src/routes/(private)/admin/audit-events/route.ts",
		"path": "/admin/audit-events",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200,
				401,
				403
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": true,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/auth.ts",
				"name": "requireAuth",
				"requires": [
					"session"
				],
				"provides": [
					"auth"
				],
				"providesTypes": {
					"auth": "{\n\treadonly \"userId\": string;\n}"
				},
				"rejects": [
					{
						"type": "unauthorized",
						"status": 401,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [
					{
						"sessionCookie": []
					}
				],
				"permissions": []
			},
			{
				"file": "src/middleware/admin.ts",
				"name": "withAdmin",
				"requires": [
					"auth"
				],
				"provides": [
					"admin"
				],
				"providesTypes": {
					"admin": "{\n\treadonly \"role\": \"owner\";\n}"
				},
				"rejects": [
					{
						"type": "forbidden",
						"status": 403,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [],
				"permissions": [
					"audit.read"
				]
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/admin.ts",
					"name": "withAdmin",
					"requires": [
						"auth"
					],
					"provides": [
						"admin"
					],
					"providesTypes": {
						"admin": "{\n\treadonly \"role\": \"owner\";\n}"
					},
					"rejects": [
						{
							"type": "forbidden",
							"status": 403,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [],
					"permissions": [
						"audit.read"
					]
				}
			]
		},
		"ctx": [
			"admin",
			"auth",
			"requestId",
			"session"
		],
		"groups": [
			"(private)"
		],
		"segments": [
			"admin",
			"audit-events"
		]
	},
	{
		"file": "src/routes/(private)/admin/reports.ts",
		"path": "/admin/reports",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200,
				401,
				403
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/auth.ts",
				"name": "requireAuth",
				"requires": [
					"session"
				],
				"provides": [
					"auth"
				],
				"providesTypes": {
					"auth": "{\n\treadonly \"userId\": string;\n}"
				},
				"rejects": [
					{
						"type": "unauthorized",
						"status": 401,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [
					{
						"sessionCookie": []
					}
				],
				"permissions": []
			},
			{
				"file": "src/middleware/admin.ts",
				"name": "withAdmin",
				"requires": [
					"auth"
				],
				"provides": [
					"admin"
				],
				"providesTypes": {
					"admin": "{\n\treadonly \"role\": \"owner\";\n}"
				},
				"rejects": [
					{
						"type": "forbidden",
						"status": 403,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [],
				"permissions": [
					"audit.read"
				]
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/admin.ts",
					"name": "withAdmin",
					"requires": [
						"auth"
					],
					"provides": [
						"admin"
					],
					"providesTypes": {
						"admin": "{\n\treadonly \"role\": \"owner\";\n}"
					},
					"rejects": [
						{
							"type": "forbidden",
							"status": 403,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [],
					"permissions": [
						"audit.read"
					]
				}
			]
		},
		"ctx": [
			"admin",
			"auth",
			"requestId",
			"session"
		],
		"groups": [
			"(private)"
		],
		"segments": [
			"admin",
			"reports"
		]
	},
	{
		"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
		"path": "/tenants/:tenantId/projects/:projectId",
		"methods": [
			"GET",
			"PATCH",
			"DELETE"
		],
		"responses": {
			"get": [
				200,
				401
			],
			"patch": [
				200,
				401,
				403
			],
			"delete": [
				204,
				401,
				403
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			},
			"patch": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": true
			},
			"delete": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/auth.ts",
				"name": "requireAuth",
				"requires": [
					"session"
				],
				"provides": [
					"auth"
				],
				"providesTypes": {
					"auth": "{\n\treadonly \"userId\": string;\n}"
				},
				"rejects": [
					{
						"type": "unauthorized",
						"status": 401,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [
					{
						"sessionCookie": []
					}
				],
				"permissions": []
			},
			{
				"file": "src/middleware/tenant.ts",
				"name": "withTenant",
				"requires": [
					"auth",
					"session"
				],
				"provides": [
					"tenant"
				],
				"providesTypes": {
					"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
				"name": "withProjectScope",
				"requires": [
					"tenant",
					"auth"
				],
				"provides": [
					"projectScope"
				],
				"providesTypes": {
					"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/tenant.ts",
					"name": "withTenant",
					"requires": [
						"auth",
						"session"
					],
					"provides": [
						"tenant"
					],
					"providesTypes": {
						"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
					"name": "withProjectScope",
					"requires": [
						"tenant",
						"auth"
					],
					"provides": [
						"projectScope"
					],
					"providesTypes": {
						"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			],
			"patch": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/tenant.ts",
					"name": "withTenant",
					"requires": [
						"auth",
						"session"
					],
					"provides": [
						"tenant"
					],
					"providesTypes": {
						"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
					"name": "withProjectScope",
					"requires": [
						"tenant",
						"auth"
					],
					"provides": [
						"projectScope"
					],
					"providesTypes": {
						"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
					"name": "withProjectPermissions",
					"requires": [
						"projectScope"
					],
					"provides": [
						"projectPermissions"
					],
					"providesTypes": {
						"projectPermissions": "{\n\treadonly \"canRead\": boolean;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [
						{
							"type": "forbidden",
							"status": 403,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [],
					"permissions": [
						"projects.write"
					]
				}
			],
			"delete": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/tenant.ts",
					"name": "withTenant",
					"requires": [
						"auth",
						"session"
					],
					"provides": [
						"tenant"
					],
					"providesTypes": {
						"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
					"name": "withProjectScope",
					"requires": [
						"tenant",
						"auth"
					],
					"provides": [
						"projectScope"
					],
					"providesTypes": {
						"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/$projectId/route.ts",
					"name": "withProjectPermissions",
					"requires": [
						"projectScope"
					],
					"provides": [
						"projectPermissions"
					],
					"providesTypes": {
						"projectPermissions": "{\n\treadonly \"canRead\": boolean;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [
						{
							"type": "forbidden",
							"status": 403,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [],
					"permissions": [
						"projects.write"
					]
				}
			]
		},
		"ctx": [
			"auth",
			"projectPermissions",
			"projectScope",
			"requestId",
			"session",
			"tenant"
		],
		"groups": [
			"(private)"
		],
		"segments": [
			"tenants",
			"$tenantId",
			"projects",
			"$projectId"
		]
	},
	{
		"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
		"path": "/tenants/:tenantId/projects",
		"methods": [
			"GET",
			"POST"
		],
		"responses": {
			"get": [
				200,
				401
			],
			"post": [
				201,
				401,
				403
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": true,
				"headers": true,
				"cookies": false,
				"body": false
			},
			"post": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": true
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/auth.ts",
				"name": "requireAuth",
				"requires": [
					"session"
				],
				"provides": [
					"auth"
				],
				"providesTypes": {
					"auth": "{\n\treadonly \"userId\": string;\n}"
				},
				"rejects": [
					{
						"type": "unauthorized",
						"status": 401,
						"schema": "z.object({ message: z.string() })"
					}
				],
				"security": [
					{
						"sessionCookie": []
					}
				],
				"permissions": []
			},
			{
				"file": "src/middleware/tenant.ts",
				"name": "withTenant",
				"requires": [
					"auth",
					"session"
				],
				"provides": [
					"tenant"
				],
				"providesTypes": {
					"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
				"name": "withProjectScope",
				"requires": [
					"tenant",
					"auth"
				],
				"provides": [
					"projectScope"
				],
				"providesTypes": {
					"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/tenant.ts",
					"name": "withTenant",
					"requires": [
						"auth",
						"session"
					],
					"provides": [
						"tenant"
					],
					"providesTypes": {
						"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
					"name": "withProjectScope",
					"requires": [
						"tenant",
						"auth"
					],
					"provides": [
						"projectScope"
					],
					"providesTypes": {
						"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
					"name": "withProjectListMode",
					"requires": [
						"projectScope"
					],
					"provides": [
						"projectListMode"
					],
					"providesTypes": {
						"projectListMode": "{\n\treadonly \"status\": \"active\" | \"archived\";\n\treadonly \"label\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			],
			"post": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/auth.ts",
					"name": "requireAuth",
					"requires": [
						"session"
					],
					"provides": [
						"auth"
					],
					"providesTypes": {
						"auth": "{\n\treadonly \"userId\": string;\n}"
					},
					"rejects": [
						{
							"type": "unauthorized",
							"status": 401,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [
						{
							"sessionCookie": []
						}
					],
					"permissions": []
				},
				{
					"file": "src/middleware/tenant.ts",
					"name": "withTenant",
					"requires": [
						"auth",
						"session"
					],
					"provides": [
						"tenant"
					],
					"providesTypes": {
						"tenant": "{\n\treadonly \"id\": string;\n\treadonly \"name\": string;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
					"name": "withProjectScope",
					"requires": [
						"tenant",
						"auth"
					],
					"provides": [
						"projectScope"
					],
					"providesTypes": {
						"projectScope": "{\n\treadonly \"tenantId\": string;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/routes/(private)/tenants/$tenantId/projects/route.ts",
					"name": "withProjectPermissions",
					"requires": [
						"projectScope"
					],
					"provides": [
						"projectPermissions"
					],
					"providesTypes": {
						"projectPermissions": "{\n\treadonly \"canRead\": boolean;\n\treadonly \"canWrite\": boolean;\n}"
					},
					"rejects": [
						{
							"type": "forbidden",
							"status": 403,
							"schema": "z.object({ message: z.string() })"
						}
					],
					"security": [],
					"permissions": [
						"projects.write"
					]
				}
			]
		},
		"ctx": [
			"auth",
			"projectListMode",
			"projectPermissions",
			"projectScope",
			"requestId",
			"session",
			"tenant"
		],
		"groups": [
			"(private)"
		],
		"segments": [
			"tenants",
			"$tenantId",
			"projects"
		]
	},
	{
		"file": "src/routes/auth/session/route.ts",
		"path": "/auth/session",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": true,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			]
		},
		"ctx": [
			"requestId",
			"session"
		],
		"groups": [],
		"segments": [
			"auth",
			"session"
		]
	},
	{
		"file": "src/routes/demo/route.ts",
		"path": "/demo",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			]
		},
		"ctx": [
			"requestId",
			"session"
		],
		"groups": [],
		"segments": [
			"demo"
		]
	},
	{
		"file": "src/routes/legacy.$id.ts",
		"path": "/legacy/:id",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			]
		},
		"ctx": [
			"requestId",
			"session"
		],
		"groups": [],
		"segments": [
			"legacy",
			"$id"
		]
	},
	{
		"file": "src/routes/legacy.ts",
		"path": "/legacy",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"deprecations": {
			"get": {
				"replacement": "/status"
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			]
		},
		"ctx": [
			"requestId",
			"session"
		],
		"groups": [],
		"segments": [
			"legacy"
		]
	},
	{
		"file": "src/routes/status/route.ts",
		"path": "/status",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [
			{
				"file": "src/middleware/context.ts",
				"name": "withRequest",
				"requires": [],
				"provides": [
					"requestId"
				],
				"providesTypes": {
					"requestId": "string"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			},
			{
				"file": "src/middleware/context.ts",
				"name": "withSession",
				"requires": [
					"requestId"
				],
				"provides": [
					"session"
				],
				"providesTypes": {
					"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
				},
				"rejects": [],
				"security": [],
				"permissions": []
			}
		],
		"methodMiddleware": {
			"get": [
				{
					"file": "src/middleware/context.ts",
					"name": "withRequest",
					"requires": [],
					"provides": [
						"requestId"
					],
					"providesTypes": {
						"requestId": "string"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				},
				{
					"file": "src/middleware/context.ts",
					"name": "withSession",
					"requires": [
						"requestId"
					],
					"provides": [
						"session"
					],
					"providesTypes": {
						"session": "{\n\treadonly \"authenticated\": boolean;\n\treadonly \"userId\"?: string | undefined;\n}"
					},
					"rejects": [],
					"security": [],
					"permissions": []
				}
			]
		},
		"ctx": [
			"requestId",
			"session"
		],
		"groups": [],
		"segments": [
			"status"
		]
	}
] as const;

export type AdminAuditEventsCtx = {
	"admin": unknown;
	"auth": unknown;
	"requestId": unknown;
	"session": unknown;
};

export type AdminReportsCtx = {
	"admin": unknown;
	"auth": unknown;
	"requestId": unknown;
	"session": unknown;
};

export type TenantsTenantIdProjectsProjectIdCtx = {
	"auth": unknown;
	"projectPermissions": unknown;
	"projectScope": unknown;
	"requestId": unknown;
	"session": unknown;
	"tenant": unknown;
};

export type TenantsTenantIdProjectsCtx = {
	"auth": unknown;
	"projectListMode": unknown;
	"projectPermissions": unknown;
	"projectScope": unknown;
	"requestId": unknown;
	"session": unknown;
	"tenant": unknown;
};

export type AuthSessionCtx = {
	"requestId": unknown;
	"session": unknown;
};

export type DemoCtx = {
	"requestId": unknown;
	"session": unknown;
};

export type LegacyIdCtx = {
	"requestId": unknown;
	"session": unknown;
};

export type LegacyCtx = {
	"requestId": unknown;
	"session": unknown;
};

export type StatusCtx = {
	"requestId": unknown;
	"session": unknown;
};

export type RoutaRouteCtxByPath = {
	"/admin/audit-events": {
		get: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/admin/reports": {
		get: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"admin": {
				readonly "role": "owner";
			};
			"auth": {
				readonly "userId": string;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/tenants/:tenantId/projects/:projectId": {
		get: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		post: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		put: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		patch: {
			"auth": {
				readonly "userId": string;
			};
			"projectPermissions": {
				readonly "canRead": boolean;
				readonly "canWrite": boolean;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		delete: {
			"auth": {
				readonly "userId": string;
			};
			"projectPermissions": {
				readonly "canRead": boolean;
				readonly "canWrite": boolean;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		head: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		options: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
	};
	"/tenants/:tenantId/projects": {
		get: {
			"auth": {
				readonly "userId": string;
			};
			"projectListMode": {
				readonly "status": "active" | "archived";
				readonly "label": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		post: {
			"auth": {
				readonly "userId": string;
			};
			"projectPermissions": {
				readonly "canRead": boolean;
				readonly "canWrite": boolean;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		put: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		patch: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		delete: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		head: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
		options: {
			"auth": {
				readonly "userId": string;
			};
			"projectScope": {
				readonly "tenantId": string;
				readonly "canWrite": boolean;
			};
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
			"tenant": {
				readonly "id": string;
				readonly "name": string;
			};
		};
	};
	"/auth/session": {
		get: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/demo": {
		get: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/legacy/:id": {
		get: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/legacy": {
		get: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
	"/status": {
		get: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		post: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		put: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		patch: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		delete: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		head: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
		options: {
			"requestId": string;
			"session": {
				readonly "authenticated": boolean;
				readonly "userId"?: string | undefined;
			};
		};
	};
};

export type RoutaCtxByKey = {
	"admin": {
		readonly "role": "owner";
	};
	"auth": {
		readonly "userId": string;
	};
	"projectListMode": {
		readonly "status": "active" | "archived";
		readonly "label": string;
	};
	"projectPermissions": {
		readonly "canRead": boolean;
		readonly "canWrite": boolean;
	};
	"projectScope": {
		readonly "tenantId": string;
		readonly "canWrite": boolean;
	};
	"requestId": string;
	"session": {
		readonly "authenticated": boolean;
		readonly "userId"?: string | undefined;
	};
	"tenant": {
		readonly "id": string;
		readonly "name": string;
	};
};

declare module "@routa-ts/core" {
	export interface Register {
		routeCtxByPath: RoutaRouteCtxByPath;
		ctxByKey: RoutaCtxByKey;
	}
}
