// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa-ts/core";
import type { z } from "zod";
import { ListUserPostsParams, ListUserPostsQuery, ListUserPostsResponse } from "./schemas.js";

const route = createRouteRoot("/users/:userId/posts");

export default route({
	get: createRoute({
		input: {
			params: ListUserPostsParams,
			query: ListUserPostsQuery,
		},
		responses: {
			success: {
				status: 200,
				schema: ListUserPostsResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { posts: [] } as unknown as z.output<typeof ListUserPostsResponse>,
			};
		},
	}),
});
