// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const ListUserPostsParams = z.object({ userId: z.string() });

export const ListUserPostsQuery = z.object({ published: z.boolean().optional() });

export const Post = z.object({
	id: z.string(),
	title: z.string(),
	published: z.boolean(),
});

export const ListUserPostsResponse = z.object({ posts: z.array(Post) });
