import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { basename, dirname, join, resolve } from "node:path";

export type CreateProjectResult = {
	projectDir: string;
	files: string[];
};

export type CreateProjectOptions = {
	openApi?: boolean;
	routaVersion?: string;
};

/**
 * Creates a new Routa project scaffold in the target directory.
 *
 * @param targetDir - Directory for the new project, resolved relative to `cwd`
 * @param cwd - Base directory used to resolve `targetDir`
 * @param options - Project generation options
 * @returns The absolute project directory and the list of generated file paths
 * @throws Error if the target directory already exists
 */
export function createProject(
	targetDir: string,
	cwd = process.cwd(),
	options: CreateProjectOptions = {},
): CreateProjectResult {
	const projectDir = resolve(cwd, targetDir);
	const projectName = basename(projectDir);

	if (existsSync(projectDir)) {
		throw new Error(`Target directory already exists: ${targetDir}`);
	}

	if (!isValidPackageName(projectName)) {
		throw new Error(`Invalid package name from target directory: ${projectName}`);
	}

	const statusRoute = statusRouteSource();
	const statusSchemas = statusSchemasSource();
	const openApi = openApiYaml();
	const routesMetadata = routesMetadataSource();
	const openApiBaseline = openApiBaselineJson();
	const manifest = manifestJson({
		route: statusRoute,
		schema: statusSchemas,
		routesMetadata,
		baseline: openApiBaseline,
	});
	const files = new Map<string, string>([
		[".gitignore", gitignore()],
		[".vscode/settings.json", vscodeSettings()],
		["README.md", readme(projectName, options.openApi ?? true)],
		["biome.json", biomeJson()],
		[
			"package.json",
			packageJson(projectName, options.routaVersion ?? "latest", options.openApi ?? true),
		],
		["src/routa.ts", routaSource()],
		["tsconfig.json", tsconfigJson()],
		["src/routes/status/route.ts", statusRoute],
		["src/routes/status/schemas.ts", statusSchemas],
	]);

	if (options.openApi ?? true) {
		files.set("openapi.yaml", openApi);
		files.set(".routa/openapi-baseline.json", openApiBaseline);
		files.set(".routa/manifest.json", manifest);
		files.set(".routa/routes.gen.ts", routesMetadata);
	}

	for (const [path, content] of files) {
		const absolutePath = join(projectDir, path);
		mkdirSync(dirname(absolutePath), { recursive: true });
		writeFileSync(absolutePath, content);
	}

	return { projectDir, files: Array.from(files.keys()) };
}

function isValidPackageName(name: string): boolean {
	const reservedNames = new Set([
		"node_modules",
		"favicon.ico",
		...builtinModules.map((moduleName) => moduleName.replace(/^node:/, "")),
	]);

	return (
		name.length <= 214
		&& !reservedNames.has(name)
		&& /^[a-z0-9][a-z0-9._-]*$/.test(name)
		&& encodeURIComponent(name) === name
	);
}

/**
 * Creates the standard header for generated files.
 *
 * @param source - The source label to include in the header
 * @returns The formatted header text
 */
function generatedHeader(source: string): string {
	return `// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: ${source}\n\n`;
}

/**
 * Generates the route metadata module for the scaffolded OpenAPI project.
 *
 * @returns The generated TypeScript source for route metadata and module augmentation.
 */
function routesMetadataSource(): string {
	return `${generatedHeader("openapi.yaml")}export const routaRoutes = [
\t{
\t\t"file": "src/routes/status/route.ts",
\t\t"path": "/status",
\t\t"methods": ["GET"],
\t\t"operationIds": ["getStatus"],
\t\t"middleware": [],
\t\t"groups": [],
\t\t"segments": ["status"]
\t}
] as const;

export type RoutaRouteCtxByPath = {
\t"/status": EmptyRouteCtxByMethod;
};

type EmptyRouteCtxByMethod = {
\tget: EmptyRouteCtx;
\tpost: EmptyRouteCtx;
\tput: EmptyRouteCtx;
\tpatch: EmptyRouteCtx;
\tdelete: EmptyRouteCtx;
\thead: EmptyRouteCtx;
\toptions: EmptyRouteCtx;
};

type EmptyRouteCtx = {
\treadonly __empty?: never;
};

export type RoutaCtxByKey = {
\treadonly __empty?: never;
};

declare module "@routa/core" {
\texport interface Register {
\t\trouteCtxByPath: RoutaRouteCtxByPath;
\t\tctxByKey: RoutaCtxByKey;
\t}
}
`;
}

/**
 * Returns the baseline OpenAPI document for the starter project.
 *
 * @returns A formatted JSON string containing the OpenAPI 3.1 baseline.
 */
function openApiBaselineJson(): string {
	return `${JSON.stringify(
		{
			openapi: "3.1.0",
			info: {
				title: "Routa API",
				version: "0.0.0",
			},
			paths: {
				"/status": {
					get: {
						operationId: "getStatus",
						responses: {
							"200": {
								description: "Service status",
								content: {
									"application/json": {
										schema: {
											type: "object",
											required: ["ok"],
											properties: {
												ok: {
													type: "boolean",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		null,
		"\t",
	)}\n`;
}

/**
 * Builds the manifest JSON for generated project files.
 *
 * @param content - File contents used to compute the manifest hashes.
 * @returns A formatted JSON string for the `.routa/manifest.json` file.
 */
function manifestJson(content: {
	route: string;
	schema: string;
	routesMetadata: string;
	baseline: string;
}): string {
	return `${JSON.stringify(
		{
			version: 1,
			openapi: {
				baseline: ".routa/openapi-baseline.json",
			},
			generated: [
				{
					path: "src/routes/status/route.ts",
					source: "openapi.yaml",
					operationIds: ["getStatus"],
					kind: "route",
					sha256: sha256(content.route),
				},
				{
					path: "src/routes/status/schemas.ts",
					source: "openapi.yaml",
					operationIds: ["getStatus"],
					kind: "schema",
					sha256: sha256(content.schema),
				},
				{
					path: ".routa/routes.gen.ts",
					source: "openapi.yaml",
					kind: "route-metadata",
					sha256: sha256(content.routesMetadata),
				},
				{
					path: ".routa/openapi-baseline.json",
					source: "openapi.yaml",
					kind: "openapi-baseline",
					sha256: sha256(content.baseline),
				},
			],
		},
		null,
		"\t",
	)}\n`;
}

/**
 * Computes the SHA-256 hash of a string.
 *
 * @param content - The input string to hash.
 * @returns The hash as a hexadecimal string.
 */
function sha256(content: string): string {
	return createHash("sha256").update(content).digest("hex");
}

/**
 * Generates the project's package manifest.
 *
 * @param name - The package name
 * @param routaVersion - The version specifier used for Routa dependencies
 * @param openApi - Whether to include OpenAPI-related scripts
 * @returns A formatted `package.json` file
 */
function packageJson(name: string, routaVersion: string, openApi: boolean): string {
	return `${JSON.stringify(
		{
			name,
			version: "0.0.0",
			private: true,
			type: "module",
			scripts: {
				dev: "routa dev",
				start: "routa start",
				check: "routa check",
				build: "routa build",
				lint: "biome check .",
				format: "biome check --write .",
				...(openApi
					? {
							scaffold: "routa scaffold openapi.yaml",
							"openapi:check": "routa openapi check",
						}
					: {}),
			},
			dependencies: {
				"@routa/cli": routaVersion,
				"@routa/core": routaVersion,
				tsx: "^4.22.4",
				zod: "^4.4.3",
			},
			devDependencies: {
				"@biomejs/biome": "^2.5.1",
				"@types/node": "^24.0.4",
				typescript: "^5.8.3",
			},
		},
		null,
		"\t",
	)}\n`;
}

/**
 * Returns a TypeScript configuration JSON string for a Routa project.
 *
 * @returns The contents of `tsconfig.json`.
 */
function tsconfigJson(): string {
	return `{
\t"compilerOptions": {
\t\t"target": "ES2022",
\t\t"module": "NodeNext",
\t\t"moduleResolution": "NodeNext",
\t\t"strict": true,
\t\t"skipLibCheck": true,
\t\t"noEmitOnError": true,
\t\t"outDir": "dist",
\t\t"types": ["node"]
\t},
\t"include": ["src/**/*.ts", ".routa/**/*.ts"]
}
`;
}

/**
 * Returns the contents of a default `.gitignore` file.
 *
 * @returns The ignore rules for dependencies, build output, local environment files, and coverage output.
 */
function gitignore(): string {
	return `node_modules/
dist/
.env
.env.local
coverage/
`;
}

/**
 * Returns the VS Code workspace settings for a Routa project.
 *
 * @returns The JSON string for `.vscode/settings.json`.
 */
function vscodeSettings(): string {
	return `${JSON.stringify(
		{
			"files.watcherExclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"search.exclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"files.readonlyInclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"[typescript]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"[json]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"[jsonc]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"editor.codeActionsOnSave": {
				"source.organizeImports.biome": "explicit",
			},
		},
		null,
		"\t",
	)}\n`;
}

/**
 * Generates the project README content.
 *
 * @param name - The project name used in the heading.
 * @param openApi - Whether to include OpenAPI-related instructions.
 * @returns The README markdown content.
 */
function readme(name: string, openApi: boolean): string {
	return `# ${name}

Routa API generated with \`pnpm create routa@latest\`.

## Development

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

\`pnpm dev\` runs \`routa dev\`, which validates the route graph, generates Routa metadata, typechecks, and starts the internal development server.

## Scripts

\`\`\`sh
pnpm dev
pnpm start
pnpm check
pnpm build
pnpm lint
pnpm format
${openApi ? "pnpm openapi:check\n" : ""}\
\`\`\`

## Routes

\`src/routa.ts\` is the user-owned Routa entry point. Routes live in \`src/routes\`.

\`\`\`txt
src/routa.ts
src/routes/status/route.ts
src/routes/status/schemas.ts
\`\`\`

${openApi ? "Routa owns generated project metadata in `.routa/`. Commit those files so OpenAPI drift and regeneration safety work across machines." : "This starter was created without OpenAPI files. Add `openapi.yaml` later and run `routa scaffold openapi.yaml` if you want generated route metadata."}
`;
}

/**
 * Returns the Biome configuration.
 *
 * @returns A formatted JSON string for `biome.json`.
 */
function biomeJson(): string {
	return `${JSON.stringify(
		{
			$schema: "./node_modules/@biomejs/biome/configuration_schema.json",
			root: false,
			vcs: {
				enabled: true,
				clientKind: "git",
				useIgnoreFile: true,
			},
			files: {
				ignoreUnknown: true,
				includes: ["**", "!node_modules", "!dist", "!coverage", "!.routa"],
			},
			formatter: {
				enabled: true,
				indentStyle: "tab",
				lineWidth: 100,
			},
			linter: {
				enabled: true,
				rules: {
					preset: "recommended",
					correctness: {
						useImportExtensions: "off",
					},
					suspicious: {
						noConsole: "off",
						noExplicitAny: "off",
					},
				},
			},
			assist: {
				enabled: true,
				actions: {
					source: {
						recommended: true,
					},
				},
			},
		},
		null,
		"\t",
	)}\n`;
}

/**
 * Returns the default `src/routa.ts` source for a new project.
 *
 * @returns The generated module string that exports a Routa app configured for port `3000`.
 */
function routaSource(): string {
	return `import { createRouta } from "@routa/core";

export default createRouta({
\tport: 3000,
});
`;
}

/**
 * Returns the OpenAPI YAML template for the scaffolded status endpoint.
 *
 * @returns The OpenAPI 3.1 YAML document for the `GET /status` operation.
 */
function openApiYaml(): string {
	return `openapi: 3.1.0
info:
  title: Routa API
  version: 0.0.0
paths:
  /status:
    get:
      operationId: getStatus
      responses:
        "200":
          description: Service status
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
`;
}

/**
 * Returns the source for the default `/status` route.
 *
 * @returns The TypeScript module text for `src/routes/status/route.ts`.
 */
function statusRouteSource(): string {
	return `import { createRoute, defineRoute } from "@routa/core";
import { GetStatusResponse } from "./schemas.js";

export default defineRoute({
\tget: createRoute({
\t\tresponses: {
\t\t\tsuccess: {
\t\t\t\tstatus: 200,
\t\t\t\tschema: GetStatusResponse,
\t\t\t},
\t\t},
\t\trun: () => ({ type: "success", data: { ok: true } }),
\t}),
});
`;
}

/**
 * Generates the `/status` response schema module source.
 *
 * @returns The TypeScript source for `GetStatusResponse`.
 */
function statusSchemasSource(): string {
	return `import { z } from "zod";

export const GetStatusResponse = z.object({
\tok: z.boolean(),
});
`;
}
