import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type CreateProjectResult = {
	projectDir: string;
	files: string[];
};

export type CreateProjectOptions = {
	openApi?: boolean;
	routaVersion?: string;
};

export function createProject(
	targetDir: string,
	cwd = process.cwd(),
	options: CreateProjectOptions = {},
): CreateProjectResult {
	const projectDir = resolve(cwd, targetDir);

	if (existsSync(projectDir)) {
		throw new Error(`Target directory already exists: ${targetDir}`);
	}

	const statusRoute = statusRouteSource();
	const statusSchemas = statusSchemasSource();
	const openApi = openApiYaml();
	const routesMetadata = routesMetadataSource();
	const openApiBaseline = openApiBaselineJson();
	const manifest = manifestJson({
		route: statusRoute,
		schema: statusSchemas,
		routesMetadata,
		baseline: openApiBaseline,
	});
	const files = new Map<string, string>([
		[".gitignore", gitignore()],
		[".vscode/settings.json", vscodeSettings()],
		["README.md", readme(targetDir)],
		["biome.json", biomeJson()],
		["package.json", packageJson(targetDir, options.routaVersion ?? "latest")],
		["src/routa.ts", routaSource()],
		["tsconfig.json", tsconfigJson()],
		["src/routes/status/route.ts", statusRoute],
		["src/routes/status/schemas.ts", statusSchemas],
	]);

	if (options.openApi ?? true) {
		files.set("openapi.yaml", openApi);
		files.set(".routa/openapi-baseline.json", openApiBaseline);
		files.set(".routa/manifest.json", manifest);
		files.set(".routa/routes.gen.ts", routesMetadata);
	}

	for (const [path, content] of files) {
		const absolutePath = join(projectDir, path);
		mkdirSync(dirname(absolutePath), { recursive: true });
		writeFileSync(absolutePath, content);
	}

	return { projectDir, files: Array.from(files.keys()) };
}

function generatedHeader(source: string): string {
	return `// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: ${source}\n\n`;
}

function routesMetadataSource(): string {
	return `${generatedHeader("openapi.yaml")}export const routaRoutes = [
\t{
\t\t"file": "src/routes/status/route.ts",
\t\t"path": "/status",
\t\t"methods": ["GET"],
\t\t"operationIds": ["getStatus"],
\t\t"middleware": [],
\t\t"groups": [],
\t\t"segments": ["status"]
\t}
] as const;

export type RoutaRouteCtxByPath = {
\t"/status": EmptyRouteCtxByMethod;
};

type EmptyRouteCtxByMethod = {
\tget: EmptyRouteCtx;
\tpost: EmptyRouteCtx;
\tput: EmptyRouteCtx;
\tpatch: EmptyRouteCtx;
\tdelete: EmptyRouteCtx;
\thead: EmptyRouteCtx;
\toptions: EmptyRouteCtx;
};

type EmptyRouteCtx = {
\treadonly __empty?: never;
};

export type RoutaCtxByKey = {
\treadonly __empty?: never;
};

declare module "@routa/core" {
\texport interface Register {
\t\trouteCtxByPath: RoutaRouteCtxByPath;
\t\tctxByKey: RoutaCtxByKey;
\t}
}
`;
}

function openApiBaselineJson(): string {
	return `${JSON.stringify(
		{
			openapi: "3.1.0",
			info: {
				title: "Routa API",
				version: "0.0.0",
			},
			paths: {
				"/status": {
					get: {
						operationId: "getStatus",
						responses: {
							"200": {
								description: "Service status",
								content: {
									"application/json": {
										schema: {
											type: "object",
											required: ["ok"],
											properties: {
												ok: {
													type: "boolean",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		null,
		"\t",
	)}\n`;
}

function manifestJson(content: {
	route: string;
	schema: string;
	routesMetadata: string;
	baseline: string;
}): string {
	return `${JSON.stringify(
		{
			version: 1,
			openapi: {
				baseline: ".routa/openapi-baseline.json",
			},
			generated: [
				{
					path: "src/routes/status/route.ts",
					source: "openapi.yaml",
					operationIds: ["getStatus"],
					kind: "route",
					sha256: sha256(content.route),
				},
				{
					path: "src/routes/status/schemas.ts",
					source: "openapi.yaml",
					operationIds: ["getStatus"],
					kind: "schema",
					sha256: sha256(content.schema),
				},
				{
					path: ".routa/routes.gen.ts",
					source: "openapi.yaml",
					kind: "route-metadata",
					sha256: sha256(content.routesMetadata),
				},
				{
					path: ".routa/openapi-baseline.json",
					source: "openapi.yaml",
					kind: "openapi-baseline",
					sha256: sha256(content.baseline),
				},
			],
		},
		null,
		"\t",
	)}\n`;
}

function sha256(content: string): string {
	return createHash("sha256").update(content).digest("hex");
}

function packageJson(name: string, routaVersion: string): string {
	return `${JSON.stringify(
		{
			name,
			version: "0.0.0",
			private: true,
			type: "module",
			scripts: {
				dev: "routa dev",
				start: "routa start",
				check: "routa check",
				build: "routa build",
				lint: "biome check .",
				format: "biome check --write .",
				scaffold: "routa scaffold openapi.yaml",
				"openapi:check": "routa openapi check",
			},
			dependencies: {
				"@routa/cli": routaVersion,
				"@routa/core": routaVersion,
				tsx: "^4.22.4",
				zod: "^4.4.3",
			},
			devDependencies: {
				"@biomejs/biome": "^2.5.1",
				"@types/node": "^24.0.4",
				typescript: "^6.0.3",
			},
		},
		null,
		"\t",
	)}\n`;
}

function tsconfigJson(): string {
	return `{
\t"compilerOptions": {
\t\t"target": "ES2022",
\t\t"module": "NodeNext",
\t\t"moduleResolution": "NodeNext",
\t\t"strict": true,
\t\t"skipLibCheck": true,
\t\t"noEmitOnError": true,
\t\t"outDir": "dist",
\t\t"types": ["node"]
\t},
\t"include": ["src/**/*.ts", ".routa/**/*.ts"]
}
`;
}

function gitignore(): string {
	return `node_modules/
dist/
.env
.env.local
coverage/
`;
}

function vscodeSettings(): string {
	return `${JSON.stringify(
		{
			"files.watcherExclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"search.exclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"files.readonlyInclude": {
				"**/.routa/routes.gen.ts": true,
			},
			"[typescript]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"[json]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"[jsonc]": {
				"editor.defaultFormatter": "biomejs.biome",
			},
			"editor.codeActionsOnSave": {
				"source.organizeImports.biome": "explicit",
			},
		},
		null,
		"\t",
	)}\n`;
}

function readme(name: string): string {
	return `# ${name}

Routa API generated with \`pnpm create routa@latest\`.

## Development

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

\`pnpm dev\` runs \`routa dev\`, which validates the route graph, generates Routa metadata, typechecks, and starts the internal development server.

## Scripts

\`\`\`sh
pnpm dev
pnpm start
pnpm check
pnpm build
pnpm lint
pnpm format
pnpm openapi:check
\`\`\`

## Routes

\`src/routa.ts\` is the user-owned Routa entry point. Routes live in \`src/routes\`.

\`\`\`txt
src/routa.ts
src/routes/status/route.ts
src/routes/status/schemas.ts
\`\`\`

Routa owns generated project metadata in \`.routa/\`. Commit those files so OpenAPI drift and regeneration safety work across machines.
`;
}

function biomeJson(): string {
	return `${JSON.stringify(
		{
			$schema: "./node_modules/@biomejs/biome/configuration_schema.json",
			root: false,
			vcs: {
				enabled: true,
				clientKind: "git",
				useIgnoreFile: true,
			},
			files: {
				ignoreUnknown: true,
				includes: ["**", "!node_modules", "!dist", "!coverage", "!.routa"],
			},
			formatter: {
				enabled: true,
				indentStyle: "tab",
				lineWidth: 100,
			},
			linter: {
				enabled: true,
				rules: {
					preset: "recommended",
					correctness: {
						useImportExtensions: "off",
					},
					suspicious: {
						noConsole: "off",
						noExplicitAny: "off",
					},
				},
			},
			assist: {
				enabled: true,
				actions: {
					source: {
						recommended: true,
					},
				},
			},
		},
		null,
		"\t",
	)}\n`;
}

function routaSource(): string {
	return `import { createRouta } from "@routa/core";

export default createRouta({
\tport: 3000,
});
`;
}

function openApiYaml(): string {
	return `openapi: 3.1.0
info:
  title: Routa API
  version: 0.0.0
paths:
  /status:
    get:
      operationId: getStatus
      responses:
        "200":
          description: Service status
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                properties:
                  ok:
                    type: boolean
`;
}

function statusRouteSource(): string {
	return `import { createRoute, defineRoute } from "@routa/core";
import { GetStatusResponse } from "./schemas.js";

export default defineRoute({
\tget: createRoute({
\t\tresponses: {
\t\t\tsuccess: {
\t\t\t\tstatus: 200,
\t\t\t\tschema: GetStatusResponse,
\t\t\t},
\t\t},
\t\trun: () => ({ type: "success", data: { ok: true } }),
\t}),
});
`;
}

function statusSchemasSource(): string {
	return `import { z } from "zod";

export const GetStatusResponse = z.object({
\tok: z.boolean(),
});
`;
}
