// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa/core";
import {
	GetProjectParams,
	GetProjectResponse,
	UpdateProjectBody,
	UpdateProjectParams,
	UpdateProjectResponse,
} from "./schemas.js";

const route = createRouteRoot("/tenants/:tenantId/projects/:projectId");

export default route({
	get: createRoute({
		input: {
			params: GetProjectParams,
		},
		responses: {
			success: {
				status: 200,
				schema: GetProjectResponse,
			},
		},
		run: ({ ctx, input }) => {
			return {
				type: "success",
				data: {
					id: input.params.projectId,
					tenantId: ctx.tenant.id,
					name: "Control Plane",
					status: "active",
				},
			};
		},
	}),
	patch: createRoute({
		input: {
			params: UpdateProjectParams,
			body: UpdateProjectBody,
		},
		responses: {
			success: {
				status: 200,
				schema: UpdateProjectResponse,
			},
		},
		run: ({ ctx, input }) => {
			return {
				type: "success",
				data: {
					id: input.params.projectId,
					tenantId: ctx.tenant.id,
					name: input.body.name ?? "Control Plane",
					status: input.body.status ?? "active",
				},
			};
		},
	}),
});
