// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa-ts/core";
import { withProjectListMode, withProjectScope } from "../../../../middleware/projects.js";
import {
	CreateProjectBody,
	CreateProjectParams,
	CreateProjectResponse,
	ListProjectsHeaders,
	ListProjectsParams,
	ListProjectsQuery,
	ListProjectsResponse,
} from "./schemas.js";

const route = createRouteRoot("/tenants/:tenantId/projects");

export default route({
	middleware: [withProjectScope],
	get: createRoute({
		middleware: [withProjectListMode],
		input: {
			params: ListProjectsParams,
			query: ListProjectsQuery,
			headers: ListProjectsHeaders,
		},
		responses: {
			success: {
				status: 200,
				schema: ListProjectsResponse,
			},
		},
		run: ({ ctx }) => {
			const status = ctx.projectListMode.status;
			const projects = [
				{
					id: "project_1",
					tenantId: ctx.projectScope.tenantId,
					name: `${ctx.tenant.name} ${ctx.projectListMode.label} Portal`,
					status,
				},
			];

			return {
				type: "success",
				data: {
					projects,
				},
			};
		},
	}),
	post: createRoute({
		input: {
			params: CreateProjectParams,
			body: CreateProjectBody,
		},
		responses: {
			success: {
				status: 201,
				schema: CreateProjectResponse,
			},
		},
		run: ({ ctx, input }) => {
			if (!ctx.projectScope.canWrite) {
				throw new Response("Forbidden", { status: 403 });
			}

			return {
				type: "success",
				data: {
					id: "project_new",
					tenantId: ctx.projectScope.tenantId,
					name: input.body.name,
					status: "active",
				},
			};
		},
	}),
});
