// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const ListProjectsParams = z.object({ tenantId: z.string() });

export const ListProjectsQuery = z.object({
	status: z.enum(["active", "archived"]).optional(),
});

export const ListProjectsHeaders = z.object({
	"x-request-id": z.string().optional(),
});

export const Project = z.object({
	id: z.string(),
	tenantId: z.string(),
	name: z.string(),
	status: z.string(),
});

export const ListProjectsResponse = z.object({ projects: z.array(Project) });

export const CreateProjectParams = z.object({ tenantId: z.string() });

export const CreateProjectInput = z.object({ name: z.string() });

export const CreateProjectBody = CreateProjectInput;

export const CreateProjectResponse = Project;
