// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa-ts/core";
import type { z } from "zod";
import {
	GetCatalogItemParams,
	GetCatalogItemQuery,
	GetCatalogItemResponse,
	InspectCatalogItemParams,
	InspectCatalogItemResponse204,
	ReplaceCatalogItemBody,
	ReplaceCatalogItemParams,
	ReplaceCatalogItemResponse,
} from "./schemas.js";

const route = createRouteRoot("/catalog/items/:itemId");

export default route({
	get: createRoute({
		input: {
			params: GetCatalogItemParams,
			query: GetCatalogItemQuery,
		},
		responses: {
			success: {
				status: 200,
				schema: GetCatalogItemResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { id: "00000000-0000-4000-8000-000000000000", name: "", enabled: false, score: 0, attributes: {  }, delivery: { kind: "email", email: "example@example.com" }, createdAt: "2026-01-01T00:00:00.000Z" } as unknown as z.output<typeof GetCatalogItemResponse>,
			};
		},
	}),
	put: createRoute({
		input: {
			params: ReplaceCatalogItemParams,
			body: ReplaceCatalogItemBody,
		},
		responses: {
			success: {
				status: 200,
				schema: ReplaceCatalogItemResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { id: "00000000-0000-4000-8000-000000000000", name: "", enabled: false, score: 0, attributes: {  }, delivery: { kind: "email", email: "example@example.com" }, createdAt: "2026-01-01T00:00:00.000Z" } as unknown as z.output<typeof ReplaceCatalogItemResponse>,
			};
		},
	}),
	head: createRoute({
		input: {
			params: InspectCatalogItemParams,
		},
		responses: {
			success: {
				status: 204,
				schema: InspectCatalogItemResponse204,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: null as unknown as z.output<typeof InspectCatalogItemResponse204>,
			};
		},
	}),
});
