// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const GetCatalogItemParams = z.object({ itemId: z.uuid() });

export const GetCatalogItemQuery = z.object({
	includeArchived: z.stringbool().optional(),
	confidence: z.coerce.number().optional(),
});

export const CatalogItem = z.object({
	id: z.uuid(),
	name: z.string(),
	enabled: z.boolean(),
	score: z.number().nullable(),
	attributes: z.record(z.string(), z.string()),
	delivery: z.discriminatedUnion("kind", [z.object({
	kind: z.literal("email"),
	email: z.email(),
}), z.object({
	kind: z.literal("webhook"),
	callback: z.url(),
})]),
	createdAt: z.iso.datetime(),
});

export const GetCatalogItemResponse = CatalogItem;

export const ReplaceCatalogItemParams = z.object({ itemId: z.uuid() });

export const CatalogItemInput = z.object({
	name: z.string(),
	enabled: z.boolean(),
	score: z.number().nullable().optional(),
	attributes: z.record(z.string(), z.string()),
	delivery: z.discriminatedUnion("kind", [z.object({
	kind: z.literal("email"),
	email: z.email(),
}), z.object({
	kind: z.literal("webhook"),
	callback: z.url(),
})]),
});

export const ReplaceCatalogItemBody = CatalogItemInput;

export const ReplaceCatalogItemResponse = CatalogItem;

export const InspectCatalogItemParams = z.object({ itemId: z.uuid() });

export const InspectCatalogItemResponse204 = z.unknown();
