// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const GetSessionCookies = z.object({ session: z.string().optional() });

export const Session = z.object({
	authenticated: z.boolean(),
	userId: z.string().optional(),
});

export const GetSessionResponse = Session;
