// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: src/routes directory

export const routaRoutes = [
	{
		"file": "src/routes/catalog/items/$itemId/route.ts",
		"path": "/catalog/items/:itemId",
		"methods": [
			"GET",
			"PUT",
			"HEAD"
		],
		"responses": {
			"get": [
				200
			],
			"put": [
				200
			],
			"head": [
				204
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": true,
				"headers": false,
				"cookies": false,
				"body": false
			},
			"put": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": true
			},
			"head": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": [],
			"put": [],
			"head": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"catalog",
			"items",
			"$itemId"
		]
	}
] as const;

export type CatalogItemsItemIdCtx = {
	readonly __empty?: never;
};

export type RoutaRouteCtxByPath = {
	"/catalog/items/:itemId": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
	};
};

export type RoutaCtxByKey = { readonly __empty?: never };

declare module "@routa-ts/core" {
	export interface Register {
		routeCtxByPath: RoutaRouteCtxByPath;
		ctxByKey: RoutaCtxByKey;
	}
}
