// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const Status = z.object({
	ok: z.boolean(),
	service: z.string(),
});

export const GetStatusResponse = Status;
