// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: src/routes directory

export const routaRoutes = [
	{
		"file": "src/routes/demo/route.ts",
		"path": "/demo",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"demo"
		]
	},
	{
		"file": "src/routes/status/route.ts",
		"path": "/status",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"status"
		]
	},
	{
		"file": "src/routes/users/$userId/posts/route.ts",
		"path": "/users/:userId/posts",
		"methods": [
			"GET"
		],
		"responses": {
			"get": [
				200
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": true,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"users",
			"$userId",
			"posts"
		]
	},
	{
		"file": "src/routes/users/$userId/route.ts",
		"path": "/users/:userId",
		"methods": [
			"GET",
			"PATCH",
			"DELETE"
		],
		"responses": {
			"get": [
				200
			],
			"patch": [
				200
			],
			"delete": [
				204
			]
		},
		"inputs": {
			"get": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			},
			"patch": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": true
			},
			"delete": {
				"params": true,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": false
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": [],
			"patch": [],
			"delete": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"users",
			"$userId"
		]
	},
	{
		"file": "src/routes/users/route.ts",
		"path": "/users",
		"methods": [
			"GET",
			"POST"
		],
		"responses": {
			"get": [
				200
			],
			"post": [
				201
			]
		},
		"inputs": {
			"get": {
				"params": false,
				"query": true,
				"headers": false,
				"cookies": false,
				"body": false
			},
			"post": {
				"params": false,
				"query": false,
				"headers": false,
				"cookies": false,
				"body": true
			}
		},
		"middleware": [],
		"methodMiddleware": {
			"get": [],
			"post": []
		},
		"ctx": [],
		"groups": [],
		"segments": [
			"users"
		]
	}
] as const;

export type DemoCtx = {
	readonly __empty?: never;
};

export type StatusCtx = {
	readonly __empty?: never;
};

export type UsersUserIdPostsCtx = {
	readonly __empty?: never;
};

export type UsersUserIdCtx = {
	readonly __empty?: never;
};

export type UsersCtx = {
	readonly __empty?: never;
};

export type RoutaRouteCtxByPath = {
	"/demo": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
		options: { readonly __empty?: never };
	};
	"/status": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
		options: { readonly __empty?: never };
	};
	"/users/:userId/posts": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
		options: { readonly __empty?: never };
	};
	"/users/:userId": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
		options: { readonly __empty?: never };
	};
	"/users": {
		get: { readonly __empty?: never };
		post: { readonly __empty?: never };
		put: { readonly __empty?: never };
		patch: { readonly __empty?: never };
		delete: { readonly __empty?: never };
		head: { readonly __empty?: never };
		options: { readonly __empty?: never };
	};
};

export type RoutaCtxByKey = { readonly __empty?: never };

declare module "@routa-ts/core" {
	export interface Register {
		routeCtxByPath: RoutaRouteCtxByPath;
		ctxByKey: RoutaCtxByKey;
	}
}
