import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { validateProject } from "./project.js";

type OpenApiLike = {
	openapi?: string;
	info?: unknown;
	paths?: Record<
		string,
		Record<
			string,
			{
				parameters?: Array<Record<string, unknown>>;
				requestBody?: Record<string, unknown>;
				responses?: Record<string, unknown>;
			}
		>
	>;
};

export function runOpenApiCheck(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const baseline = readBaseline(cwd);

	if (!baseline) {
		return { code: 1, stderr: "Missing .routa/openapi-baseline.json. Run routa scaffold first.\n" };
	}

	const current = generateOpenApi(cwd);
	const diagnostics = driftDiagnostics(baseline, current);

	if (diagnostics.length > 0) {
		return { code: 1, stderr: `${diagnostics.join("\n")}\n` };
	}

	return { code: 0, stdout: "OpenAPI check passed. No drift detected.\n" };
}

export function runOpenApiBreaking(
	argv: readonly string[],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	const baseline = readBaseline(cwd);

	if (!baseline) {
		return { code: 1, stderr: "Missing .routa/openapi-baseline.json. Run routa scaffold first.\n" };
	}

	const current = generateOpenApi(cwd);
	const diagnostics = removedOperationDiagnostics(baseline, current);

	if (argv.includes("--update-baseline")) {
		writeFileSync(
			join(cwd, ".routa/openapi-baseline.json"),
			`${JSON.stringify(current, null, "\t")}\n`,
		);
		return { code: 0, stdout: "OpenAPI baseline updated.\n" };
	}

	if (diagnostics.length > 0) {
		return { code: 0, stdout: `${diagnostics.join("\n")}\n` };
	}

	return { code: 0, stdout: "OpenAPI breaking check passed. No removed operations detected.\n" };
}

export function generateOpenApi(cwd = process.cwd()): OpenApiLike {
	const validation = validateProject(cwd);
	const paths: NonNullable<OpenApiLike["paths"]> = {};

	for (const route of validation.routes) {
		paths[route.path.replaceAll(/:([^/]+)/g, "{$1}")] = Object.fromEntries(
			Object.entries(route.responses).map(([method, statuses]) => [
				method,
				{
					...operationInput(route.path, route.inputs[method]),
					responses: Object.fromEntries(
						statuses.map((status) => [
							String(status),
							{
								description: "Generated by Routa",
								content: {
									"application/json": {
										schema: { type: "object" },
									},
								},
							},
						]),
					),
				},
			]),
		);
	}

	return {
		openapi: "3.1.0",
		info: { title: "Routa API", version: "0.0.0" },
		paths,
	};
}

function operationInput(
	path: string,
	input: { params: boolean; query: boolean; body: boolean } | undefined,
) {
	return {
		...(input?.params
			? {
					parameters: pathParams(path).map((name) => ({
						name,
						in: "path",
						required: true,
						schema: { type: "string" },
					})),
				}
			: {}),
		...(input?.body
			? {
					requestBody: {
						content: {
							"application/json": {
								schema: { type: "object" },
							},
						},
					},
				}
			: {}),
	};
}

function pathParams(path: string): string[] {
	return Array.from(path.matchAll(/:([^/]+)/g)).map((match) => match[1]);
}

function driftDiagnostics(baseline: OpenApiLike, current: OpenApiLike): string[] {
	const diagnostics: string[] = [];

	for (const [path, methods] of Object.entries(baseline.paths ?? {})) {
		for (const [method, operation] of Object.entries(methods)) {
			const currentOperation = current.paths?.[path]?.[method];

			if (!currentOperation) {
				diagnostics.push(`OPENAPI_DRIFT: ${method.toUpperCase()} ${path} removed`);
				continue;
			}

			for (const status of Object.keys(operation.responses ?? {})) {
				if (!(status in (currentOperation.responses ?? {}))) {
					diagnostics.push(
						`OPENAPI_DRIFT: ${method.toUpperCase()} ${path} response ${status} removed`,
					);
				}
			}
		}
	}

	for (const [path, methods] of Object.entries(current.paths ?? {})) {
		for (const [method, operation] of Object.entries(methods)) {
			const baselineResponses = baseline.paths?.[path]?.[method]?.responses ?? {};
			const currentStatuses = Object.keys(operation.responses ?? {});

			for (const status of currentStatuses) {
				if (!(status in baselineResponses)) {
					diagnostics.push(`OPENAPI_DRIFT: ${method.toUpperCase()} ${path} response ${status}`);
				}
			}
		}
	}

	return diagnostics;
}

function removedOperationDiagnostics(baseline: OpenApiLike, current: OpenApiLike): string[] {
	const diagnostics: string[] = [];

	for (const [path, methods] of Object.entries(baseline.paths ?? {})) {
		for (const method of Object.keys(methods)) {
			if (!current.paths?.[path]?.[method]) {
				diagnostics.push(`OPENAPI_REMOVED_OPERATION: ${method.toUpperCase()} ${path}`);
			}
		}
	}

	return diagnostics;
}

function readBaseline(cwd: string): OpenApiLike | undefined {
	const file = join(cwd, ".routa/openapi-baseline.json");

	if (!existsSync(file)) {
		return undefined;
	}

	return JSON.parse(readFileSync(file, "utf8")) as OpenApiLike;
}
