import { type ChildProcess, spawn, spawnSync } from "node:child_process";
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	realpathSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import * as ts from "typescript";

export type Diagnostic = {
	code: string;
	severity: "error";
	message: string;
	file?: string;
	routePath?: string;
	suggestion?: string;
};

export type RouteMetadata = {
	file: string;
	path: string;
	methods: string[];
	responses: Record<string, number[]>;
	inputs: Record<string, RouteMethodInputMetadata>;
	middleware: MiddlewareMetadata[];
	methodMiddleware: Record<string, MiddlewareMetadata[]>;
	ctx: string[];
	groups: string[];
	segments: string[];
};

export type RouteMethodInputMetadata = {
	params: boolean;
	query: boolean;
	headers: boolean;
	cookies: boolean;
	body: boolean;
};

export type MiddlewareMetadata = {
	file: string;
	name: string;
	requires: string[];
	provides: string[];
	providesTypes: Record<string, string>;
	rejects: MiddlewareRejectMetadata[];
};

export type MiddlewareRejectMetadata = {
	type: string;
	status: number;
	schema: string;
};

export type ProjectValidationResult = {
	routes: RouteMetadata[];
	diagnostics: Diagnostic[];
};

const generatedHeader =
	"// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: src/routes directory\n\n";

const routesRoot = join("src", "routes");
const devPollMs = 300;
const devRestartDebounceMs = 150;
const httpMethods = new Set(["get", "post", "put", "patch", "delete", "head", "options"]);
const emptyRouteInputs: RouteMethodInputMetadata = {
	params: false,
	query: false,
	headers: false,
	cookies: false,
	body: false,
};
const routeStubSource = `import { createRoute, defineRoute } from "@routa-ts/core";

export default defineRoute({
\tget: createRoute({
\t\tresponses: {},
\t\trun: () => {
\t\t\treturn { type: "success", data: null };
\t\t},
\t}),
});
`;

/**
 * Validates a Routa project and optionally generates route metadata when validation succeeds.
 *
 * @param cwd - The project root directory
 * @param options - Validation options
 * @param options.write - When `true` (default), write `.routa/routes.gen.ts` after a clean validation
 * @returns The discovered routes and any validation diagnostics
 */
export function validateProject(
	cwd = process.cwd(),
	options: { write?: boolean } = {},
): ProjectValidationResult {
	const write = options.write ?? true;
	const discovery = discoverRoutes(cwd);
	const routes = discovery.routes;
	const diagnostics = [
		...projectStructureDiagnostics(cwd),
		...discovery.diagnostics,
		...runResultShapeDiagnostics(cwd),
		...duplicateRouteDiagnostics(routes),
		...missingSuccessResponseDiagnostics(routes),
		...duplicateSchemaDiagnostics(cwd),
		...middlewareOrderDiagnostics(routes),
		...middlewareRejectStatusDiagnostics(routes),
	];

	if (write && diagnostics.length === 0) {
		writeRoutesMetadata(cwd, routes);
	}

	return { routes, diagnostics };
}

/**
 * Runs project validation and a TypeScript no-emit check.
 *
 * @returns A result object containing the exit code and any captured output.
 */
export function runProjectCheck(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const stdout = [
		`Routa validation passed for ${validation.routes.length} route file(s).`,
		"Running TypeScript check: tsc -p tsconfig.json --noEmit",
	];
	const typecheck = runTypeScript(cwd, ["-p", "tsconfig.json", "--noEmit"]);

	if (typecheck.code !== 0) {
		return {
			code: typecheck.code,
			stdout: appendOutput(stdout, typecheck.stdout),
			stderr: appendOutput(["TypeScript check failed."], typecheck.stderr),
		};
	}

	return {
		code: 0,
		stdout: appendOutput([...stdout, "TypeScript check passed.", "Routa check passed."]),
	};
}

/**
 * Builds a Routa project after validating its routes.
 *
 * @returns Build output. On success, `stdout` reports how many route files passed validation and build.
 */
export function runProjectBuild(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const build = runTypeScript(cwd, ["-p", "tsconfig.json"]);

	if (build.code !== 0) {
		return build;
	}

	return { code: 0, stdout: `Routa build passed for ${validation.routes.length} route file(s).\n` };
}

/**
 * Prints a route reference from Routa's validated route metadata.
 *
 * @param argv - Command-line arguments for route reference formatting
 * @param cwd - Project root directory
 * @returns The formatted route reference or validation/argument diagnostics
 */
export function runProjectRoutes(
	argv: readonly string[] = [],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	const format = routeReferenceFormat(argv);

	if (!format) {
		return {
			code: 1,
			stderr: "Invalid routes format. Use --format json or --format markdown.\n",
		};
	}

	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	return {
		code: 0,
		stdout:
			format === "json"
				? `${JSON.stringify(routeReference(validation.routes), null, "\t")}\n`
				: routeReferenceMarkdown(validation.routes),
	};
}

/**
 * Runs the Routa project in dev mode.
 *
 * @param argv - Command-line arguments to pass to the server launcher
 * @param cwd - Project root directory
 * @returns The process result, including an exit code and any captured output
 */
export function runProjectDev(
	argv: readonly string[] = [],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	return runProjectServer("dev", argv, cwd);
}

/**
 * Starts the Routa development supervisor.
 *
 * Prepares the dev runtime, writes any preparation output to the console on failure or when printing the runtime command, and then supervises the runtime process for source changes.
 *
 * @param argv - Command-line arguments to pass to the dev server
 * @param cwd - Project root directory
 */
export function runProjectDevProcess(argv: readonly string[] = [], cwd = process.cwd()): void {
	const result = prepareProjectServer("dev", argv, cwd);

	if (result.code !== 0 || result.print) {
		writeCommandResult(result);
		process.exitCode = result.code;
		return;
	}

	runDevSupervisor(cwd, result.runtimeFile);
}

/**
 * Starts the Routa project server.
 *
 * @param argv - Command-line arguments to pass to the server preparation step
 * @param cwd - The project working directory
 * @returns The command result with an exit code and optional output
 */
export function runProjectStart(
	argv: readonly string[] = [],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	return runProjectServer("start", argv, cwd);
}

/**
 * Prepares and launches the project runtime for development or production start.
 *
 * @param mode - The server mode to prepare.
 * @param argv - Command-line arguments to pass to server preparation.
 * @param cwd - The working directory of the project.
 * @returns The preparation result, or the spawned process result code.
 */
function runProjectServer(
	mode: "dev" | "start",
	argv: readonly string[],
	cwd: string,
): { code: number; stdout?: string; stderr?: string } {
	const result = prepareProjectServer(mode, argv, cwd);

	if (result.code !== 0 || result.print) {
		return result;
	}

	const server = spawnSync(
		process.execPath,
		runtimeArgs(result.runtimeFile, cwd, result.runtimeRoot, result.useTsx),
		{
			cwd,
			encoding: "utf8",
			stdio: "inherit",
		},
	);

	return { code: server.status ?? 1 };
}

type PreparedServer = {
	code: number;
	stdout?: string;
	stderr?: string;
	runtimeFile: string;
	runtimeRoot: string;
	useTsx: boolean;
	print: boolean;
};

/**
 * Prepares a project server launch or dev-supervision run.
 *
 * In dev mode, empty route files are stubbed before validation. If validation fails, the returned result
 * contains the formatted diagnostics. Otherwise, the runtime file is resolved and the project is
 * type-checked before the server can start.
 *
 * @param mode - The server mode to prepare.
 * @param argv - Command-line arguments passed to the server command.
 * @param cwd - The project root directory.
 * @returns The prepared server result, including the runtime file path when preparation succeeds.
 */
function prepareProjectServer(
	mode: "dev" | "start",
	argv: readonly string[],
	cwd: string,
): PreparedServer {
	if (mode === "dev") {
		stubEmptyRouteFiles(cwd);
	}

	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
			runtimeFile: "",
			runtimeRoot: "",
			useTsx: false,
			print: false,
		};
	}

	const runtimeFile = join(dirname(fileURLToPath(import.meta.url)), "runtime.js");
	const runtimeRoot = mode === "start" ? join(cwd, "dist") : cwd;
	const useTsx = mode === "dev";
	const runtimeOutputError =
		mode === "start" ? validateRuntimeOutput(cwd, runtimeRoot, validation.routes) : undefined;

	if (runtimeOutputError) {
		return {
			code: 1,
			stderr: `${runtimeOutputError}\n`,
			runtimeFile,
			runtimeRoot,
			useTsx,
			print: false,
		};
	}

	if (argv.includes("--print")) {
		return { code: 0, stdout: `${runtimeFile}\n`, runtimeFile, runtimeRoot, useTsx, print: true };
	}

	if (mode === "start") {
		return { code: 0, runtimeFile, runtimeRoot, useTsx, print: false };
	}

	const typecheck = runTypeScript(cwd, ["-p", "tsconfig.json", "--noEmit"]);
	if (typecheck.code !== 0) {
		return {
			...typecheck,
			runtimeFile,
			runtimeRoot,
			useTsx,
			print: false,
		};
	}

	return { code: 0, runtimeFile, runtimeRoot, useTsx, print: false };
}

function validateRuntimeOutput(
	cwd: string,
	runtimeRoot: string,
	routes: readonly RouteMetadata[],
): string | undefined {
	const runtimeFiles = new Set(["src/routa.ts", ".routa/routes.gen.ts"]);

	for (const route of routes) {
		runtimeFiles.add(route.file);
		const schemaFile = join(dirname(route.file), "schemas.ts");
		if (existsSync(join(cwd, schemaFile))) {
			runtimeFiles.add(schemaFile);
		}
		for (const middleware of route.middleware) {
			runtimeFiles.add(middleware.file);
		}
		for (const middlewareList of Object.values(route.methodMiddleware)) {
			for (const middleware of middlewareList) {
				runtimeFiles.add(middleware.file);
			}
		}
	}

	for (const file of runtimeFiles) {
		const sourceFile = join(cwd, file);
		const outputFile = join(runtimeRoot, file.replace(/\.ts$/, ".js"));

		if (!existsSync(outputFile)) {
			return `Missing compiled runtime output for ${file}. Run routa build first.`;
		}

		if (statSync(outputFile).mtimeMs < statSync(sourceFile).mtimeMs) {
			return `Compiled runtime output for ${file} is stale. Run routa build first.`;
		}
	}

	return undefined;
}

/**
 * Writes captured output to the process streams.
 *
 * @param result - The command output to write.
 */
function writeCommandResult(result: { stdout?: string; stderr?: string }): void {
	if (result.stdout) {
		process.stdout.write(result.stdout);
	}

	if (result.stderr) {
		process.stderr.write(result.stderr);
	}
}

/**
 * Builds the command-line arguments for launching the Routa runtime.
 *
 * @param runtimeFile - The runtime script to execute
 * @param cwd - The project directory passed to the runtime
 * @returns The argument list for the Node process
 */
function runtimeArgs(
	runtimeFile: string,
	cwd: string,
	runtimeRoot: string,
	useTsx: boolean,
): string[] {
	return [...(useTsx ? ["--import", "tsx"] : []), runtimeFile, cwd, runtimeRoot];
}

/**
 * Supervises the Routa dev runtime and restarts it when source files change.
 *
 * Re-stubs empty route files before each validation, reports validation diagnostics, and exits cleanly on termination signals.
 * Restarts are debounced and wait for the previous child process to exit before respawning.
 */
function runDevSupervisor(cwd: string, runtimeFile: string): void {
	let child = startRuntimeProcess(cwd, runtimeFile);
	let snapshot = sourceSnapshot(cwd);
	let restartTimer: ReturnType<typeof setTimeout> | undefined;
	let restarting = false;
	let restartQueued = false;

	const restart = async () => {
		if (restarting) {
			restartQueued = true;
			return;
		}

		restarting = true;

		try {
			do {
				restartQueued = false;
				const nextSnapshot = sourceSnapshot(cwd);

				if (!sourceSnapshotChanged(snapshot, nextSnapshot)) {
					continue;
				}

				for (const file of stubEmptyRouteFiles(cwd)) {
					process.stdout.write(`Stubbed ${file}\n`);
				}

				const validation = validateProject(cwd);

				if (validation.diagnostics.length > 0) {
					process.stderr.write(formatDiagnostics(validation.diagnostics));
					snapshot = sourceSnapshot(cwd);
					continue;
				}

				process.stdout.write("Restarting Routa dev server...\n");
				const previous = child;
				previous.kill();
				await waitForChildExit(previous);
				child = startRuntimeProcess(cwd, runtimeFile);
				snapshot = sourceSnapshot(cwd);
			} while (restartQueued);
		} finally {
			restarting = false;
		}
	};

	const scheduleRestart = () => {
		if (!sourceSnapshotChanged(snapshot, sourceSnapshot(cwd))) {
			return;
		}

		if (restartTimer) {
			clearTimeout(restartTimer);
		}

		restartTimer = setTimeout(() => {
			restartTimer = undefined;
			void restart();
		}, devRestartDebounceMs);
	};

	const timer = setInterval(scheduleRestart, devPollMs);
	const stop = () => {
		clearInterval(timer);
		if (restartTimer) {
			clearTimeout(restartTimer);
		}
		child.kill();
		process.exit(0);
	};

	process.once("SIGINT", stop);
	process.once("SIGTERM", stop);
}

/**
 * Resolves when a child process has exited.
 */
function waitForChildExit(child: ChildProcess): Promise<void> {
	if (child.exitCode !== null || child.signalCode !== null) {
		return Promise.resolve();
	}

	return new Promise((resolve) => {
		child.once("exit", () => resolve());
	});
}

/**
 * Starts the Routa runtime process.
 *
 * @param cwd - Working directory for the spawned process
 * @param runtimeFile - Path to the generated runtime entry file
 * @returns The spawned child process
 */
function startRuntimeProcess(cwd: string, runtimeFile: string): ChildProcess {
	return spawn(process.execPath, runtimeArgs(runtimeFile, cwd, cwd, true), {
		cwd,
		stdio: "inherit",
	});
}

export type SourceSnapshot = Map<string, number>;

/**
 * Replaces empty route files with the default route stub.
 *
 * @param cwd - Project root directory
 * @returns The relative paths of the files that were written
 */
export function stubEmptyRouteFiles(cwd = process.cwd()): string[] {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return [];
	}

	const files = walk(routesDir).filter((file) => file.endsWith(`${sep}route.ts`));
	const written: string[] = [];

	for (const file of files) {
		const content = readFileSync(file, "utf8");

		if (content.trim() !== "") {
			continue;
		}

		writeFileSync(file, routeStubSource);
		written.push(relative(cwd, file));
	}

	return written;
}

/**
 * Captures modification times for Routa source files.
 *
 * @returns A map of file paths relative to `cwd` to their last modification time in milliseconds.
 */
export function sourceSnapshot(cwd = process.cwd()): SourceSnapshot {
	const files = [
		...walk(join(cwd, "src")).filter((file) => file.endsWith(".ts")),
		join(cwd, ".routa/routes.gen.ts"),
	].filter((file) => existsSync(file));
	const snapshot: SourceSnapshot = new Map();

	for (const file of files) {
		snapshot.set(relative(cwd, file), statSync(file).mtimeMs);
	}

	return snapshot;
}

/**
 * Detects whether two source snapshots differ.
 *
 * @param previous - The earlier snapshot
 * @param next - The later snapshot
 * @returns `true` if the snapshots differ, `false` otherwise.
 */
export function sourceSnapshotChanged(previous: SourceSnapshot, next: SourceSnapshot): boolean {
	if (previous.size !== next.size) {
		return true;
	}

	for (const [file, mtime] of next) {
		if (previous.get(file) !== mtime) {
			return true;
		}
	}

	return false;
}

type RouteReferenceFormat = "json" | "markdown";

type RouteReference = {
	routes: RouteReferenceRoute[];
};

type RouteReferenceRoute = {
	path: string;
	file: string;
	groups: string[];
	segments: string[];
	methods: RouteReferenceMethod[];
};

type RouteReferenceMethod = {
	method: string;
	inputs: RouteMethodInputMetadata;
	responses: number[];
	ctx: string[];
	rejects: MiddlewareRejectMetadata[];
	middleware: Array<
		Pick<MiddlewareMetadata, "file" | "name" | "requires" | "provides" | "rejects">
	>;
};

/**
 * Reads the requested route reference output format from CLI arguments.
 *
 * @param argv - Command-line arguments after `routes`
 * @returns The requested format, or `undefined` when the format is invalid
 */
function routeReferenceFormat(argv: readonly string[]): RouteReferenceFormat | undefined {
	const formatArg = argv.find((item) => item.startsWith("--format"));

	if (!formatArg) {
		return "markdown";
	}

	const value = formatArg.includes("=")
		? formatArg.slice(formatArg.indexOf("=") + 1)
		: argv[argv.indexOf(formatArg) + 1];

	return value === "json" || value === "markdown" ? value : undefined;
}

/**
 * Projects route metadata into a public route reference shape.
 *
 * @param routes - Validated route metadata
 * @returns Route reference data suitable for JSON or Markdown rendering
 */
function routeReference(routes: readonly RouteMetadata[]): RouteReference {
	return {
		routes: [...routes]
			.sort(
				(left, right) => left.path.localeCompare(right.path) || left.file.localeCompare(right.file),
			)
			.map((route) => ({
				path: route.path,
				file: route.file,
				groups: route.groups,
				segments: route.segments,
				methods: [...route.methods]
					.sort((left, right) => left.localeCompare(right))
					.map((method) => routeReferenceMethod(route, method)),
			})),
	};
}

/**
 * Builds a method-level route reference entry.
 *
 * @param route - Route metadata that owns the method
 * @param method - Uppercase HTTP method name
 * @returns Method metadata with resolved middleware, context, rejects, inputs, and responses
 */
function routeReferenceMethod(route: RouteMetadata, method: string): RouteReferenceMethod {
	const key = method.toLowerCase();
	const middleware = route.methodMiddleware[key] ?? route.middleware;
	const ctx = Array.from(new Set(middleware.flatMap((item) => item.provides))).sort();
	const rejects = uniqueRejects(middleware.flatMap((item) => item.rejects));

	return {
		method,
		inputs: route.inputs[key] ?? { ...emptyRouteInputs },
		responses: [...(route.responses[key] ?? [])].sort((left, right) => left - right),
		ctx,
		rejects,
		middleware: middleware.map((item) => ({
			file: item.file,
			name: item.name,
			requires: item.requires,
			provides: item.provides,
			rejects: item.rejects,
		})),
	};
}

/**
 * Renders validated route metadata as a Markdown route reference.
 *
 * @param routes - Validated route metadata
 * @returns Markdown route reference
 */
function routeReferenceMarkdown(routes: readonly RouteMetadata[]): string {
	const reference = routeReference(routes);
	const lines = ["# Routa Route Reference", ""];

	if (reference.routes.length === 0) {
		lines.push("No routes found.", "");
		return lines.join("\n");
	}

	for (const route of reference.routes) {
		lines.push(`## ${route.path}`, "", `File: \`${route.file}\``);

		if (route.groups.length > 0) {
			lines.push(`Groups: ${route.groups.map((item) => `\`${item}\``).join(", ")}`);
		}

		if (route.segments.length > 0) {
			lines.push(`Segments: ${route.segments.map((item) => `\`${item}\``).join(", ")}`);
		}

		lines.push("");

		for (const method of route.methods) {
			lines.push(
				`### ${method.method}`,
				"",
				`Inputs: ${inputList(method.inputs).join(", ") || "none"}`,
				`Responses: ${method.responses.join(", ") || "none"}`,
				`Context: ${method.ctx.map((item) => `\`ctx.${item}\``).join(", ") || "none"}`,
				`Rejects: ${method.rejects.map((item) => `\`${item.type}\` (${item.status})`).join(", ") || "none"}`,
				"",
				"Middleware:",
			);

			if (method.middleware.length === 0) {
				lines.push("- none");
			} else {
				for (const middleware of method.middleware) {
					lines.push(
						`- \`${middleware.name}\` from \`${middleware.file}\``
							+ `; requires: ${middleware.requires.join(", ") || "none"}`
							+ `; provides: ${middleware.provides.join(", ") || "none"}`
							+ `; rejects: ${middleware.rejects.map((item) => `${item.type}:${item.status}`).join(", ") || "none"}`,
					);
				}
			}

			lines.push("");
		}
	}

	return `${lines.join("\n")}\n`;
}

/**
 * Converts input metadata into a compact list of declared input locations.
 *
 * @param inputs - Route method input metadata
 * @returns Declared input location names
 */
function inputList(inputs: RouteMethodInputMetadata): string[] {
	return (["params", "query", "headers", "cookies", "body"] as const).filter((key) => inputs[key]);
}

function uniqueRejects(rejects: readonly MiddlewareRejectMetadata[]): MiddlewareRejectMetadata[] {
	const unique = new Map<string, MiddlewareRejectMetadata>();

	for (const reject of rejects) {
		unique.set(reject.type, reject);
	}

	return Array.from(unique.values()).sort((left, right) => left.type.localeCompare(right.type));
}

type RouteDiscovery = {
	routes: RouteMetadata[];
	diagnostics: Diagnostic[];
};

/**
 * Discovers route metadata from a Routa project's route files.
 *
 * @param cwd - Project root directory
 * @returns The discovered route metadata for each `route.ts` file under `src/routes`, plus discovery diagnostics
 */
function discoverRoutes(cwd: string): RouteDiscovery {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return { routes: [], diagnostics: [] };
	}

	const files = walk(routesDir).filter((file) => file.endsWith(`${sep}route.ts`));
	const diagnostics: Diagnostic[] = [];

	const routes = files.flatMap((file) => {
		const relativeFile = relative(cwd, file);
		const relativeRouteDir = relative(routesDir, dirname(file));
		const rawSegments = relativeRouteDir === "" ? [] : relativeRouteDir.split(sep);
		const groups = rawSegments.filter(
			(segment) => segment.startsWith("(") && segment.endsWith(")"),
		);
		const segments = rawSegments.filter(
			(segment) => !(segment.startsWith("(") && segment.endsWith(")")),
		);
		const pathSegments = segments.map((segment) =>
			segment.startsWith("$") ? `:${segment.slice(1)}` : segment,
		);
		const inheritedMiddleware = middlewareChain(cwd, rawSegments);
		const routeFileMiddleware = parseRouteFileMiddleware(cwd, relativeFile);
		const middleware = [...inheritedMiddleware, ...routeFileMiddleware.route];
		const methodMiddleware = Object.fromEntries(
			Object.entries(routeFileMiddleware.methods).map(([method, items]) => [
				method,
				[...middleware, ...items],
			]),
		);
		const path = `/${pathSegments.join("/")}`.replace(/\/$/, "") || "/";
		const parsed = parseRouteContract(file);

		if (!parsed.configFound) {
			diagnostics.push({
				code: "ROUTA_ROUTE_CONFIG_UNRESOLVED",
				severity: "error",
				message: `Route config in ${relativeFile} could not be resolved.`,
				file: relativeFile,
				routePath: path,
				suggestion:
					"Export `defineRoute({ ... })` directly, or `export default routeConfig` where `routeConfig` is initialized with `defineRoute({ ... })`.",
			});
			return [];
		}

		const contract = parsed.contract;
		const ctx = Array.from(
			new Set([
				...middleware.flatMap((item) => item.provides),
				...Object.values(methodMiddleware).flatMap((items) =>
					items.flatMap((item) => item.provides),
				),
			]),
		).sort();

		for (const unresolved of routeFileMiddleware.unresolved) {
			diagnostics.push({
				code: "ROUTA_MIDDLEWARE_UNRESOLVED",
				severity: "error",
				message: `Middleware ${unresolved} cannot be statically resolved, so it would run without contract checks.`,
				file: relativeFile,
				routePath: path,
				suggestion:
					"Reference middleware as a direct identifier of a createMiddleware export, and list entries explicitly instead of spreading arrays.",
			});
		}

		return [
			{
				file: relativeFile,
				path,
				methods: Object.keys(contract).map((method) => method.toUpperCase()),
				responses: Object.fromEntries(
					Object.entries(contract).map(([method, metadata]) => [
						method,
						methodResponseStatuses(metadata.responses, methodMiddleware[method] ?? middleware),
					]),
				),
				inputs: Object.fromEntries(
					Object.entries(contract).map(([method, metadata]) => [method, metadata.inputs]),
				),
				middleware,
				methodMiddleware,
				ctx,
				groups,
				segments,
			},
		];
	});

	return { routes, diagnostics };
}

/**
 * Extracts route method contract metadata from a route file.
 *
 * @param file - Path to the route file
 * @returns Parsed contract metadata and whether a route config object was found
 */
function parseRouteContract(file: string): {
	configFound: boolean;
	contract: Record<
		string,
		{ responses: number[]; responseTypes: string[]; inputs: RouteMethodInputMetadata }
	>;
} {
	const contract: Record<
		string,
		{ responses: number[]; responseTypes: string[]; inputs: RouteMethodInputMetadata }
	> = {};
	const sourceFile = parseTypeScriptFile(file);
	const routeConfig = routeConfigObject(sourceFile);

	if (!routeConfig) {
		return { configFound: false, contract };
	}

	for (const property of objectProperties(routeConfig)) {
		const method = propertyName(property.name);

		if (!method || !httpMethods.has(method)) {
			continue;
		}

		const routeContract = createRouteObject(property.initializer);

		if (!routeContract) {
			continue;
		}

		contract[method] = {
			responses: responseStatuses(routeContract),
			responseTypes: responseTypeKeys(routeContract),
			inputs: routeInputs(routeContract),
		};
	}

	return { configFound: true, contract };
}

function methodResponseStatuses(
	routeStatuses: readonly number[],
	middleware: readonly MiddlewareMetadata[],
): number[] {
	return Array.from(
		new Set([
			...routeStatuses,
			...middleware.flatMap((item) => item.rejects.map((reject) => reject.status)),
		]),
	).sort((left, right) => left - right);
}

/**
 * Collects the declared response type keys from a route contract.
 *
 * @param routeContract - The route contract object literal
 * @returns The property names declared under `responses`
 */
function responseTypeKeys(routeContract: ts.ObjectLiteralExpression): string[] {
	const responses = objectProperty(routeContract, "responses");
	const responsesObject = responses ? objectLiteral(responses.initializer) : undefined;

	if (!responsesObject) {
		return [];
	}

	return objectProperties(responsesObject).flatMap((property) => {
		const name = propertyName(property.name);
		return name ? [name] : [];
	});
}

/**
 * Reports route methods that do not declare a 2xx success response.
 *
 * DELETE methods are included and may satisfy the check with a 204 response.
 *
 * @param routes - Route metadata to inspect
 * @returns Diagnostics for route methods missing a declared 2xx response
 */
function missingSuccessResponseDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		for (const [method, statuses] of Object.entries(route.responses)) {
			if (!statuses.some((status) => status >= 200 && status < 300)) {
				diagnostics.push({
					code: "ROUTA_MISSING_SUCCESS_RESPONSE",
					severity: "error",
					message: `${method.toUpperCase()} ${route.path} is missing a 2xx success response.`,
					file: route.file,
					routePath: route.path,
					suggestion:
						method === "delete"
							? "Add a declared success response with a 2xx HTTP status (204 is allowed)."
							: "Add a declared success response with a 2xx HTTP status.",
				});
			}
		}
	}

	return diagnostics;
}

/**
 * Reports duplicate schema export names in route schema files.
 *
 * @param cwd - Project root directory
 * @returns Diagnostics for repeated `export const` names in route `schemas.ts` files under `src/routes`
 */
function duplicateSchemaDiagnostics(cwd: string): Diagnostic[] {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return [];
	}

	const diagnostics: Diagnostic[] = [];

	for (const file of walk(routesDir).filter((item) => item.endsWith(`${sep}schemas.ts`))) {
		const relativeFile = relative(cwd, file);
		const sourceFile = parseTypeScriptFile(file);
		const seen = new Set<string>();

		for (const statement of sourceFile.statements) {
			if (!ts.isVariableStatement(statement)) {
				continue;
			}

			if (!statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)) {
				continue;
			}

			if (!(statement.declarationList.flags & ts.NodeFlags.Const)) {
				continue;
			}

			for (const declaration of statement.declarationList.declarations) {
				if (!ts.isIdentifier(declaration.name)) {
					continue;
				}

				const name = declaration.name.text;

				if (seen.has(name)) {
					diagnostics.push({
						code: "ROUTA_DUPLICATE_SCHEMA_NAME",
						severity: "error",
						message: `Duplicate schema export ${name}.`,
						file: relativeFile,
						suggestion: "Use a stable contract-purpose name such as CreateUserResponse.",
					});
					continue;
				}

				seen.add(name);
			}
		}
	}

	return diagnostics;
}

function runResultShapeDiagnostics(cwd: string): Diagnostic[] {
	const srcDir = join(cwd, "src");

	if (!existsSync(srcDir)) {
		return [];
	}

	return walk(srcDir)
		.filter((file) => file.endsWith(".ts"))
		.flatMap((file) => runResultShapeDiagnosticsForFile(cwd, relative(cwd, file), file));
}

function runResultShapeDiagnosticsForFile(
	cwd: string,
	relativeFile: string,
	file: string,
): Diagnostic[] {
	const sourceFile = parseTypeScriptFile(file);
	const diagnostics: Diagnostic[] = [];

	function visit(node: ts.Node): void {
		if (
			ts.isCallExpression(node)
			&& (callName(node.expression) === "createRoute"
				|| callName(node.expression) === "createMiddleware")
			&& ts.isObjectLiteralExpression(node.arguments[0])
		) {
			const contract = node.arguments[0];
			const run = objectProperty(contract, "run");
			const resultTypes =
				callName(node.expression) === "createRoute"
					? contractObjectKeys(contract, "responses")
					: contractObjectKeys(contract, "rejects");

			if (run) {
				diagnostics.push(
					...runReturnObjectDiagnostics(
						cwd,
						sourceFile,
						relativeFile,
						run.initializer,
						resultTypes,
					),
				);
			}
		}

		ts.forEachChild(node, visit);
	}

	visit(sourceFile);
	return diagnostics;
}

function runReturnObjectDiagnostics(
	cwd: string,
	sourceFile: ts.SourceFile,
	file: string,
	run: ts.Expression,
	resultTypes: Set<string> | undefined,
): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	function checkReturn(expression: ts.Expression): void {
		const object = objectLiteral(expression);

		if (!object) {
			return;
		}

		for (const property of objectProperties(object)) {
			const name = propertyName(property.name);

			if (!name || name === "type" || name === "data") {
				continue;
			}

			const position = sourceFile.getLineAndCharacterOfPosition(property.name.getStart(sourceFile));
			diagnostics.push({
				code: "ROUTA_RESULT_SHAPE",
				severity: "error",
				message: `Run result includes unsupported field "${name}". Route and middleware results may only include "type" and "data".`,
				file: `${file}:${position.line + 1}:${position.character + 1}`,
				suggestion: `Remove "${name}" from the returned result object.`,
			});
		}

		const typeProperty = objectProperty(object, "type");
		const typeExpression = typeProperty ? unwrapExpression(typeProperty.initializer) : undefined;

		if (
			resultTypes
			&& typeProperty
			&& typeExpression
			&& ts.isStringLiteralLike(typeExpression)
			&& !resultTypes.has(typeExpression.text)
		) {
			const position = sourceFile.getLineAndCharacterOfPosition(
				typeProperty.initializer.getStart(sourceFile),
			);
			const options = [...resultTypes].map((type) => `"${type}"`).join(", ");
			diagnostics.push({
				code: "ROUTA_RESULT_TYPE",
				severity: "error",
				message: `Run result type "${typeExpression.text}" is not declared.`,
				file: `${file}:${position.line + 1}:${position.character + 1}`,
				suggestion: options
					? `Use one of the declared result types: ${options}.`
					: "Declare this result type before returning it.",
			});
		}
	}

	function visit(node: ts.Node): void {
		if (ts.isReturnStatement(node) && node.expression) {
			checkReturn(node.expression);
		}

		if (
			(ts.isArrowFunction(run) || ts.isFunctionExpression(run))
			&& run.body === node
			&& ts.isExpression(node)
		) {
			checkReturn(node);
		}

		ts.forEachChild(node, visit);
	}

	if (ts.isArrowFunction(run) || ts.isFunctionExpression(run)) {
		visit(run.body);
	}

	return diagnostics.map((diagnostic) => ({
		...diagnostic,
		file: diagnostic.file?.startsWith(cwd) ? relative(cwd, diagnostic.file) : diagnostic.file,
	}));
}

function contractObjectKeys(
	contract: ts.ObjectLiteralExpression,
	name: string,
): Set<string> | undefined {
	const property = objectProperty(contract, name);
	const object = objectLiteral(property?.initializer);

	if (!object) {
		return;
	}

	return new Set(
		objectProperties(object).flatMap((item) => {
			const key = propertyName(item.name);
			return key ? [key] : [];
		}),
	);
}

/**
 * Collects middleware declarations inherited from the route directory hierarchy.
 *
 * @param cwd - Project root directory
 * @param rawSegments - Route path segments used to locate nested `middleware.ts` files
 * @returns Middleware declarations from the global route middleware file and any matching nested middleware files
 */
function middlewareChain(cwd: string, rawSegments: string[]): MiddlewareMetadata[] {
	const candidates = [`${routesRoot}/middleware.ts`];
	let current = routesRoot;

	for (const segment of rawSegments) {
		current = join(current, segment);
		candidates.push(join(current, "middleware.ts"));
	}

	return candidates
		.filter((file) => existsSync(join(cwd, file)))
		.flatMap((file) => parseMiddlewareFile(cwd, file));
}

/**
 * Verifies that the required Routa project files and directories exist.
 *
 * @returns Diagnostics for each missing required project item.
 */
function projectStructureDiagnostics(cwd: string): Diagnostic[] {
	const required = [
		{ path: "package.json", message: "Missing package.json." },
		{ path: "tsconfig.json", message: "Missing tsconfig.json." },
		{ path: "src", message: "Missing src/ directory." },
		{ path: "src/routa.ts", message: "Missing src/routa.ts." },
	];

	return required
		.filter((item) => !existsSync(join(cwd, item.path)))
		.map((item) => ({
			code: "ROUTA_PROJECT_REQUIRED",
			severity: "error" as const,
			message: `${item.message} Routa commands must run inside a TypeScript Routa project.`,
			file: item.path,
			suggestion:
				"Create a project with pnpm create routa-ts@latest, or run this command at the project root.",
		}));
}

/**
 * Parses exported middleware declarations from a middleware file.
 *
 * @param cwd - Project root used to resolve `file`.
 * @param file - Path to the middleware file relative to `cwd`.
 * @returns Metadata for each exported middleware declaration found in the file.
 */
function parseMiddlewareFile(cwd: string, file: string): MiddlewareMetadata[] {
	const sourceFile = parseTypeScriptFile(join(cwd, file));

	return exportedMiddlewareDeclarations(cwd, file, sourceFile).map((block) =>
		middlewareMetadata(block.file, block.name, block.contract),
	);
}

/**
 * Resolves exported middleware declarations from a module and its re-exports.
 *
 * @param cwd - The project root directory
 * @param file - The module being inspected
 * @param sourceFile - The parsed TypeScript source file for `file`
 * @returns Middleware declarations found in the module graph
 */
function exportedMiddlewareDeclarations(
	cwd: string,
	file: string,
	sourceFile: ts.SourceFile,
	seen = new Set<string>(),
): Array<{ file: string; name: string; contract: ts.ObjectLiteralExpression }> {
	if (seen.has(file)) {
		return [];
	}

	seen.add(file);

	const declarations: Array<{
		file: string;
		name: string;
		contract: ts.ObjectLiteralExpression;
	}> = [];
	const imports = namedImportMap(cwd, file, sourceFile);

	for (const statement of sourceFile.statements) {
		if (ts.isVariableStatement(statement) && hasExportModifier(statement)) {
			for (const declaration of statement.declarationList.declarations) {
				if (!ts.isIdentifier(declaration.name) || !declaration.initializer) {
					continue;
				}

				const contract = createMiddlewareObject(declaration.initializer);

				if (contract) {
					declarations.push({ file, name: declaration.name.text, contract });
				}
			}
			continue;
		}

		if (!ts.isExportDeclaration(statement) || !statement.exportClause) {
			continue;
		}

		if (!ts.isNamedExports(statement.exportClause)) {
			continue;
		}

		const targetFile =
			statement.moduleSpecifier && ts.isStringLiteral(statement.moduleSpecifier)
				? resolveImportFile(cwd, file, statement.moduleSpecifier.text)
				: undefined;

		for (const specifier of statement.exportClause.elements) {
			const exportedName = specifier.name.text;
			const importedName = specifier.propertyName?.text ?? specifier.name.text;
			const source = targetFile
				? { file: targetFile, name: importedName }
				: imports.get(importedName);

			if (!source) {
				continue;
			}

			const targetAst = parseTypeScriptFile(join(cwd, source.file));
			const targetDeclarations = exportedMiddlewareDeclarations(cwd, source.file, targetAst, seen);
			const declaration = targetDeclarations.find((item) => item.name === source.name);

			if (declaration) {
				declarations.push({
					...declaration,
					name: source.name,
				});
				continue;
			}

			const direct = middlewareDeclarations(targetAst, true).find(
				(item) => item.name === source.name,
			);

			if (direct) {
				declarations.push({ file: source.file, name: source.name, contract: direct.contract });
				continue;
			}

			const local = middlewareDeclarations(targetAst, false).find(
				(item) => item.name === source.name,
			);

			if (local && exportedName === source.name) {
				declarations.push({ file: source.file, name: source.name, contract: local.contract });
			}
		}
	}

	return declarations;
}

/**
 * Maps named imports to their source module and exported name.
 *
 * @param cwd - The project root directory.
 * @param file - The file containing the import declarations.
 * @param sourceFile - The parsed TypeScript source file.
 * @returns A map from local import names to the resolved module file and imported name.
 */
function namedImportMap(
	cwd: string,
	file: string,
	sourceFile: ts.SourceFile,
): Map<string, { file: string; name: string }> {
	const imports = new Map<string, { file: string; name: string }>();

	for (const statement of sourceFile.statements) {
		if (
			!ts.isImportDeclaration(statement)
			|| !ts.isStringLiteral(statement.moduleSpecifier)
			|| !statement.importClause?.namedBindings
			|| !ts.isNamedImports(statement.importClause.namedBindings)
		) {
			continue;
		}

		const sourceFile = resolveImportFile(cwd, file, statement.moduleSpecifier.text);

		if (!sourceFile) {
			continue;
		}

		for (const specifier of statement.importClause.namedBindings.elements) {
			imports.set(specifier.name.text, {
				file: sourceFile,
				name: specifier.propertyName?.text ?? specifier.name.text,
			});
		}
	}

	return imports;
}

/**
 * Resolves a relative module specifier to an existing TypeScript file.
 *
 * @param cwd - The project root used to resolve candidate paths.
 * @param fromFile - The file containing the import or re-export.
 * @param specifier - The module specifier to resolve.
 * @returns The first matching file path relative to `cwd`, or `undefined` if no relative file exists.
 */
function resolveImportFile(cwd: string, fromFile: string, specifier: string): string | undefined {
	if (!specifier.startsWith(".")) {
		return;
	}

	const base = join(dirname(fromFile), specifier);
	const candidates = [
		base,
		base.endsWith(".js") ? `${base.slice(0, -3)}.ts` : undefined,
		base.endsWith(".ts") ? base : `${base}.ts`,
		join(base, "index.ts"),
	].filter((item): item is string => Boolean(item));

	return candidates.find((candidate) => existsSync(join(cwd, candidate)));
}

/**
 * Extracts middleware metadata declared in a route file.
 *
 * @param cwd - The project root directory.
 * @param routeFile - The route file path relative to `cwd`.
 * @returns The route-level middleware list and per-method middleware lists.
 */
function parseRouteFileMiddleware(
	cwd: string,
	routeFile: string,
): {
	route: MiddlewareMetadata[];
	methods: Record<string, MiddlewareMetadata[]>;
	unresolved: string[];
} {
	const sourceFile = parseTypeScriptFile(join(cwd, routeFile));
	const routeConfig = routeConfigObject(sourceFile);

	if (!routeConfig) {
		return { route: [], methods: {}, unresolved: [] };
	}

	const middleware = middlewareDeclarations(sourceFile, false);
	const middlewareByName = new Map(middleware.map((item) => [item.name, item.contract]));
	const imports = namedImportMap(cwd, routeFile, sourceFile);
	const route: MiddlewareMetadata[] = [];
	const methods: Record<string, MiddlewareMetadata[]> = {};
	const unresolved: string[] = [];
	const metadataForMiddleware = (expression: ts.Expression): MiddlewareMetadata | undefined => {
		const metadata = middlewareExpressionMetadata(expression, middlewareByName);

		if (metadata) {
			return middlewareMetadata(routeFile, metadata.name, metadata.contract);
		}

		const unwrapped = unwrapExpression(expression);

		if (!ts.isIdentifier(unwrapped)) {
			return;
		}

		const source = imports.get(unwrapped.text);

		if (!source) {
			return;
		}

		const targetAst = parseTypeScriptFile(join(cwd, source.file));
		const declaration =
			exportedMiddlewareDeclarations(cwd, source.file, targetAst).find(
				(item) => item.name === source.name,
			) ?? middlewareDeclarations(targetAst, true).find((item) => item.name === source.name);

		if (!declaration) {
			return;
		}

		return middlewareMetadata(routeFile, unwrapped.text, declaration.contract);
	};

	for (const property of objectProperties(routeConfig)) {
		if (propertyName(property.name) === "middleware") {
			const expressions = middlewareExpressions(property.initializer);
			unresolved.push(...expressions.unresolved);

			for (const expression of expressions.resolved) {
				const metadata = metadataForMiddleware(expression);

				if (metadata) {
					route.push(metadata);
				} else {
					unresolved.push(expression.getText());
				}
			}
		}
	}

	for (const property of objectProperties(routeConfig)) {
		const method = propertyName(property.name);

		if (!method || !httpMethods.has(method)) {
			continue;
		}

		const routeContract = createRouteObject(property.initializer);

		if (!routeContract) {
			continue;
		}

		const entries: MiddlewareMetadata[] = [];

		for (const routeProperty of objectProperties(routeContract)) {
			if (propertyName(routeProperty.name) !== "middleware") {
				continue;
			}

			const expressions = middlewareExpressions(routeProperty.initializer);
			unresolved.push(...expressions.unresolved);

			for (const expression of expressions.resolved) {
				const metadata = metadataForMiddleware(expression);

				if (metadata) {
					entries.push(metadata);
				} else {
					unresolved.push(expression.getText());
				}
			}
		}

		methods[method] = entries;
	}

	return { route, methods, unresolved };
}

/**
 * Extracts string literals from an object property's array value.
 *
 * @param source - The object literal to read from
 * @param property - The property name to inspect
 * @returns The string values found in the property's array, or an empty array when the property is missing or not an array of strings
 */
function stringArrayProperty(source: ts.ObjectLiteralExpression, property: string): string[] {
	const item = objectProperty(source, property);

	if (!item || !ts.isArrayLiteralExpression(item.initializer)) {
		return [];
	}

	return item.initializer.elements.flatMap((element) => {
		const expression = unwrapExpression(element);
		return ts.isStringLiteralLike(expression) ? [expression.text] : [];
	});
}

/**
 * Creates metadata for a middleware declaration.
 *
 * @returns Middleware metadata including its source file, name, required context keys, provided context keys and types, and rejected keys.
 */
function middlewareMetadata(
	file: string,
	name: string,
	contract: ts.ObjectLiteralExpression,
): MiddlewareMetadata {
	const provides = middlewareProvides(contract);
	const inferred = middlewareNextProvidesTypes(contract);

	return {
		file,
		name,
		requires: stringArrayProperty(contract, "requires"),
		provides: provides.keys,
		providesTypes: Object.fromEntries(
			provides.keys.map((provided) => [
				provided,
				provides.types[provided] ?? inferred[provided] ?? "unknown",
			]),
		),
		rejects: middlewareRejects(contract),
	};
}

function middlewareRejects(contract: ts.ObjectLiteralExpression): MiddlewareRejectMetadata[] {
	const item = objectProperty(contract, "rejects");
	const rejects = item ? objectLiteral(item.initializer) : undefined;

	if (!rejects) {
		return [];
	}

	return objectProperties(rejects).flatMap((property) => {
		const type = propertyName(property.name);
		const reject = objectLiteral(property.initializer);

		if (!type || !reject) {
			return [];
		}

		const statusProperty = objectProperty(reject, "status");
		const schemaProperty = objectProperty(reject, "schema");
		const status = statusProperty ? numericValue(statusProperty.initializer) : undefined;

		if (status === undefined || !schemaProperty) {
			return [];
		}

		return [
			{
				type,
				status,
				schema: schemaProperty.initializer.getText(),
			},
		];
	});
}

/**
 * Extracts the context keys and value types provided by a middleware contract.
 *
 * @param contract - The middleware contract object.
 * @returns The provided keys and their inferred types.
 */
function middlewareProvides(contract: ts.ObjectLiteralExpression): {
	keys: string[];
	types: Record<string, string>;
} {
	const item = objectProperty(contract, "provides");

	if (!item) {
		return { keys: [], types: {} };
	}

	const expression = unwrapExpression(item.initializer);

	if (!ts.isObjectLiteralExpression(expression)) {
		return { keys: [], types: {} };
	}

	const entries = objectProperties(expression).flatMap((property) => {
		const name = propertyName(property.name);
		return name ? [[name, zodType(property.initializer)] as const] : [];
	});

	return {
		keys: entries.map(([key]) => key),
		types: Object.fromEntries(entries),
	};
}

/**
 * Infers context value types supplied to the middleware's `next()` call.
 *
 * @returns A record mapping each context key to its inferred type.
 */
function middlewareNextProvidesTypes(contract: ts.ObjectLiteralExpression): Record<string, string> {
	const nextCtx = middlewareNextContext(contract);

	if (!nextCtx) {
		return {};
	}

	const inputTypes = middlewareInputTypes(contract);
	const result: Record<string, string> = {};

	for (const property of objectProperties(nextCtx)) {
		const name = propertyName(property.name);

		if (name) {
			result[name] = typeForExpression(property.initializer, inputTypes);
		}
	}

	return result;
}

/**
 * Finds the context object passed to `next()` in a middleware's `run` function.
 *
 * @param contract - The middleware contract object.
 * @returns The first object literal passed to `next()`, or `undefined` if none is found.
 */
function middlewareNextContext(
	contract: ts.ObjectLiteralExpression,
): ts.ObjectLiteralExpression | undefined {
	const run = objectProperty(contract, "run");

	if (!run) {
		return;
	}

	let context: ts.ObjectLiteralExpression | undefined;

	const visit = (node: ts.Node): void => {
		if (context) {
			return;
		}

		if (
			ts.isCallExpression(node)
			&& callName(node) === "next"
			&& node.arguments.length > 0
			&& ts.isExpression(node.arguments[0])
		) {
			context = objectLiteral(node.arguments[0]);
			return;
		}

		ts.forEachChild(node, visit);
	};

	visit(run.initializer);
	return context;
}

/**
 * Infers input field types declared by a middleware contract.
 *
 * @param contract - Middleware contract object literal
 * @returns A map of `location.field` paths to inferred type strings
 */
function middlewareInputTypes(contract: ts.ObjectLiteralExpression): Map<string, string> {
	const input = objectProperty(contract, "input");
	const inputObject = input ? objectLiteral(input.initializer) : undefined;
	const result = new Map<string, string>();

	if (!inputObject) {
		return result;
	}

	for (const location of objectProperties(inputObject)) {
		const locationName = propertyName(location.name);
		const schema = zodObjectShape(location.initializer);

		if (!locationName || !schema) {
			continue;
		}

		for (const property of objectProperties(schema)) {
			const name = propertyName(property.name);

			if (!name) {
				continue;
			}

			result.set(`${locationName}.${name}`, zodType(property.initializer));
		}
	}

	return result;
}

/**
 * Extracts the shape object from a Zod `object(...)` expression.
 *
 * @param expression - The expression to inspect
 * @returns The object literal shape when the expression is a `object(...)` call, `undefined` otherwise
 */
function zodObjectShape(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "object") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

/**
 * Infers a TypeScript type string from a Zod expression.
 *
 * @returns The inferred type string, or `"unknown"` when the expression is not recognized.
 */
function zodType(expression: ts.Expression): string {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return "unknown";
	}

	const call = callName(unwrapped);
	const callee = unwrapExpression(unwrapped.expression);

	if (call === "optional" && ts.isPropertyAccessExpression(callee)) {
		return `${zodType(callee.expression)} | undefined`;
	}

	if (call === "object") {
		const shape = objectLiteral(unwrapped.arguments[0]);

		if (!shape) {
			return "Record<string, unknown>";
		}

		return zodObjectType(shape);
	}

	if (call === "array") {
		return `Array<${unwrapped.arguments[0] ? zodType(unwrapped.arguments[0]) : "unknown"}>`;
	}

	if (call === "enum" && ts.isArrayLiteralExpression(unwrapped.arguments[0])) {
		const values = unwrapped.arguments[0].elements.flatMap((element) => {
			const value = unwrapExpression(element);
			return ts.isStringLiteralLike(value) ? [JSON.stringify(value.text)] : [];
		});

		return values.length > 0 ? values.join(" | ") : "string";
	}

	if (call === "string") {
		return "string";
	}

	if (call === "number" || call === "int") {
		return "number";
	}

	if (call === "boolean" || call === "stringbool") {
		return "boolean";
	}

	return "unknown";
}

/**
 * Builds a readonly object type from a Zod object shape.
 *
 * @param shape - The object literal that defines the Zod shape
 * @returns A TypeScript-like object type for the shape
 */
function zodObjectType(shape: ts.ObjectLiteralExpression): string {
	const properties = objectProperties(shape).flatMap((property) => {
		const name = propertyName(property.name);

		if (!name) {
			return [];
		}

		const optional = isZodOptional(property.initializer);
		return [
			`\treadonly ${JSON.stringify(name)}${optional ? "?" : ""}: ${zodType(property.initializer)};`,
		];
	});

	return properties.length > 0 ? `{\n${properties.join("\n")}\n}` : "{}";
}

/**
 * Determines whether an expression is a Zod optional schema.
 *
 * @param expression - The expression to inspect
 * @returns `true` if the expression is an `optional(...)` call, `false` otherwise
 */
function isZodOptional(expression: ts.Expression): boolean {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return false;
	}

	return callName(unwrapped) === "optional";
}

/**
 * Infers a string representation of the type produced by an expression.
 *
 * @param expression - The expression to analyze
 * @param inputTypes - Known types for `input` access paths
 * @returns A TypeScript-like type string for the expression
 */
function typeForExpression(expression: ts.Expression, inputTypes: Map<string, string>): string {
	const unwrapped = unwrapExpression(expression);

	if (ts.isStringLiteralLike(unwrapped) || ts.isTemplateExpression(unwrapped)) {
		return "string";
	}

	if (ts.isNumericLiteral(unwrapped)) {
		return "number";
	}

	if (
		unwrapped.kind === ts.SyntaxKind.TrueKeyword
		|| unwrapped.kind === ts.SyntaxKind.FalseKeyword
	) {
		return "boolean";
	}

	if (ts.isObjectLiteralExpression(unwrapped)) {
		return objectType(unwrapped, inputTypes);
	}

	if (ts.isConditionalExpression(unwrapped)) {
		return mergeTypes(
			typeForExpression(unwrapped.whenTrue, inputTypes),
			typeForExpression(unwrapped.whenFalse, inputTypes),
		);
	}

	if (
		ts.isBinaryExpression(unwrapped)
		&& unwrapped.operatorToken.kind === ts.SyntaxKind.QuestionQuestionToken
	) {
		return removeUndefined(
			typeForExpression(unwrapped.left, inputTypes),
			typeForExpression(unwrapped.right, inputTypes),
		);
	}

	const inputType = inputAccessType(unwrapped, inputTypes);

	if (inputType) {
		return inputType;
	}

	return "unknown";
}

/**
 * Formats an object literal as a readonly TypeScript object type.
 *
 * @returns A TypeScript type string with one readonly property per named object literal member, or `{}` when no named properties are present.
 */
function objectType(object: ts.ObjectLiteralExpression, inputTypes: Map<string, string>): string {
	const properties = objectProperties(object)
		.map((property) => {
			const name = propertyName(property.name);
			return name
				? `readonly ${JSON.stringify(name)}: ${typeForExpression(property.initializer, inputTypes)};`
				: "";
		})
		.filter(Boolean);

	return properties.length > 0 ? `{\n${properties.map((item) => `\t${item}`).join("\n")}\n}` : "{}";
}

/**
 * Merges two type representations into a combined type.
 *
 * @param left - The first type representation.
 * @param right - The second type representation.
 * @returns The shared object type when both inputs are object types, otherwise a union or the matching type.
 */
function mergeTypes(left: string, right: string): string {
	const leftObject = parseObjectType(left);
	const rightObject = parseObjectType(right);

	if (!leftObject || !rightObject) {
		return left === right ? left : `${left} | ${right}`;
	}

	const keys = Array.from(
		new Set([...Object.keys(leftObject), ...Object.keys(rightObject)]),
	).sort();
	const lines = keys.map((key) => {
		const leftValue = leftObject[key];
		const rightValue = rightObject[key];
		const optional = leftValue && rightValue ? "" : "?";
		const value =
			leftValue && rightValue ? mergeTypes(leftValue, rightValue) : (leftValue ?? rightValue);
		return `\treadonly ${JSON.stringify(key)}${optional}: ${value};`;
	});

	return `{\n${lines.join("\n")}\n}`;
}

/**
 * Parses a readonly object type string into a key-to-type map.
 *
 * @param type - The type string to parse
 * @returns An object map of property names to their declared types, or `undefined` if the string is not an object type
 */
function parseObjectType(type: string): Record<string, string> | undefined {
	const trimmed = type.trim();

	if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) {
		return;
	}

	const result: Record<string, string> = {};
	for (const match of trimmed.matchAll(/readonly "([^"]+)"\??: ([^;]+);/g)) {
		result[match[1]] = match[2];
	}

	return result;
}

/**
 * Removes `undefined` from a union type string and merges it with a fallback type.
 *
 * @param left - The type string to narrow
 * @param fallback - The type string to preserve in the result
 * @returns The narrowed type string, or a merged type when the fallback adds information
 */
function removeUndefined(left: string, fallback: string): string {
	const narrowed = left
		.split("|")
		.map((item) => item.trim())
		.filter((item) => item !== "undefined")
		.join(" | ");

	return narrowed === fallback ? narrowed : mergeTypes(narrowed || "unknown", fallback);
}

/**
 * Looks up the inferred type for an input access expression.
 *
 * @param expression - The expression to inspect
 * @param inputTypes - The map of input access paths to inferred types
 * @returns The inferred type for the access path, or `undefined` if no type is known
 */
function inputAccessType(
	expression: ts.Expression,
	inputTypes: Map<string, string>,
): string | undefined {
	const path = inputAccessPath(expression);
	return path ? inputTypes.get(path) : undefined;
}

/**
 * Resolves an `input.<location>.<field>` access path.
 *
 * @param expression - The expression to inspect
 * @returns The access path as `<location>.<field>` when the expression matches, `undefined` otherwise
 */
function inputAccessPath(expression: ts.Expression): string | undefined {
	const segments: string[] = [];
	let current = unwrapExpression(expression);

	while (ts.isPropertyAccessExpression(current) || ts.isElementAccessExpression(current)) {
		if (ts.isPropertyAccessExpression(current)) {
			segments.unshift(current.name.text);
			current = unwrapExpression(current.expression);
			continue;
		}

		const argument = unwrapExpression(current.argumentExpression);
		if (!ts.isStringLiteralLike(argument)) {
			return;
		}

		segments.unshift(argument.text);
		current = unwrapExpression(current.expression);
	}

	if (!ts.isIdentifier(current) || current.text !== "input" || segments.length !== 2) {
		return;
	}

	return `${segments[0]}.${segments[1]}`;
}

/**
 * Parses a TypeScript source file.
 *
 * @param file - The file path to read and parse.
 * @returns The parsed TypeScript source file.
 */
function parseTypeScriptFile(file: string): ts.SourceFile {
	return ts.createSourceFile(
		file,
		readFileSync(file, "utf8"),
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS,
	);
}

/**
 * Extracts the exported route configuration object from a source file.
 *
 * Follows `export default identifier` to a local initializer when possible.
 *
 * @param sourceFile - The parsed TypeScript source file to inspect
 * @returns The exported route configuration object, if present
 */
function routeConfigObject(sourceFile: ts.SourceFile): ts.ObjectLiteralExpression | undefined {
	for (const statement of sourceFile.statements) {
		if (!ts.isExportAssignment(statement) || statement.isExportEquals) {
			continue;
		}

		const expression = resolveExportedExpression(sourceFile, statement.expression);
		return defineRouteObject(expression) ?? objectLiteral(expression);
	}
}

/**
 * Resolves an exported expression to a local initializer when it is an identifier.
 */
function resolveExportedExpression(
	sourceFile: ts.SourceFile,
	expression: ts.Expression,
): ts.Expression {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isIdentifier(unwrapped)) {
		return unwrapped;
	}

	const initializer = localInitializer(sourceFile, unwrapped.text);
	return initializer ? unwrapExpression(initializer) : unwrapped;
}

/**
 * Finds the initializer for a local `const`/`let`/`var` binding in a source file.
 */
function localInitializer(sourceFile: ts.SourceFile, name: string): ts.Expression | undefined {
	for (const statement of sourceFile.statements) {
		if (!ts.isVariableStatement(statement)) {
			continue;
		}

		for (const declaration of statement.declarationList.declarations) {
			if (
				ts.isIdentifier(declaration.name)
				&& declaration.name.text === name
				&& declaration.initializer
			) {
				return declaration.initializer;
			}
		}
	}
}

/**
 * Extracts the route definition object from a `defineRoute(...)` call.
 *
 * @returns The first argument as an object literal, if the expression is a `defineRoute` call.
 */
function defineRouteObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

/**
 * Extracts the route contract object from a `createRoute` call.
 *
 * @param expression - The expression to inspect
 * @returns The first argument object literal when the expression is a `createRoute(...)` call; otherwise `undefined`
 */
function createRouteObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "createRoute") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

/**
 * Collects middleware declarations from a source file.
 *
 * @param sourceFile - The TypeScript source file to inspect.
 * @param exportedOnly - Whether to include only exported variable declarations.
 * @returns The discovered middleware names and their `createMiddleware(...)` contract objects.
 */
function middlewareDeclarations(
	sourceFile: ts.SourceFile,
	exportedOnly: boolean,
): Array<{ name: string; contract: ts.ObjectLiteralExpression }> {
	const declarations: Array<{ name: string; contract: ts.ObjectLiteralExpression }> = [];

	for (const statement of sourceFile.statements) {
		if (!ts.isVariableStatement(statement)) {
			continue;
		}

		if (exportedOnly && !hasExportModifier(statement)) {
			continue;
		}

		for (const declaration of statement.declarationList.declarations) {
			if (!ts.isIdentifier(declaration.name) || !declaration.initializer) {
				continue;
			}

			const contract = createMiddlewareObject(declaration.initializer);

			if (!contract) {
				continue;
			}

			declarations.push({ name: declaration.name.text, contract });
		}
	}

	return declarations;
}

/**
 * Determines whether a variable statement is exported.
 *
 * @returns `true` if the statement has an `export` modifier, `false` otherwise.
 */
function hasExportModifier(statement: ts.VariableStatement): boolean {
	return (
		statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
	);
}

/**
 * Extracts the middleware contract object from a `createMiddleware` call.
 *
 * @param expression - The expression to inspect
 * @returns The first argument object literal when the expression is a `createMiddleware(...)` call, otherwise `undefined`
 */
function createMiddlewareObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "createMiddleware") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

/**
 * Resolves a middleware expression to its declaration contract.
 *
 * @param expression - The middleware expression to inspect.
 * @param middlewareByName - A lookup of locally declared middleware contracts by name.
 * @returns The middleware name and contract object when the expression resolves, or `undefined` otherwise.
 */
function middlewareExpressionMetadata(
	expression: ts.Expression,
	middlewareByName: Map<string, ts.ObjectLiteralExpression>,
): { name: string; contract: ts.ObjectLiteralExpression } | undefined {
	const unwrapped = unwrapExpression(expression);

	if (ts.isIdentifier(unwrapped)) {
		const contract = middlewareByName.get(unwrapped.text);

		if (contract) {
			return { name: unwrapped.text, contract };
		}
	}

	const inline = createMiddlewareObject(unwrapped);

	if (inline) {
		return { name: "createMiddleware", contract: inline };
	}
}

/**
 * Extracts middleware expressions from an expression or middleware array literal.
 *
 * Spread elements are reported as unresolved because their contents run at
 * runtime but cannot be statically analyzed.
 *
 * @param expression - The expression to inspect
 * @returns The resolvable expressions and descriptions of unresolved entries
 */
function middlewareExpressions(expression: ts.Expression): {
	resolved: ts.Expression[];
	unresolved: string[];
} {
	const unwrapped = unwrapExpression(expression);

	if (ts.isArrayLiteralExpression(unwrapped)) {
		const resolved: ts.Expression[] = [];
		const unresolved: string[] = [];

		for (const element of unwrapped.elements) {
			if (ts.isSpreadElement(element)) {
				unresolved.push(element.getText());
			} else {
				resolved.push(element as ts.Expression);
			}
		}

		return { resolved, unresolved };
	}

	return { resolved: [unwrapped], unresolved: [] };
}

/**
 * Extracts the declared input locations from a route contract.
 *
 * @param routeContract - The route contract object literal to inspect.
 * @returns An object indicating whether `params`, `query`, `headers`, `cookies`, and `body` inputs are declared.
 */
function routeInputs(routeContract: ts.ObjectLiteralExpression): RouteMethodInputMetadata {
	const input = objectProperty(routeContract, "input");
	const inputObject = input ? objectLiteral(input.initializer) : undefined;

	return {
		params: Boolean(inputObject && objectProperty(inputObject, "params")),
		query: Boolean(inputObject && objectProperty(inputObject, "query")),
		headers: Boolean(inputObject && objectProperty(inputObject, "headers")),
		cookies: Boolean(inputObject && objectProperty(inputObject, "cookies")),
		body: Boolean(inputObject && objectProperty(inputObject, "body")),
	};
}

/**
 * Collects declared response status codes from a route contract.
 *
 * @param routeContract - The route contract object literal
 * @returns The numeric status codes declared under `responses`
 */
function responseStatuses(routeContract: ts.ObjectLiteralExpression): number[] {
	const responses = objectProperty(routeContract, "responses");

	if (!responses) {
		return [];
	}

	const statuses: number[] = [];
	const visit = (node: ts.Node) => {
		if (ts.isPropertyAssignment(node) && propertyName(node.name) === "status") {
			const status = numericValue(node.initializer);

			if (status !== undefined) {
				statuses.push(status);
			}
		}

		ts.forEachChild(node, visit);
	};
	visit(responses.initializer);

	return statuses;
}

/**
 * Extracts a numeric literal value from an expression.
 *
 * @param expression - The expression to inspect
 * @returns The numeric value, or `undefined` when the expression is not a numeric literal
 */
function numericValue(expression: ts.Expression): number | undefined {
	const unwrapped = unwrapExpression(expression);

	if (ts.isNumericLiteral(unwrapped)) {
		return Number(unwrapped.text);
	}
}

/**
 * Finds a property assignment with the given name in an object literal.
 *
 * @param object - The object literal to search.
 * @param name - The property name to match.
 * @returns The matching property assignment, or `undefined` if none is found.
 */
function objectProperty(
	object: ts.ObjectLiteralExpression,
	name: string,
): ts.PropertyAssignment | undefined {
	return objectProperties(object).find((property) => propertyName(property.name) === name);
}

/**
 * Gets the property assignments declared in an object literal.
 *
 * @param object - The object literal to inspect
 * @returns The property assignments contained in `object`
 */
function objectProperties(object: ts.ObjectLiteralExpression): ts.PropertyAssignment[] {
	return object.properties.filter(ts.isPropertyAssignment);
}

/**
 * Gets an object literal expression from a node.
 *
 * @param node - The node to inspect
 * @returns The object literal expression if the node resolves to one, `undefined` otherwise
 */
function objectLiteral(node: ts.Node | undefined): ts.ObjectLiteralExpression | undefined {
	if (!node || !ts.isExpression(node)) {
		return;
	}

	const unwrapped = unwrapExpression(node);
	return ts.isObjectLiteralExpression(unwrapped) ? unwrapped : undefined;
}

/**
 * Gets the name of a called function or property access.
 *
 * @returns The identifier or property name used by the expression, or `undefined` when it cannot be determined.
 */
function callName(expression: ts.Expression): string | undefined {
	const callee = ts.isCallExpression(expression)
		? unwrapExpression(expression.expression)
		: unwrapExpression(expression);

	if (ts.isIdentifier(callee)) {
		return callee.text;
	}

	if (ts.isPropertyAccessExpression(callee)) {
		return callee.name.text;
	}
}

/**
 * Gets the text name of a property declaration.
 *
 * @param name - The property name node
 * @returns The property name text, or `undefined` for computed names
 */
function propertyName(name: ts.PropertyName): string | undefined {
	if (ts.isIdentifier(name) || ts.isStringLiteralLike(name) || ts.isNumericLiteral(name)) {
		return name.text;
	}
}

/**
 * Removes common TypeScript wrapper expressions from an expression.
 *
 * @param expression - The expression to unwrap.
 * @returns The innermost expression after removing wrappers.
 */
function unwrapExpression(expression: ts.Expression): ts.Expression {
	let current = expression;

	while (
		ts.isParenthesizedExpression(current)
		|| ts.isAsExpression(current)
		|| ts.isSatisfiesExpression(current)
		|| ts.isTypeAssertionExpression(current)
		|| ts.isNonNullExpression(current)
	) {
		current = current.expression;
	}

	return current;
}

/**
 * Validates middleware ordering for each route.
 *
 * @returns Diagnostics for middleware that requires context before it has been provided.
 */
function middlewareOrderDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const chains =
			route.methods.length > 0
				? route.methods.map(
						(item) => route.methodMiddleware[item.toLowerCase()] ?? route.middleware,
					)
				: [route.middleware];

		for (const chain of chains) {
			const provided = new Set<string>();

			for (const middleware of chain) {
				for (const required of middleware.requires) {
					if (!provided.has(required)) {
						diagnostics.push({
							code: "ROUTA_MIDDLEWARE_ORDER",
							severity: "error",
							message: `${middleware.name} requires ctx.${required} before it is provided.`,
							file: middleware.file,
							routePath: route.path,
							suggestion: `Move middleware that provides ${required} before ${middleware.name}.`,
						});
					}
				}

				for (const providedField of middleware.provides) {
					provided.add(providedField);
				}
			}
		}
	}

	return diagnostics;
}

function middlewareRejectStatusDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		for (const middleware of [
			...route.middleware,
			...Object.values(route.methodMiddleware).flat(),
		]) {
			for (const reject of middleware.rejects) {
				if (reject.status >= 400 && reject.status <= 599) {
					continue;
				}

				diagnostics.push({
					code: "ROUTA_MIDDLEWARE_REJECT_STATUS",
					severity: "error",
					message: `${middleware.name} reject "${reject.type}" uses non-error status ${reject.status}.`,
					file: middleware.file,
					routePath: route.path,
					suggestion: "Middleware rejects must use a 4xx or 5xx HTTP status.",
				});
			}
		}
	}

	return diagnostics;
}

/**
 * Reports routes that share the same path.
 *
 * @param routes - The discovered route metadata to inspect.
 * @returns Diagnostics for each duplicate route path.
 */
function duplicateRouteDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const seen = new Map<string, RouteMetadata>();
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const previous = seen.get(route.path);

		if (previous) {
			diagnostics.push({
				code: "ROUTA_DUPLICATE_ROUTE",
				severity: "error",
				message: `Duplicate route path ${route.path}.`,
				file: route.file,
				routePath: route.path,
				suggestion: `Rename or move ${route.file}; it conflicts with ${previous.file}.`,
			});
			continue;
		}

		seen.set(route.path, route);
	}

	return diagnostics;
}

/**
 * Serializes route metadata into the `.routa/routes.gen.ts` module source.
 *
 * This is the single source of truth for the generated metadata shape; both
 * `routa check` and `routa scaffold` emit it so the runtime always loads the
 * same structure.
 *
 * @param routes - The route metadata to serialize.
 * @returns The generated TypeScript source.
 */
export function routesMetadataSource(routes: RouteMetadata[]): string {
	return `${generatedHeader}export const routaRoutes = ${JSON.stringify(routes, null, "\t")} as const;

${routeContextTypes(routes)}
`;
}

/**
 * Writes generated route metadata to `.routa/routes.gen.ts`.
 *
 * @param cwd - The project root directory.
 * @param routes - The discovered route metadata to serialize.
 */
function writeRoutesMetadata(cwd: string, routes: RouteMetadata[]): void {
	const file = join(cwd, ".routa/routes.gen.ts");
	const source = routesMetadataSource(routes);

	if (existsSync(file) && readFileSync(file, "utf8") === source) {
		return;
	}

	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(file, source);
}

/**
 * Builds TypeScript declarations for route context types and module registration.
 *
 * @returns Generated source text for per-route context types, route-to-method context maps, and the `@routa-ts/core` module augmentation.
 */
function routeContextTypes(routes: RouteMetadata[]): string {
	const ctxTypes = routes
		.map((route) => {
			const typeName = routeCtxTypeName(route);
			const ctx =
				route.ctx.length > 0
					? route.ctx.map((key) => `\t${JSON.stringify(key)}: unknown;`).join("\n")
					: "\treadonly __empty?: never;";

			return `export type ${typeName} = {\n${ctx}\n};`;
		})
		.join("\n\n");

	const ctxMap = `export type RoutaRouteCtxByPath = {\n${routes
		.map((route) => `\t${JSON.stringify(route.path)}: ${routeMethodCtxMap(route)};`)
		.join("\n")}\n};`;
	const ctxByKey = `export type RoutaCtxByKey = ${ctxByKeyType(routes)};`;

	return `${ctxTypes}\n\n${ctxMap}\n\n${ctxByKey}\n\ndeclare module "@routa-ts/core" {\n\texport interface Register {\n\t\trouteCtxByPath: RoutaRouteCtxByPath;\n\t\tctxByKey: RoutaCtxByKey;\n\t}\n}`;
}

/**
 * Builds the aggregate context type contributed by all middleware across the project.
 *
 * @param routes - Route metadata used to collect provided context keys and their inferred types
 * @returns A TypeScript object type string for the combined context map, or `{ readonly __empty?: never }` when no context is provided
 */
function ctxByKeyType(routes: RouteMetadata[]): string {
	const ctx = new Map<string, string>();

	for (const route of routes) {
		const chains = [route.middleware, ...Object.values(route.methodMiddleware)];

		for (const chain of chains) {
			for (const middleware of chain) {
				for (const key of middleware.provides) {
					ctx.set(key, middleware.providesTypes[key] ?? "unknown");
				}
			}
		}
	}

	if (ctx.size === 0) {
		return "{ readonly __empty?: never }";
	}

	return `{\n${Array.from(ctx.entries())
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([key, type]) => `\t${JSON.stringify(key)}: ${indentType(type, 1)};`)
		.join("\n")}\n}`;
}

/**
 * Builds the route context map for all HTTP methods.
 *
 * @param route - The route metadata to describe.
 * @returns A TypeScript object type mapping each HTTP method to its context type.
 */
function routeMethodCtxMap(route: RouteMetadata): string {
	const methods: string[] = [];

	for (const method of ["get", "post", "put", "patch", "delete", "head", "options"]) {
		methods.push(`\t\t${method}: ${routeCtxTypeNameForMiddleware(route, method)};`);
	}

	return `{\n${methods.join("\n")}\n\t}`;
}

/**
 * Builds the context type for a route method's middleware chain.
 *
 * @param route - The route metadata to inspect
 * @param method - The HTTP method whose middleware chain is used when present
 * @returns A TypeScript object type for the middleware-provided context keys
 */
function routeCtxTypeNameForMiddleware(route: RouteMetadata, method: string): string {
	const chain = route.methodMiddleware[method] ?? route.middleware;
	const ctx = new Map<string, string>();

	for (const middleware of chain) {
		for (const key of middleware.provides) {
			ctx.set(key, middleware.providesTypes[key] ?? "unknown");
		}
	}

	if (ctx.size === 0) {
		return "{ readonly __empty?: never }";
	}

	return `{\n${Array.from(ctx.entries())
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([key, type]) => `\t\t\t${JSON.stringify(key)}: ${indentType(type, 3)};`)
		.join("\n")}\n\t\t}`;
}

/**
 * Indents each line of a type string.
 *
 * @param type - The type text to indent
 * @param tabs - The number of tab characters to prepend to each line after the first
 * @returns The type text with newline-separated lines indented
 */
function indentType(type: string, tabs: number): string {
	const indentation = "\t".repeat(tabs);
	return type.replaceAll("\n", `\n${indentation}`);
}

/**
 * Builds the generated context type name for a route path.
 *
 * @param route - The route metadata used to derive the name
 * @returns The route context type name
 */
function routeCtxTypeName(route: RouteMetadata): string {
	const suffix = route.path === "/" ? "Root" : pascalCase(route.path);
	return `${suffix}Ctx`;
}

/**
 * Converts a string to PascalCase.
 *
 * @param value - The input string
 * @returns The PascalCase form of `value`, or `"Route"` when no alphanumeric characters are present
 */
function pascalCase(value: string): string {
	const text = value.replaceAll(/[^a-zA-Z0-9]+/g, " ").trim();

	if (!text) {
		return "Route";
	}

	return text
		.split(/\s+/)
		.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
		.join("");
}

/**
 * Runs the TypeScript compiler for a project.
 *
 * Prefers a local `node_modules/.bin/tsc` when present, then falls back to `pnpm exec tsc`.
 *
 * @param cwd - Project root directory
 * @param args - Arguments passed to `tsc`
 * @returns The compiler result, or `{ code: 0 }` when `tsconfig.json` is missing
 */
function runTypeScript(
	cwd: string,
	args: string[],
): { code: number; stdout?: string; stderr?: string } {
	if (!existsSync(join(cwd, "tsconfig.json"))) {
		return { code: 0 };
	}

	const localTsc = join(cwd, "node_modules", ".bin", "tsc");
	const result = existsSync(localTsc)
		? spawnSync(localTsc, args, {
				cwd,
				encoding: "utf8",
				shell: process.platform === "win32",
			})
		: spawnSync("pnpm", ["exec", "tsc", ...args], {
				cwd,
				encoding: "utf8",
			});

	return {
		code: result.status ?? 1,
		stdout: result.stdout,
		stderr: result.stderr || result.error?.message,
	};
}

/**
 * Appends captured output to a list of lines.
 *
 * @param lines - The lines to join.
 * @param output - Additional output to append after the joined lines.
 * @returns The combined text with a trailing newline.
 */
function appendOutput(lines: string[], output?: string): string {
	const base = `${lines.join("\n")}\n`;

	if (!output) {
		return base;
	}

	return `${base}${output.endsWith("\n") ? output : `${output}\n`}`;
}

/**
 * Formats diagnostics into a newline-separated report.
 *
 * @param diagnostics - Diagnostics to format
 * @returns The formatted diagnostic report
 */
function formatDiagnostics(diagnostics: Diagnostic[]): string {
	return diagnostics
		.map((diagnostic) => {
			const location = diagnostic.file ? `${diagnostic.file}: ` : "";
			const suggestion = diagnostic.suggestion ? `\nSuggestion: ${diagnostic.suggestion}` : "";
			return `${diagnostic.code}: ${location}${diagnostic.message}${suggestion}`;
		})
		.join("\n");
}

/**
 * Recursively lists all files under a directory.
 *
 * Symlink cycles are skipped by tracking visited real paths.
 *
 * @param dir - The directory to traverse
 * @param visited - Real paths already visited during this walk
 * @returns The full paths of all files found under `dir`
 */
function walk(dir: string, visited = new Set<string>()): string[] {
	let realDir: string;

	try {
		realDir = realpathSync(dir);
	} catch {
		return [];
	}

	if (visited.has(realDir)) {
		return [];
	}

	visited.add(realDir);

	return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
		const file = join(dir, entry.name);

		if (entry.isSymbolicLink()) {
			let stats: ReturnType<typeof statSync>;

			try {
				stats = statSync(file);
			} catch {
				return [];
			}

			return stats.isDirectory() ? walk(file, visited) : [file];
		}

		return entry.isDirectory() ? walk(file, visited) : [file];
	});
}
