import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

export type Diagnostic = {
	code: string;
	severity: "error";
	message: string;
	file?: string;
	routePath?: string;
	suggestion?: string;
};

export type RouteMetadata = {
	file: string;
	path: string;
	methods: string[];
	responses: Record<string, number[]>;
	inputs: Record<string, RouteMethodInputMetadata>;
	middleware: MiddlewareMetadata[];
	ctx: string[];
	groups: string[];
	segments: string[];
};

export type RouteMethodInputMetadata = {
	params: boolean;
	query: boolean;
	body: boolean;
};

export type MiddlewareMetadata = {
	file: string;
	name: string;
	requires: string[];
	provides: string[];
	rejects: string[];
};

export type ProjectValidationResult = {
	routes: RouteMetadata[];
	diagnostics: Diagnostic[];
};

const generatedHeader =
	"// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: routes directory\n\n";

export function validateProject(cwd = process.cwd()): ProjectValidationResult {
	const routes = discoverRoutes(cwd);
	const diagnostics = [
		...duplicateRouteDiagnostics(routes),
		...missingSuccessResponseDiagnostics(routes),
		...duplicateSchemaDiagnostics(cwd),
		...middlewareOrderDiagnostics(routes),
	];

	if (diagnostics.length === 0) {
		writeRoutesMetadata(cwd, routes);
	}

	return { routes, diagnostics };
}

export function runProjectCheck(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const typecheck = runTypeScript(cwd, ["-p", "tsconfig.json", "--noEmit"]);

	if (typecheck.code !== 0) {
		return typecheck;
	}

	return { code: 0, stdout: `Routa check passed for ${validation.routes.length} route file(s).\n` };
}

export function runProjectBuild(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const build = runTypeScript(cwd, ["-p", "tsconfig.json"]);

	if (build.code !== 0) {
		return build;
	}

	return { code: 0, stdout: `Routa build passed for ${validation.routes.length} route file(s).\n` };
}

function discoverRoutes(cwd: string): RouteMetadata[] {
	const routesDir = join(cwd, "routes");

	if (!existsSync(routesDir)) {
		return [];
	}

	const files = walk(routesDir).filter((file) => file.endsWith(`${sep}route.ts`));

	return files.map((file) => {
		const relativeFile = relative(cwd, file);
		const rawSegments = dirname(relativeFile).split(sep).slice(1);
		const groups = rawSegments.filter(
			(segment) => segment.startsWith("(") && segment.endsWith(")"),
		);
		const segments = rawSegments.filter(
			(segment) => !(segment.startsWith("(") && segment.endsWith(")")),
		);
		const pathSegments = segments.map((segment) =>
			segment.startsWith("$") ? `:${segment.slice(1)}` : segment,
		);
		const middleware = middlewareChain(cwd, rawSegments, relativeFile);
		const contract = parseRouteContract(file);
		const ctx = Array.from(new Set(middleware.flatMap((item) => item.provides))).sort();

		return {
			file: relativeFile,
			path: `/${pathSegments.join("/")}`.replace(/\/$/, "") || "/",
			methods: Object.keys(contract).map((method) => method.toUpperCase()),
			responses: Object.fromEntries(
				Object.entries(contract).map(([method, metadata]) => [method, metadata.responses]),
			),
			inputs: Object.fromEntries(
				Object.entries(contract).map(([method, metadata]) => [method, metadata.inputs]),
			),
			middleware,
			ctx,
			groups,
			segments,
		};
	});
}

function parseRouteContract(
	file: string,
): Record<string, { responses: number[]; inputs: RouteMethodInputMetadata }> {
	const source = readFileSync(file, "utf8");
	const contract: Record<string, { responses: number[]; inputs: RouteMethodInputMetadata }> = {};
	const methodPattern = /^\s*(get|post|put|patch|delete|head|options):\s*createRoute\(\{/gm;
	const matches = Array.from(source.matchAll(methodPattern));

	for (const [index, match] of matches.entries()) {
		const method = match[1];
		const start = match.index ?? 0;
		const end = matches[index + 1]?.index ?? source.length;
		const block = source.slice(start, end);
		const statuses = Array.from(block.matchAll(/status:\s*(\d+)/g)).map((statusMatch) =>
			Number(statusMatch[1]),
		);
		contract[method] = {
			responses: statuses,
			inputs: {
				params: /\bparams\s*:/.test(block),
				query: /\bquery\s*:/.test(block),
				body: /\bbody\s*:/.test(block),
			},
		};
	}

	return contract;
}

function missingSuccessResponseDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		for (const [method, statuses] of Object.entries(route.responses)) {
			if (method === "delete") {
				continue;
			}

			if (!statuses.some((status) => status >= 200 && status < 300)) {
				diagnostics.push({
					code: "ROUTA_MISSING_SUCCESS_RESPONSE",
					severity: "error",
					message: `${method.toUpperCase()} ${route.path} is missing a 2xx success response.`,
					file: route.file,
					routePath: route.path,
					suggestion: "Add a declared success response with a 2xx HTTP status.",
				});
			}
		}
	}

	return diagnostics;
}

function duplicateSchemaDiagnostics(cwd: string): Diagnostic[] {
	const routesDir = join(cwd, "routes");

	if (!existsSync(routesDir)) {
		return [];
	}

	const diagnostics: Diagnostic[] = [];

	for (const file of walk(routesDir).filter((item) => item.endsWith(`${sep}schemas.ts`))) {
		const relativeFile = relative(cwd, file);
		const source = readFileSync(file, "utf8");
		const seen = new Set<string>();

		for (const match of source.matchAll(/export\s+const\s+([A-Za-z_$][\w$]*)/g)) {
			const name = match[1];

			if (seen.has(name)) {
				diagnostics.push({
					code: "ROUTA_DUPLICATE_SCHEMA_NAME",
					severity: "error",
					message: `Duplicate schema export ${name}.`,
					file: relativeFile,
					suggestion: "Use a stable contract-purpose name such as CreateUserResponse.",
				});
				continue;
			}

			seen.add(name);
		}
	}

	return diagnostics;
}

function middlewareChain(
	cwd: string,
	rawSegments: string[],
	routeFile: string,
): MiddlewareMetadata[] {
	const candidates = ["routes/middleware.ts"];
	let current = "routes";

	for (const segment of rawSegments) {
		current = join(current, segment);
		candidates.push(join(current, "middleware.ts"));
	}

	return candidates
		.filter((file) => existsSync(join(cwd, file)))
		.flatMap((file) => parseMiddlewareFile(cwd, file))
		.concat(parseRouteFileMiddleware(cwd, routeFile));
}

function parseMiddlewareFile(cwd: string, file: string): MiddlewareMetadata[] {
	const source = readFileSync(join(cwd, file), "utf8");

	return middlewareBlocks(source, true).map((block) => ({
		file,
		name: block.name,
		requires: stringArrayProperty(block.body, "requires"),
		provides: stringArrayProperty(block.body, "provides"),
		rejects: stringArrayProperty(block.body, "rejects"),
	}));
}

function parseRouteFileMiddleware(cwd: string, routeFile: string): MiddlewareMetadata[] {
	const source = readFileSync(join(cwd, routeFile), "utf8");
	const entries = [
		...Array.from(source.matchAll(/middleware:\s*\[([\s\S]*?)\]/g)).flatMap((match) =>
			identifiersInList(match[1]),
		),
		...Array.from(source.matchAll(/middleware:\s*([A-Za-z_$][\w$]*)/g)).map((match) => match[1]),
	];

	return entries.map((name) => ({
		file: routeFile,
		name,
		requires: middlewareObjectProperty(source, name, "requires"),
		provides: middlewareObjectProperty(source, name, "provides"),
		rejects: middlewareObjectProperty(source, name, "rejects"),
	}));
}

function middlewareObjectProperty(source: string, name: string, property: string): string[] {
	const block = middlewareBlocks(source, false).find((item) => item.name === name);

	return block ? stringArrayProperty(block.body, property) : [];
}

function stringArrayProperty(source: string, property: string): string[] {
	const pattern = new RegExp(`${property}:\\s*\\[([\\s\\S]*?)\\]`, "m");
	const match = source.match(pattern);

	if (!match) {
		return [];
	}

	return Array.from(match[1].matchAll(/["']([^"']+)["']/g)).map((item) => item[1]);
}

function identifiersInList(source: string): string[] {
	return Array.from(source.matchAll(/\b([A-Za-z_$][\w$]*)\b/g))
		.map((match) => match[1])
		.filter((name) => name !== "middleware");
}

function middlewareOrderDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const provided = new Set<string>();

		for (const middleware of route.middleware) {
			for (const required of middleware.requires) {
				if (!provided.has(required)) {
					diagnostics.push({
						code: "ROUTA_MIDDLEWARE_ORDER",
						severity: "error",
						message: `${middleware.name} requires ctx.${required} before it is provided.`,
						file: middleware.file,
						routePath: route.path,
						suggestion: `Move middleware that provides ${required} before ${middleware.name}.`,
					});
				}
			}

			for (const providedField of middleware.provides) {
				provided.add(providedField);
			}
		}
	}

	return diagnostics;
}

function middlewareBlocks(
	source: string,
	exportedOnly: boolean,
): Array<{ name: string; body: string }> {
	const pattern = exportedOnly
		? /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*createMiddleware\(\{/g
		: /(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*=\s*createMiddleware\(\{/g;
	const blocks: Array<{ name: string; body: string }> = [];

	for (const match of source.matchAll(pattern)) {
		const bodyStart = (match.index ?? 0) + match[0].length;
		const bodyEnd = matchingBraceEnd(source, bodyStart - 1);

		if (bodyEnd === -1) {
			continue;
		}

		blocks.push({
			name: match[1],
			body: source.slice(bodyStart, bodyEnd),
		});
	}

	return blocks;
}

function matchingBraceEnd(source: string, openBraceIndex: number): number {
	let depth = 0;
	let quote: string | undefined;

	for (let index = openBraceIndex; index < source.length; index += 1) {
		const char = source[index];
		const previous = source[index - 1];

		if (quote) {
			if (char === quote && previous !== "\\") {
				quote = undefined;
			}

			continue;
		}

		if (char === '"' || char === "'" || char === "`") {
			quote = char;
			continue;
		}

		if (char === "{") {
			depth += 1;
			continue;
		}

		if (char === "}") {
			depth -= 1;

			if (depth === 0) {
				return index;
			}
		}
	}

	return -1;
}

function duplicateRouteDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const seen = new Map<string, RouteMetadata>();
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const previous = seen.get(route.path);

		if (previous) {
			diagnostics.push({
				code: "ROUTA_DUPLICATE_ROUTE",
				severity: "error",
				message: `Duplicate route path ${route.path}.`,
				file: route.file,
				routePath: route.path,
				suggestion: `Rename or move ${route.file}; it conflicts with ${previous.file}.`,
			});
			continue;
		}

		seen.set(route.path, route);
	}

	return diagnostics;
}

function writeRoutesMetadata(cwd: string, routes: RouteMetadata[]): void {
	const file = join(cwd, ".routa/routes.gen.ts");
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(
		file,
		`${generatedHeader}export const routaRoutes = ${JSON.stringify(routes, null, "\t")} as const;

${routeContextTypes(routes)}
`,
	);
}

function routeContextTypes(routes: RouteMetadata[]): string {
	return routes
		.map((route) => {
			const typeName = routeCtxTypeName(route);
			const ctx =
				route.ctx.length > 0
					? route.ctx.map((key) => `\t${JSON.stringify(key)}: unknown;`).join("\n")
					: "\treadonly __empty?: never;";

			return `export type ${typeName} = {\n${ctx}\n};`;
		})
		.join("\n\n");
}

function routeCtxTypeName(route: RouteMetadata): string {
	const suffix = route.path === "/" ? "Root" : pascalCase(route.path);
	return `${suffix}Ctx`;
}

function pascalCase(value: string): string {
	const text = value.replaceAll(/[^a-zA-Z0-9]+/g, " ").trim();

	if (!text) {
		return "Route";
	}

	return text
		.split(/\s+/)
		.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
		.join("");
}

function runTypeScript(
	cwd: string,
	args: string[],
): { code: number; stdout?: string; stderr?: string } {
	if (!existsSync(join(cwd, "tsconfig.json"))) {
		return { code: 0 };
	}

	const result = spawnSync("pnpm", ["exec", "tsc", ...args], {
		cwd,
		encoding: "utf8",
	});

	return {
		code: result.status ?? 1,
		stdout: result.stdout,
		stderr: result.stderr || result.error?.message,
	};
}

function formatDiagnostics(diagnostics: Diagnostic[]): string {
	return diagnostics
		.map((diagnostic) => {
			const location = diagnostic.file ? `${diagnostic.file}: ` : "";
			const suggestion = diagnostic.suggestion ? `\nSuggestion: ${diagnostic.suggestion}` : "";
			return `${diagnostic.code}: ${location}${diagnostic.message}${suggestion}`;
		})
		.join("\n");
}

function walk(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
		const file = join(dir, entry.name);
		return entry.isDirectory() ? walk(file) : [file];
	});
}
