import { type ChildProcess, spawn, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import * as ts from "typescript";

export type Diagnostic = {
	code: string;
	severity: "error";
	message: string;
	file?: string;
	routePath?: string;
	suggestion?: string;
};

export type RouteMetadata = {
	file: string;
	path: string;
	methods: string[];
	responses: Record<string, number[]>;
	inputs: Record<string, RouteMethodInputMetadata>;
	middleware: MiddlewareMetadata[];
	methodMiddleware: Record<string, MiddlewareMetadata[]>;
	ctx: string[];
	groups: string[];
	segments: string[];
};

export type RouteMethodInputMetadata = {
	params: boolean;
	query: boolean;
	body: boolean;
};

export type MiddlewareMetadata = {
	file: string;
	name: string;
	requires: string[];
	provides: string[];
	providesTypes: Record<string, string>;
	rejects: string[];
};

export type ProjectValidationResult = {
	routes: RouteMetadata[];
	diagnostics: Diagnostic[];
};

const generatedHeader =
	"// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: src/routes directory\n\n";

const routesRoot = join("src", "routes");
const devPollMs = 300;
const httpMethods = new Set(["get", "post", "put", "patch", "delete", "head", "options"]);
const routeStubSource = `import { createRoute, defineRoute } from "@routa/core";

export default defineRoute({
\tget: createRoute({
\t\tresponses: {},
\t\trun: () => {
\t\t\treturn { type: "success", data: null };
\t\t},
\t}),
});
`;

export function validateProject(cwd = process.cwd()): ProjectValidationResult {
	const routes = discoverRoutes(cwd);
	const diagnostics = [
		...projectStructureDiagnostics(cwd),
		...duplicateRouteDiagnostics(routes),
		...missingSuccessResponseDiagnostics(routes),
		...duplicateSchemaDiagnostics(cwd),
		...middlewareOrderDiagnostics(routes),
	];

	if (diagnostics.length === 0) {
		writeRoutesMetadata(cwd, routes);
	}

	return { routes, diagnostics };
}

export function runProjectCheck(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const stdout = [
		`Routa validation passed for ${validation.routes.length} route file(s).`,
		"Running TypeScript check: tsc -p tsconfig.json --noEmit",
	];
	const typecheck = runTypeScript(cwd, ["-p", "tsconfig.json", "--noEmit"]);

	if (typecheck.code !== 0) {
		return {
			code: typecheck.code,
			stdout: appendOutput(stdout, typecheck.stdout),
			stderr: appendOutput(["TypeScript check failed."], typecheck.stderr),
		};
	}

	return {
		code: 0,
		stdout: appendOutput([...stdout, "TypeScript check passed.", "Routa check passed."]),
	};
}

export function runProjectBuild(cwd = process.cwd()): {
	code: number;
	stdout?: string;
	stderr?: string;
} {
	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
		};
	}

	const build = runTypeScript(cwd, ["-p", "tsconfig.json"]);

	if (build.code !== 0) {
		return build;
	}

	return { code: 0, stdout: `Routa build passed for ${validation.routes.length} route file(s).\n` };
}

export function runProjectDev(
	argv: readonly string[] = [],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	return runProjectServer("dev", argv, cwd);
}

export function runProjectDevProcess(argv: readonly string[] = [], cwd = process.cwd()): void {
	const result = prepareProjectServer("dev", argv, cwd);

	if (result.code !== 0 || result.print) {
		writeCommandResult(result);
		process.exitCode = result.code;
		return;
	}

	runDevSupervisor(cwd, result.runtimeFile);
}

export function runProjectStart(
	argv: readonly string[] = [],
	cwd = process.cwd(),
): { code: number; stdout?: string; stderr?: string } {
	return runProjectServer("start", argv, cwd);
}

function runProjectServer(
	mode: "dev" | "start",
	argv: readonly string[],
	cwd: string,
): { code: number; stdout?: string; stderr?: string } {
	const result = prepareProjectServer(mode, argv, cwd);

	if (result.code !== 0 || result.print) {
		return result;
	}

	const server = spawnSync(process.execPath, runtimeArgs(result.runtimeFile, cwd), {
		cwd,
		encoding: "utf8",
		stdio: "inherit",
	});

	return { code: server.status ?? 1 };
}

type PreparedServer = {
	code: number;
	stdout?: string;
	stderr?: string;
	runtimeFile: string;
	print: boolean;
};

function prepareProjectServer(
	mode: "dev" | "start",
	argv: readonly string[],
	cwd: string,
): PreparedServer {
	if (mode === "dev") {
		stubEmptyRouteFiles(cwd);
	}

	const validation = validateProject(cwd);

	if (validation.diagnostics.length > 0) {
		return {
			code: 1,
			stderr: formatDiagnostics(validation.diagnostics),
			runtimeFile: "",
			print: false,
		};
	}

	const runtimeFile = join(dirname(fileURLToPath(import.meta.url)), "runtime.js");

	if (argv.includes("--print")) {
		return { code: 0, stdout: `${runtimeFile}\n`, runtimeFile, print: true };
	}

	const typecheck = runTypeScript(cwd, ["-p", "tsconfig.json", "--noEmit"]);

	if (typecheck.code !== 0) {
		return {
			...typecheck,
			runtimeFile,
			print: false,
		};
	}

	return { code: 0, runtimeFile, print: false };
}

function writeCommandResult(result: { stdout?: string; stderr?: string }): void {
	if (result.stdout) {
		process.stdout.write(result.stdout);
	}

	if (result.stderr) {
		process.stderr.write(result.stderr);
	}
}

function runtimeArgs(runtimeFile: string, cwd: string): string[] {
	return ["--import", "tsx", runtimeFile, cwd];
}

function runDevSupervisor(cwd: string, runtimeFile: string): void {
	let child = startRuntimeProcess(cwd, runtimeFile);
	let snapshot = sourceSnapshot(cwd);

	const restart = () => {
		const changed = sourceSnapshotChanged(snapshot, sourceSnapshot(cwd));

		if (!changed) {
			return;
		}

		for (const file of stubEmptyRouteFiles(cwd)) {
			process.stdout.write(`Stubbed ${file}\n`);
		}

		const validation = validateProject(cwd);

		if (validation.diagnostics.length > 0) {
			process.stderr.write(formatDiagnostics(validation.diagnostics));
			snapshot = sourceSnapshot(cwd);
			return;
		}

		process.stdout.write("Restarting Routa dev server...\n");
		child.kill();
		child = startRuntimeProcess(cwd, runtimeFile);
		snapshot = sourceSnapshot(cwd);
	};

	const timer = setInterval(restart, devPollMs);
	const stop = () => {
		clearInterval(timer);
		child.kill();
		process.exit(0);
	};

	process.once("SIGINT", stop);
	process.once("SIGTERM", stop);
}

function startRuntimeProcess(cwd: string, runtimeFile: string): ChildProcess {
	return spawn(process.execPath, runtimeArgs(runtimeFile, cwd), {
		cwd,
		stdio: "inherit",
	});
}

export type SourceSnapshot = Map<string, number>;

export function stubEmptyRouteFiles(cwd = process.cwd()): string[] {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return [];
	}

	const files = walk(routesDir).filter((file) => file.endsWith(`${sep}route.ts`));
	const written: string[] = [];

	for (const file of files) {
		const content = readFileSync(file, "utf8");

		if (content.trim() !== "") {
			continue;
		}

		writeFileSync(file, routeStubSource);
		written.push(relative(cwd, file));
	}

	return written;
}

export function sourceSnapshot(cwd = process.cwd()): SourceSnapshot {
	const files = [
		...walk(join(cwd, "src")).filter((file) => file.endsWith(".ts")),
		join(cwd, ".routa/routes.gen.ts"),
	].filter((file) => existsSync(file));
	const snapshot: SourceSnapshot = new Map();

	for (const file of files) {
		snapshot.set(relative(cwd, file), statSync(file).mtimeMs);
	}

	return snapshot;
}

export function sourceSnapshotChanged(previous: SourceSnapshot, next: SourceSnapshot): boolean {
	if (previous.size !== next.size) {
		return true;
	}

	for (const [file, mtime] of next) {
		if (previous.get(file) !== mtime) {
			return true;
		}
	}

	return false;
}

function discoverRoutes(cwd: string): RouteMetadata[] {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return [];
	}

	const files = walk(routesDir).filter((file) => file.endsWith(`${sep}route.ts`));

	return files.map((file) => {
		const relativeFile = relative(cwd, file);
		const relativeRouteDir = relative(routesDir, dirname(file));
		const rawSegments = relativeRouteDir === "" ? [] : relativeRouteDir.split(sep);
		const groups = rawSegments.filter(
			(segment) => segment.startsWith("(") && segment.endsWith(")"),
		);
		const segments = rawSegments.filter(
			(segment) => !(segment.startsWith("(") && segment.endsWith(")")),
		);
		const pathSegments = segments.map((segment) =>
			segment.startsWith("$") ? `:${segment.slice(1)}` : segment,
		);
		const inheritedMiddleware = middlewareChain(cwd, rawSegments);
		const routeFileMiddleware = parseRouteFileMiddleware(cwd, relativeFile);
		const middleware = [...inheritedMiddleware, ...routeFileMiddleware.route];
		const methodMiddleware = Object.fromEntries(
			Object.entries(routeFileMiddleware.methods).map(([method, items]) => [
				method,
				[...middleware, ...items],
			]),
		);
		const contract = parseRouteContract(file);
		const ctx = Array.from(
			new Set([
				...middleware.flatMap((item) => item.provides),
				...Object.values(methodMiddleware).flatMap((items) =>
					items.flatMap((item) => item.provides),
				),
			]),
		).sort();

		return {
			file: relativeFile,
			path: `/${pathSegments.join("/")}`.replace(/\/$/, "") || "/",
			methods: Object.keys(contract).map((method) => method.toUpperCase()),
			responses: Object.fromEntries(
				Object.entries(contract).map(([method, metadata]) => [method, metadata.responses]),
			),
			inputs: Object.fromEntries(
				Object.entries(contract).map(([method, metadata]) => [method, metadata.inputs]),
			),
			middleware,
			methodMiddleware,
			ctx,
			groups,
			segments,
		};
	});
}

function parseRouteContract(
	file: string,
): Record<string, { responses: number[]; inputs: RouteMethodInputMetadata }> {
	const contract: Record<string, { responses: number[]; inputs: RouteMethodInputMetadata }> = {};
	const routeConfig = routeConfigObject(parseTypeScriptFile(file));

	if (!routeConfig) {
		return contract;
	}

	for (const property of objectProperties(routeConfig)) {
		const method = propertyName(property.name);

		if (!method || !httpMethods.has(method)) {
			continue;
		}

		const routeContract = createRouteObject(property.initializer);

		if (!routeContract) {
			continue;
		}

		contract[method] = {
			responses: responseStatuses(routeContract),
			inputs: routeInputs(routeContract),
		};
	}

	return contract;
}

function missingSuccessResponseDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		for (const [method, statuses] of Object.entries(route.responses)) {
			if (method === "delete") {
				continue;
			}

			if (!statuses.some((status) => status >= 200 && status < 300)) {
				diagnostics.push({
					code: "ROUTA_MISSING_SUCCESS_RESPONSE",
					severity: "error",
					message: `${method.toUpperCase()} ${route.path} is missing a 2xx success response.`,
					file: route.file,
					routePath: route.path,
					suggestion: "Add a declared success response with a 2xx HTTP status.",
				});
			}
		}
	}

	return diagnostics;
}

function duplicateSchemaDiagnostics(cwd: string): Diagnostic[] {
	const routesDir = join(cwd, routesRoot);

	if (!existsSync(routesDir)) {
		return [];
	}

	const diagnostics: Diagnostic[] = [];

	for (const file of walk(routesDir).filter((item) => item.endsWith(`${sep}schemas.ts`))) {
		const relativeFile = relative(cwd, file);
		const source = readFileSync(file, "utf8");
		const seen = new Set<string>();

		for (const match of source.matchAll(/export\s+const\s+([A-Za-z_$][\w$]*)/g)) {
			const name = match[1];

			if (seen.has(name)) {
				diagnostics.push({
					code: "ROUTA_DUPLICATE_SCHEMA_NAME",
					severity: "error",
					message: `Duplicate schema export ${name}.`,
					file: relativeFile,
					suggestion: "Use a stable contract-purpose name such as CreateUserResponse.",
				});
				continue;
			}

			seen.add(name);
		}
	}

	return diagnostics;
}

function middlewareChain(cwd: string, rawSegments: string[]): MiddlewareMetadata[] {
	const candidates = [`${routesRoot}/middleware.ts`];
	let current = routesRoot;

	for (const segment of rawSegments) {
		current = join(current, segment);
		candidates.push(join(current, "middleware.ts"));
	}

	return candidates
		.filter((file) => existsSync(join(cwd, file)))
		.flatMap((file) => parseMiddlewareFile(cwd, file));
}

function projectStructureDiagnostics(cwd: string): Diagnostic[] {
	const required = [
		{ path: "package.json", message: "Missing package.json." },
		{ path: "tsconfig.json", message: "Missing tsconfig.json." },
		{ path: "src", message: "Missing src/ directory." },
		{ path: "src/routa.ts", message: "Missing src/routa.ts." },
	];

	return required
		.filter((item) => !existsSync(join(cwd, item.path)))
		.map((item) => ({
			code: "ROUTA_PROJECT_REQUIRED",
			severity: "error" as const,
			message: `${item.message} Routa commands must run inside a TypeScript Routa project.`,
			file: item.path,
			suggestion:
				"Create a project with pnpm create routa@latest, or run this command at the project root.",
		}));
}

function parseMiddlewareFile(cwd: string, file: string): MiddlewareMetadata[] {
	const sourceFile = parseTypeScriptFile(join(cwd, file));

	return exportedMiddlewareDeclarations(cwd, file, sourceFile).map((block) =>
		middlewareMetadata(block.file, block.name, block.contract),
	);
}

function exportedMiddlewareDeclarations(
	cwd: string,
	file: string,
	sourceFile: ts.SourceFile,
	seen = new Set<string>(),
): Array<{ file: string; name: string; contract: ts.ObjectLiteralExpression }> {
	if (seen.has(file)) {
		return [];
	}

	seen.add(file);

	const declarations: Array<{
		file: string;
		name: string;
		contract: ts.ObjectLiteralExpression;
	}> = [];
	const imports = namedImportMap(cwd, file, sourceFile);

	for (const statement of sourceFile.statements) {
		if (ts.isVariableStatement(statement) && hasExportModifier(statement)) {
			for (const declaration of statement.declarationList.declarations) {
				if (!ts.isIdentifier(declaration.name) || !declaration.initializer) {
					continue;
				}

				const contract = createMiddlewareObject(declaration.initializer);

				if (contract) {
					declarations.push({ file, name: declaration.name.text, contract });
				}
			}
			continue;
		}

		if (!ts.isExportDeclaration(statement) || !statement.exportClause) {
			continue;
		}

		if (!ts.isNamedExports(statement.exportClause)) {
			continue;
		}

		const targetFile =
			statement.moduleSpecifier && ts.isStringLiteral(statement.moduleSpecifier)
				? resolveImportFile(cwd, file, statement.moduleSpecifier.text)
				: undefined;

		for (const specifier of statement.exportClause.elements) {
			const exportedName = specifier.name.text;
			const importedName = specifier.propertyName?.text ?? specifier.name.text;
			const source = targetFile
				? { file: targetFile, name: importedName }
				: imports.get(importedName);

			if (!source) {
				continue;
			}

			const targetAst = parseTypeScriptFile(join(cwd, source.file));
			const targetDeclarations = exportedMiddlewareDeclarations(cwd, source.file, targetAst, seen);
			const declaration = targetDeclarations.find((item) => item.name === source.name);

			if (declaration) {
				declarations.push({
					...declaration,
					name: source.name,
				});
				continue;
			}

			const direct = middlewareDeclarations(targetAst, true).find(
				(item) => item.name === source.name,
			);

			if (direct) {
				declarations.push({ file: source.file, name: source.name, contract: direct.contract });
				continue;
			}

			const local = middlewareDeclarations(targetAst, false).find(
				(item) => item.name === source.name,
			);

			if (local && exportedName === source.name) {
				declarations.push({ file: source.file, name: source.name, contract: local.contract });
			}
		}
	}

	return declarations;
}

function namedImportMap(
	cwd: string,
	file: string,
	sourceFile: ts.SourceFile,
): Map<string, { file: string; name: string }> {
	const imports = new Map<string, { file: string; name: string }>();

	for (const statement of sourceFile.statements) {
		if (
			!ts.isImportDeclaration(statement)
			|| !ts.isStringLiteral(statement.moduleSpecifier)
			|| !statement.importClause?.namedBindings
			|| !ts.isNamedImports(statement.importClause.namedBindings)
		) {
			continue;
		}

		const sourceFile = resolveImportFile(cwd, file, statement.moduleSpecifier.text);

		if (!sourceFile) {
			continue;
		}

		for (const specifier of statement.importClause.namedBindings.elements) {
			imports.set(specifier.name.text, {
				file: sourceFile,
				name: specifier.propertyName?.text ?? specifier.name.text,
			});
		}
	}

	return imports;
}

function resolveImportFile(cwd: string, fromFile: string, specifier: string): string | undefined {
	if (!specifier.startsWith(".")) {
		return;
	}

	const base = join(dirname(fromFile), specifier);
	const candidates = [
		base,
		base.endsWith(".js") ? `${base.slice(0, -3)}.ts` : undefined,
		base.endsWith(".ts") ? base : `${base}.ts`,
		join(base, "index.ts"),
	].filter((item): item is string => Boolean(item));

	return candidates.find((candidate) => existsSync(join(cwd, candidate)));
}

function parseRouteFileMiddleware(
	cwd: string,
	routeFile: string,
): { route: MiddlewareMetadata[]; methods: Record<string, MiddlewareMetadata[]> } {
	const sourceFile = parseTypeScriptFile(join(cwd, routeFile));
	const routeConfig = routeConfigObject(sourceFile);

	if (!routeConfig) {
		return { route: [], methods: {} };
	}

	const middleware = middlewareDeclarations(sourceFile, false);
	const middlewareByName = new Map(middleware.map((item) => [item.name, item.contract]));
	const imports = namedImportMap(cwd, routeFile, sourceFile);
	const route: MiddlewareMetadata[] = [];
	const methods: Record<string, MiddlewareMetadata[]> = {};
	const metadataForMiddleware = (expression: ts.Expression): MiddlewareMetadata | undefined => {
		const metadata = middlewareExpressionMetadata(expression, middlewareByName);

		if (metadata) {
			return middlewareMetadata(routeFile, metadata.name, metadata.contract);
		}

		const unwrapped = unwrapExpression(expression);

		if (!ts.isIdentifier(unwrapped)) {
			return;
		}

		const source = imports.get(unwrapped.text);

		if (!source) {
			return;
		}

		const targetAst = parseTypeScriptFile(join(cwd, source.file));
		const declaration =
			exportedMiddlewareDeclarations(cwd, source.file, targetAst).find(
				(item) => item.name === source.name,
			) ?? middlewareDeclarations(targetAst, true).find((item) => item.name === source.name);

		if (!declaration) {
			return;
		}

		return middlewareMetadata(routeFile, unwrapped.text, declaration.contract);
	};

	for (const property of objectProperties(routeConfig)) {
		if (propertyName(property.name) === "middleware") {
			for (const expression of middlewareExpressions(property.initializer)) {
				const metadata = metadataForMiddleware(expression);

				if (metadata) {
					route.push(metadata);
				}
			}
		}
	}

	for (const property of objectProperties(routeConfig)) {
		const method = propertyName(property.name);

		if (!method || !httpMethods.has(method)) {
			continue;
		}

		const routeContract = createRouteObject(property.initializer);

		if (!routeContract) {
			continue;
		}

		const entries: MiddlewareMetadata[] = [];

		for (const routeProperty of objectProperties(routeContract)) {
			if (propertyName(routeProperty.name) !== "middleware") {
				continue;
			}

			for (const expression of middlewareExpressions(routeProperty.initializer)) {
				const metadata = metadataForMiddleware(expression);

				if (metadata) {
					entries.push(metadata);
				}
			}
		}

		methods[method] = entries;
	}

	return { route, methods };
}

function stringArrayProperty(source: ts.ObjectLiteralExpression, property: string): string[] {
	const item = objectProperty(source, property);

	if (!item || !ts.isArrayLiteralExpression(item.initializer)) {
		return [];
	}

	return item.initializer.elements.flatMap((element) => {
		const expression = unwrapExpression(element);
		return ts.isStringLiteralLike(expression) ? [expression.text] : [];
	});
}

function middlewareMetadata(
	file: string,
	name: string,
	contract: ts.ObjectLiteralExpression,
): MiddlewareMetadata {
	const provides = middlewareProvides(contract);
	const inferred = middlewareNextProvidesTypes(contract);

	return {
		file,
		name,
		requires: stringArrayProperty(contract, "requires"),
		provides: provides.keys,
		providesTypes: Object.fromEntries(
			provides.keys.map((provided) => [
				provided,
				provides.types[provided] ?? inferred[provided] ?? "unknown",
			]),
		),
		rejects: stringArrayProperty(contract, "rejects"),
	};
}

function middlewareProvides(contract: ts.ObjectLiteralExpression): {
	keys: string[];
	types: Record<string, string>;
} {
	const item = objectProperty(contract, "provides");

	if (!item) {
		return { keys: [], types: {} };
	}

	const expression = unwrapExpression(item.initializer);

	if (!ts.isObjectLiteralExpression(expression)) {
		return { keys: [], types: {} };
	}

	const entries = objectProperties(expression).flatMap((property) => {
		const name = propertyName(property.name);
		return name ? [[name, zodType(property.initializer)] as const] : [];
	});

	return {
		keys: entries.map(([key]) => key),
		types: Object.fromEntries(entries),
	};
}

function middlewareNextProvidesTypes(contract: ts.ObjectLiteralExpression): Record<string, string> {
	const nextCtx = middlewareNextContext(contract);

	if (!nextCtx) {
		return {};
	}

	const inputTypes = middlewareInputTypes(contract);
	const result: Record<string, string> = {};

	for (const property of objectProperties(nextCtx)) {
		const name = propertyName(property.name);

		if (name) {
			result[name] = typeForExpression(property.initializer, inputTypes);
		}
	}

	return result;
}

function middlewareNextContext(
	contract: ts.ObjectLiteralExpression,
): ts.ObjectLiteralExpression | undefined {
	const run = objectProperty(contract, "run");

	if (!run) {
		return;
	}

	let context: ts.ObjectLiteralExpression | undefined;

	const visit = (node: ts.Node): void => {
		if (context) {
			return;
		}

		if (
			ts.isCallExpression(node)
			&& callName(node) === "next"
			&& node.arguments.length > 0
			&& ts.isExpression(node.arguments[0])
		) {
			context = objectLiteral(node.arguments[0]);
			return;
		}

		ts.forEachChild(node, visit);
	};

	visit(run.initializer);
	return context;
}

function middlewareInputTypes(contract: ts.ObjectLiteralExpression): Map<string, string> {
	const input = objectProperty(contract, "input");
	const inputObject = input ? objectLiteral(input.initializer) : undefined;
	const result = new Map<string, string>();

	if (!inputObject) {
		return result;
	}

	for (const location of objectProperties(inputObject)) {
		const locationName = propertyName(location.name);
		const schema = zodObjectShape(location.initializer);

		if (!locationName || !schema) {
			continue;
		}

		for (const property of objectProperties(schema)) {
			const name = propertyName(property.name);

			if (!name) {
				continue;
			}

			result.set(`${locationName}.${name}`, zodType(property.initializer));
		}
	}

	return result;
}

function zodObjectShape(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "object") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

function zodType(expression: ts.Expression): string {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return "unknown";
	}

	const call = callName(unwrapped);
	const callee = unwrapExpression(unwrapped.expression);

	if (call === "optional" && ts.isPropertyAccessExpression(callee)) {
		return `${zodType(callee.expression)} | undefined`;
	}

	if (call === "object") {
		const shape = objectLiteral(unwrapped.arguments[0]);

		if (!shape) {
			return "Record<string, unknown>";
		}

		return zodObjectType(shape);
	}

	if (call === "array") {
		return `Array<${unwrapped.arguments[0] ? zodType(unwrapped.arguments[0]) : "unknown"}>`;
	}

	if (call === "enum" && ts.isArrayLiteralExpression(unwrapped.arguments[0])) {
		const values = unwrapped.arguments[0].elements.flatMap((element) => {
			const value = unwrapExpression(element);
			return ts.isStringLiteralLike(value) ? [JSON.stringify(value.text)] : [];
		});

		return values.length > 0 ? values.join(" | ") : "string";
	}

	if (call === "string") {
		return "string";
	}

	if (call === "number" || call === "int") {
		return "number";
	}

	if (call === "boolean") {
		return "boolean";
	}

	return "unknown";
}

function zodObjectType(shape: ts.ObjectLiteralExpression): string {
	const properties = objectProperties(shape).flatMap((property) => {
		const name = propertyName(property.name);

		if (!name) {
			return [];
		}

		const optional = isZodOptional(property.initializer);
		return [
			`\treadonly ${JSON.stringify(name)}${optional ? "?" : ""}: ${zodType(property.initializer)};`,
		];
	});

	return properties.length > 0 ? `{\n${properties.join("\n")}\n}` : "{}";
}

function isZodOptional(expression: ts.Expression): boolean {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return false;
	}

	return callName(unwrapped) === "optional";
}

function typeForExpression(expression: ts.Expression, inputTypes: Map<string, string>): string {
	const unwrapped = unwrapExpression(expression);

	if (ts.isStringLiteralLike(unwrapped) || ts.isTemplateExpression(unwrapped)) {
		return "string";
	}

	if (ts.isNumericLiteral(unwrapped)) {
		return "number";
	}

	if (
		unwrapped.kind === ts.SyntaxKind.TrueKeyword
		|| unwrapped.kind === ts.SyntaxKind.FalseKeyword
	) {
		return "boolean";
	}

	if (ts.isObjectLiteralExpression(unwrapped)) {
		return objectType(unwrapped, inputTypes);
	}

	if (ts.isConditionalExpression(unwrapped)) {
		return mergeTypes(
			typeForExpression(unwrapped.whenTrue, inputTypes),
			typeForExpression(unwrapped.whenFalse, inputTypes),
		);
	}

	if (
		ts.isBinaryExpression(unwrapped)
		&& unwrapped.operatorToken.kind === ts.SyntaxKind.QuestionQuestionToken
	) {
		return removeUndefined(
			typeForExpression(unwrapped.left, inputTypes),
			typeForExpression(unwrapped.right, inputTypes),
		);
	}

	const inputType = inputAccessType(unwrapped, inputTypes);

	if (inputType) {
		return inputType;
	}

	return "unknown";
}

function objectType(object: ts.ObjectLiteralExpression, inputTypes: Map<string, string>): string {
	const properties = objectProperties(object)
		.map((property) => {
			const name = propertyName(property.name);
			return name
				? `readonly ${JSON.stringify(name)}: ${typeForExpression(property.initializer, inputTypes)};`
				: "";
		})
		.filter(Boolean);

	return properties.length > 0 ? `{\n${properties.map((item) => `\t${item}`).join("\n")}\n}` : "{}";
}

function mergeTypes(left: string, right: string): string {
	const leftObject = parseObjectType(left);
	const rightObject = parseObjectType(right);

	if (!leftObject || !rightObject) {
		return left === right ? left : `${left} | ${right}`;
	}

	const keys = Array.from(
		new Set([...Object.keys(leftObject), ...Object.keys(rightObject)]),
	).sort();
	const lines = keys.map((key) => {
		const leftValue = leftObject[key];
		const rightValue = rightObject[key];
		const optional = leftValue && rightValue ? "" : "?";
		const value =
			leftValue && rightValue ? mergeTypes(leftValue, rightValue) : (leftValue ?? rightValue);
		return `\treadonly ${JSON.stringify(key)}${optional}: ${value};`;
	});

	return `{\n${lines.join("\n")}\n}`;
}

function parseObjectType(type: string): Record<string, string> | undefined {
	const trimmed = type.trim();

	if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) {
		return;
	}

	const result: Record<string, string> = {};
	for (const match of trimmed.matchAll(/readonly "([^"]+)"\??: ([^;]+);/g)) {
		result[match[1]] = match[2];
	}

	return result;
}

function removeUndefined(left: string, fallback: string): string {
	const narrowed = left
		.split("|")
		.map((item) => item.trim())
		.filter((item) => item !== "undefined")
		.join(" | ");

	return narrowed === fallback ? narrowed : mergeTypes(narrowed || "unknown", fallback);
}

function inputAccessType(
	expression: ts.Expression,
	inputTypes: Map<string, string>,
): string | undefined {
	const path = inputAccessPath(expression);
	return path ? inputTypes.get(path) : undefined;
}

function inputAccessPath(expression: ts.Expression): string | undefined {
	const segments: string[] = [];
	let current = unwrapExpression(expression);

	while (ts.isPropertyAccessExpression(current) || ts.isElementAccessExpression(current)) {
		if (ts.isPropertyAccessExpression(current)) {
			segments.unshift(current.name.text);
			current = unwrapExpression(current.expression);
			continue;
		}

		const argument = unwrapExpression(current.argumentExpression);
		if (!ts.isStringLiteralLike(argument)) {
			return;
		}

		segments.unshift(argument.text);
		current = unwrapExpression(current.expression);
	}

	if (!ts.isIdentifier(current) || current.text !== "input" || segments.length !== 2) {
		return;
	}

	return `${segments[0]}.${segments[1]}`;
}

function parseTypeScriptFile(file: string): ts.SourceFile {
	return ts.createSourceFile(
		file,
		readFileSync(file, "utf8"),
		ts.ScriptTarget.Latest,
		true,
		ts.ScriptKind.TS,
	);
}

function routeConfigObject(sourceFile: ts.SourceFile): ts.ObjectLiteralExpression | undefined {
	for (const statement of sourceFile.statements) {
		if (ts.isExportAssignment(statement)) {
			return defineRouteObject(statement.expression) ?? objectLiteral(statement.expression);
		}
	}
}

function defineRouteObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped)) {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

function createRouteObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "createRoute") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

function middlewareDeclarations(
	sourceFile: ts.SourceFile,
	exportedOnly: boolean,
): Array<{ name: string; contract: ts.ObjectLiteralExpression }> {
	const declarations: Array<{ name: string; contract: ts.ObjectLiteralExpression }> = [];

	for (const statement of sourceFile.statements) {
		if (!ts.isVariableStatement(statement)) {
			continue;
		}

		if (exportedOnly && !hasExportModifier(statement)) {
			continue;
		}

		for (const declaration of statement.declarationList.declarations) {
			if (!ts.isIdentifier(declaration.name) || !declaration.initializer) {
				continue;
			}

			const contract = createMiddlewareObject(declaration.initializer);

			if (!contract) {
				continue;
			}

			declarations.push({ name: declaration.name.text, contract });
		}
	}

	return declarations;
}

function hasExportModifier(statement: ts.VariableStatement): boolean {
	return (
		statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
	);
}

function createMiddlewareObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
	const unwrapped = unwrapExpression(expression);

	if (!ts.isCallExpression(unwrapped) || callName(unwrapped) !== "createMiddleware") {
		return;
	}

	return objectLiteral(unwrapped.arguments[0]);
}

function middlewareExpressionMetadata(
	expression: ts.Expression,
	middlewareByName: Map<string, ts.ObjectLiteralExpression>,
): { name: string; contract: ts.ObjectLiteralExpression } | undefined {
	const unwrapped = unwrapExpression(expression);

	if (ts.isIdentifier(unwrapped)) {
		const contract = middlewareByName.get(unwrapped.text);

		if (contract) {
			return { name: unwrapped.text, contract };
		}
	}

	const inline = createMiddlewareObject(unwrapped);

	if (inline) {
		return { name: "createMiddleware", contract: inline };
	}
}

function middlewareExpressions(expression: ts.Expression): ts.Expression[] {
	const unwrapped = unwrapExpression(expression);

	if (ts.isArrayLiteralExpression(unwrapped)) {
		return unwrapped.elements.flatMap((element) =>
			ts.isSpreadElement(element) ? [] : [element as ts.Expression],
		);
	}

	return [unwrapped];
}

function routeInputs(routeContract: ts.ObjectLiteralExpression): RouteMethodInputMetadata {
	const input = objectProperty(routeContract, "input");
	const inputObject = input ? objectLiteral(input.initializer) : undefined;

	return {
		params: Boolean(inputObject && objectProperty(inputObject, "params")),
		query: Boolean(inputObject && objectProperty(inputObject, "query")),
		body: Boolean(inputObject && objectProperty(inputObject, "body")),
	};
}

function responseStatuses(routeContract: ts.ObjectLiteralExpression): number[] {
	const responses = objectProperty(routeContract, "responses");

	if (!responses) {
		return [];
	}

	const statuses: number[] = [];
	const visit = (node: ts.Node) => {
		if (ts.isPropertyAssignment(node) && propertyName(node.name) === "status") {
			const status = numericValue(node.initializer);

			if (status !== undefined) {
				statuses.push(status);
			}
		}

		ts.forEachChild(node, visit);
	};
	visit(responses.initializer);

	return statuses;
}

function numericValue(expression: ts.Expression): number | undefined {
	const unwrapped = unwrapExpression(expression);

	if (ts.isNumericLiteral(unwrapped)) {
		return Number(unwrapped.text);
	}
}

function objectProperty(
	object: ts.ObjectLiteralExpression,
	name: string,
): ts.PropertyAssignment | undefined {
	return objectProperties(object).find((property) => propertyName(property.name) === name);
}

function objectProperties(object: ts.ObjectLiteralExpression): ts.PropertyAssignment[] {
	return object.properties.filter(ts.isPropertyAssignment);
}

function objectLiteral(node: ts.Node | undefined): ts.ObjectLiteralExpression | undefined {
	if (!node || !ts.isExpression(node)) {
		return;
	}

	const unwrapped = unwrapExpression(node);
	return ts.isObjectLiteralExpression(unwrapped) ? unwrapped : undefined;
}

function callName(expression: ts.Expression): string | undefined {
	const callee = ts.isCallExpression(expression)
		? unwrapExpression(expression.expression)
		: unwrapExpression(expression);

	if (ts.isIdentifier(callee)) {
		return callee.text;
	}

	if (ts.isPropertyAccessExpression(callee)) {
		return callee.name.text;
	}
}

function propertyName(name: ts.PropertyName): string | undefined {
	if (ts.isIdentifier(name) || ts.isStringLiteralLike(name) || ts.isNumericLiteral(name)) {
		return name.text;
	}
}

function unwrapExpression(expression: ts.Expression): ts.Expression {
	let current = expression;

	while (
		ts.isParenthesizedExpression(current)
		|| ts.isAsExpression(current)
		|| ts.isSatisfiesExpression(current)
		|| ts.isTypeAssertionExpression(current)
		|| ts.isNonNullExpression(current)
	) {
		current = current.expression;
	}

	return current;
}

function middlewareOrderDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const chains =
			route.methods.length > 0
				? route.methods.map(
						(item) => route.methodMiddleware[item.toLowerCase()] ?? route.middleware,
					)
				: [route.middleware];

		for (const chain of chains) {
			const provided = new Set<string>();

			for (const middleware of chain) {
				for (const required of middleware.requires) {
					if (!provided.has(required)) {
						diagnostics.push({
							code: "ROUTA_MIDDLEWARE_ORDER",
							severity: "error",
							message: `${middleware.name} requires ctx.${required} before it is provided.`,
							file: middleware.file,
							routePath: route.path,
							suggestion: `Move middleware that provides ${required} before ${middleware.name}.`,
						});
					}
				}

				for (const providedField of middleware.provides) {
					provided.add(providedField);
				}
			}
		}
	}

	return diagnostics;
}

function duplicateRouteDiagnostics(routes: RouteMetadata[]): Diagnostic[] {
	const seen = new Map<string, RouteMetadata>();
	const diagnostics: Diagnostic[] = [];

	for (const route of routes) {
		const previous = seen.get(route.path);

		if (previous) {
			diagnostics.push({
				code: "ROUTA_DUPLICATE_ROUTE",
				severity: "error",
				message: `Duplicate route path ${route.path}.`,
				file: route.file,
				routePath: route.path,
				suggestion: `Rename or move ${route.file}; it conflicts with ${previous.file}.`,
			});
			continue;
		}

		seen.set(route.path, route);
	}

	return diagnostics;
}

function writeRoutesMetadata(cwd: string, routes: RouteMetadata[]): void {
	const file = join(cwd, ".routa/routes.gen.ts");
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(
		file,
		`${generatedHeader}export const routaRoutes = ${JSON.stringify(routes, null, "\t")} as const;

${routeContextTypes(routes)}
`,
	);
}

function routeContextTypes(routes: RouteMetadata[]): string {
	const ctxTypes = routes
		.map((route) => {
			const typeName = routeCtxTypeName(route);
			const ctx =
				route.ctx.length > 0
					? route.ctx.map((key) => `\t${JSON.stringify(key)}: unknown;`).join("\n")
					: "\treadonly __empty?: never;";

			return `export type ${typeName} = {\n${ctx}\n};`;
		})
		.join("\n\n");

	const ctxMap = `export type RoutaRouteCtxByPath = {\n${routes
		.map((route) => `\t${JSON.stringify(route.path)}: ${routeMethodCtxMap(route)};`)
		.join("\n")}\n};`;
	const ctxByKey = `export type RoutaCtxByKey = ${ctxByKeyType(routes)};`;

	return `${ctxTypes}\n\n${ctxMap}\n\n${ctxByKey}\n\ndeclare module "@routa/core" {\n\texport interface Register {\n\t\trouteCtxByPath: RoutaRouteCtxByPath;\n\t\tctxByKey: RoutaCtxByKey;\n\t}\n}`;
}

function ctxByKeyType(routes: RouteMetadata[]): string {
	const ctx = new Map<string, string>();

	for (const route of routes) {
		const chains = [route.middleware, ...Object.values(route.methodMiddleware)];

		for (const chain of chains) {
			for (const middleware of chain) {
				for (const key of middleware.provides) {
					ctx.set(key, middleware.providesTypes[key] ?? "unknown");
				}
			}
		}
	}

	if (ctx.size === 0) {
		return "{ readonly __empty?: never }";
	}

	return `{\n${Array.from(ctx.entries())
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([key, type]) => `\t${JSON.stringify(key)}: ${indentType(type, 1)};`)
		.join("\n")}\n}`;
}

function routeMethodCtxMap(route: RouteMetadata): string {
	const methods: string[] = [];

	for (const method of ["get", "post", "put", "patch", "delete", "head", "options"]) {
		methods.push(`\t\t${method}: ${routeCtxTypeNameForMiddleware(route, method)};`);
	}

	return `{\n${methods.join("\n")}\n\t}`;
}

function routeCtxTypeNameForMiddleware(route: RouteMetadata, method: string): string {
	const chain = route.methodMiddleware[method] ?? route.middleware;
	const ctx = new Map<string, string>();

	for (const middleware of chain) {
		for (const key of middleware.provides) {
			ctx.set(key, middleware.providesTypes[key] ?? "unknown");
		}
	}

	if (ctx.size === 0) {
		return "{ readonly __empty?: never }";
	}

	return `{\n${Array.from(ctx.entries())
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([key, type]) => `\t\t\t${JSON.stringify(key)}: ${indentType(type, 3)};`)
		.join("\n")}\n\t\t}`;
}

function indentType(type: string, tabs: number): string {
	const indentation = "\t".repeat(tabs);
	return type.replaceAll("\n", `\n${indentation}`);
}

function routeCtxTypeName(route: RouteMetadata): string {
	const suffix = route.path === "/" ? "Root" : pascalCase(route.path);
	return `${suffix}Ctx`;
}

function pascalCase(value: string): string {
	const text = value.replaceAll(/[^a-zA-Z0-9]+/g, " ").trim();

	if (!text) {
		return "Route";
	}

	return text
		.split(/\s+/)
		.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
		.join("");
}

function runTypeScript(
	cwd: string,
	args: string[],
): { code: number; stdout?: string; stderr?: string } {
	if (!existsSync(join(cwd, "tsconfig.json"))) {
		return { code: 0 };
	}

	const result = spawnSync("pnpm", ["exec", "tsc", ...args], {
		cwd,
		encoding: "utf8",
	});

	return {
		code: result.status ?? 1,
		stdout: result.stdout,
		stderr: result.stderr || result.error?.message,
	};
}

function appendOutput(lines: string[], output?: string): string {
	const base = `${lines.join("\n")}\n`;

	if (!output) {
		return base;
	}

	return `${base}${output.endsWith("\n") ? output : `${output}\n`}`;
}

function formatDiagnostics(diagnostics: Diagnostic[]): string {
	return diagnostics
		.map((diagnostic) => {
			const location = diagnostic.file ? `${diagnostic.file}: ` : "";
			const suggestion = diagnostic.suggestion ? `\nSuggestion: ${diagnostic.suggestion}` : "";
			return `${diagnostic.code}: ${location}${diagnostic.message}${suggestion}`;
		})
		.join("\n");
}

function walk(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
		const file = join(dir, entry.name);
		return entry.isDirectory() ? walk(file) : [file];
	});
}
