import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
import { parse as parseYaml } from "yaml";

const httpMethods = ["get", "post", "put", "patch", "delete", "head", "options"] as const;

type HttpMethod = (typeof httpMethods)[number];

type OpenApiDocument = {
	openapi?: string;
	info?: unknown;
	paths?: Record<string, Record<string, OpenApiOperation>>;
	components?: {
		schemas?: Record<string, OpenApiSchema>;
	};
};

type OpenApiOperation = {
	operationId?: string;
	parameters?: Array<{
		name?: string;
		in?: string;
		required?: boolean;
		schema?: OpenApiSchema;
	}>;
	requestBody?: {
		content?: Record<string, { schema?: OpenApiSchema }>;
	};
	responses?: Record<
		string,
		{
			description?: string;
			content?: Record<string, { schema?: OpenApiSchema }>;
		}
	>;
};

type OpenApiContent = Record<string, { schema?: OpenApiSchema }>;

type OpenApiSchema = {
	type?: string;
	format?: string;
	items?: OpenApiSchema;
	properties?: Record<string, OpenApiSchema>;
	required?: string[];
	$ref?: string;
};

type Manifest = {
	version: 1;
	openapi: { baseline: string };
	generated: ManifestGeneratedFile[];
};

type ManifestGeneratedFile = {
	path: string;
	source?: string;
	operationIds?: string[];
	kind: string;
	sha256?: string;
};

export type ScaffoldResult = {
	files: string[];
	routes: Array<{
		file: string;
		path: string;
		methods: string[];
		operationIds: string[];
		middleware: string[];
		groups: string[];
		segments: string[];
	}>;
	preview: boolean;
};

export type ScaffoldOptions = {
	preview?: boolean;
	yes?: boolean;
};

const generatedHeader = (source: string) =>
	`// Generated by Routa.\n// Safe to edit, but regeneration may update this file after preview.\n// Source: ${source}\n\n`;

export function scaffoldOpenApi(
	inputFile: string,
	cwd = process.cwd(),
	options: ScaffoldOptions = {},
): ScaffoldResult {
	const extension = extname(inputFile).toLowerCase();

	if (![".yaml", ".json"].includes(extension)) {
		throw new Error("Unsupported OpenAPI input. Use .yaml or .json.");
	}

	const absoluteInput = join(cwd, inputFile);
	const source = relative(cwd, absoluteInput);
	const raw = readFileSync(absoluteInput, "utf8");
	const document = parseOpenApi(raw, extension);
	validateOpenApiDocument(document);
	const paths = document.paths ?? {};
	const generated = new Set<string>();
	const routes: ScaffoldResult["routes"] = [];
	const previousManifest = readManifest(cwd);
	const generatedContent = new Map<string, string>();

	for (const [openApiPath, pathItem] of Object.entries(paths)) {
		const operations = Object.entries(pathItem).filter(([method]) =>
			httpMethods.includes(method as HttpMethod),
		) as Array<[HttpMethod, OpenApiOperation]>;

		if (operations.length === 0) {
			continue;
		}

		const routeDir = join(cwd, pathToRouteDir(openApiPath));
		const routeFile = join(routeDir, "route.ts");
		const schemaFile = join(routeDir, "schemas.ts");
		mkdirSync(routeDir, { recursive: true });

		const schemaExports = new Map<string, string>();
		const methodBlocks: string[] = [];
		const operationIds: string[] = [];

		for (const [method, operation] of operations) {
			const names = operationNames(method, openApiPath, operation);
			operationIds.push(operation.operationId ?? `${method}${pascalCase(openApiPath)}`);
			const inputParts: string[] = [];
			const paramsSchema = schemaForPathParams(openApiPath, operation);
			const querySchema = schemaForParameters(operation, "query");
			const bodySchema = schemaForRequestBody(operation);
			const response = schemaForResponse(operation);

			if (paramsSchema) {
				schemaExports.set(names.params, paramsSchema);
				inputParts.push(`params: ${names.params}`);
			}

			if (querySchema) {
				schemaExports.set(names.query, querySchema);
				inputParts.push(`query: ${names.query}`);
			}

			if (bodySchema) {
				addReferencedComponents(schemaExports, requestBodySchema(operation), document);
				schemaExports.set(names.body, bodySchema);
				inputParts.push(`body: ${names.body}`);
			}

			addReferencedComponents(schemaExports, response.schemaSource, document);
			schemaExports.set(names.response, response.schema);

			const inputBlock =
				inputParts.length > 0
					? `\n\t\t\tinput: {\n\t\t\t\t${inputParts.join(",\n\t\t\t\t")},\n\t\t\t},`
					: "";

			methodBlocks.push(`\t${method}: createRoute({${inputBlock}
\t\tresponses: {
\t\t\tsuccess: {
\t\t\t\tstatus: ${response.status},
\t\t\t\tschema: ${names.response},
\t\t\t},
\t\t},
\t\trun: async () => {
\t\t\t// TODO: call application-owned business logic.
\t\t\treturn { type: "success", data: ${response.placeholder} as z.output<typeof ${names.response}> };
\t\t},
\t})`);
		}

		const imports = Array.from(schemaExports.keys()).sort().join(", ");
		const routeSource = `${generatedHeader(source)}import { createRoute, defineRoute } from "@routa/core";
import type { z } from "zod";
import { ${imports} } from "./schemas.js";

export default defineRoute({
${methodBlocks.join(",\n")}
});
`;
		const schemaSource = `${generatedHeader(source)}import { z } from "zod";

${Array.from(schemaExports.entries())
	.map(([name, schema]) => `export const ${name} = ${schema};`)
	.join("\n\n")}
`;

		generated.add(relative(cwd, routeFile));
		generated.add(relative(cwd, schemaFile));
		generatedContent.set(relative(cwd, routeFile), routeSource);
		generatedContent.set(relative(cwd, schemaFile), schemaSource);
		routes.push({
			file: relative(cwd, routeFile),
			path: openApiPath.replaceAll(/\{([^}]+)\}/g, ":$1"),
			methods: operations.map(([method]) => method.toUpperCase()),
			operationIds,
			middleware: [],
			groups: [],
			segments: pathSegments(openApiPath),
		});
	}

	mkdirSync(join(cwd, ".routa"), { recursive: true });

	generatedContent.set(
		".routa/routes.gen.ts",
		`${generatedHeader(source)}export const routaRoutes = ${JSON.stringify(routes, null, "\t")} as const;
`,
	);
	generatedContent.set(".routa/openapi-baseline.json", `${JSON.stringify(document, null, "\t")}\n`);

	const manifestGenerated = Array.from(generated)
		.sort()
		.map((path) => {
			const route = routes.find((item) => path.startsWith(dirname(item.file)));

			return {
				path,
				source,
				operationIds: route?.operationIds ?? [],
				kind: path.endsWith("schemas.ts") ? "schema" : "route",
				sha256: sha256(generatedContent.get(path) ?? ""),
			};
		});

	const routeMetadataContent = generatedContent.get(".routa/routes.gen.ts") ?? "";
	const manifest: Manifest = {
		version: 1,
		openapi: { baseline: ".routa/openapi-baseline.json" },
		generated: [
			...manifestGenerated,
			{
				path: ".routa/routes.gen.ts",
				source,
				kind: "route-metadata",
				sha256: sha256(routeMetadataContent),
			},
			{
				path: ".routa/openapi-baseline.json",
				source,
				kind: "openapi-baseline",
				sha256: sha256(generatedContent.get(".routa/openapi-baseline.json") ?? ""),
			},
		],
	};
	const manifestContent = `${JSON.stringify(manifest, null, "\t")}\n`;
	const files = [
		...Array.from(generated).sort(),
		".routa/openapi-baseline.json",
		".routa/manifest.json",
		".routa/routes.gen.ts",
	];

	if (previousManifest && options.preview) {
		return {
			files,
			routes,
			preview: true,
		};
	}

	if (previousManifest && !options.yes) {
		throw new Error(
			"Regeneration requires preview or confirmation. Re-run with --preview or --yes.",
		);
	}

	for (const [path, content] of generatedContent) {
		writeManagedFile(cwd, path, content, previousManifest);
	}

	writeFile(join(cwd, ".routa/manifest.json"), manifestContent);

	return {
		files,
		routes,
		preview: false,
	};
}

function parseOpenApi(raw: string, extension: string): OpenApiDocument {
	const document = extension === ".json" ? JSON.parse(raw) : parseYaml(raw);

	if (!document || typeof document !== "object" || !("paths" in document)) {
		throw new Error("Invalid OpenAPI document: missing paths.");
	}

	return document as OpenApiDocument;
}

function validateOpenApiDocument(document: OpenApiDocument): void {
	const operationIds = new Set<string>();

	for (const name of Object.keys(document.components?.schemas ?? {})) {
		validateGeneratedIdentifier(
			refName(`#/components/schemas/${name}`),
			`component schema ${name}`,
		);
	}

	for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
		for (const [method, operation] of Object.entries(pathItem)) {
			if (!httpMethods.includes(method as HttpMethod)) {
				continue;
			}

			if (!operation.operationId) {
				throw new Error(`Missing operationId for ${method.toUpperCase()} ${path}.`);
			}

			if (operationIds.has(operation.operationId)) {
				throw new Error(`Duplicate operationId: ${operation.operationId}.`);
			}

			operationIds.add(operation.operationId);

			const names = operationNames(method as HttpMethod, path, operation);
			for (const [kind, name] of Object.entries(names)) {
				validateGeneratedIdentifier(name, `${kind} name for ${method.toUpperCase()} ${path}`);
			}

			if (operation.requestBody?.content && !operation.requestBody.content["application/json"]) {
				throw new Error(
					`Unsupported request media type for ${method.toUpperCase()} ${path}. Use application/json.`,
				);
			}

			for (const [status, response] of Object.entries(operation.responses ?? {})) {
				if (response.content && !response.content["application/json"]) {
					throw new Error(
						`Unsupported response media type for ${method.toUpperCase()} ${path} ${status}. Use application/json.`,
					);
				}
			}
		}
	}
}

function pathToRouteDir(openApiPath: string): string {
	const segments = pathSegments(openApiPath).map((segment) =>
		segment.startsWith("{") && segment.endsWith("}") ? `$${segment.slice(1, -1)}` : segment,
	);

	return join("routes", ...segments);
}

function pathSegments(openApiPath: string): string[] {
	return openApiPath.split("/").filter(Boolean);
}

function operationNames(method: HttpMethod, path: string, operation: OpenApiOperation) {
	const base = pascalCase(operation.operationId ?? `${method} ${path}`);

	return {
		params: `${base}Params`,
		query: `${base}Query`,
		body: `${base}Body`,
		response: `${base}Response`,
	};
}

function schemaForPathParams(path: string, operation: OpenApiOperation): string | undefined {
	const names = new Set(
		path
			.split("/")
			.filter((segment) => segment.startsWith("{") && segment.endsWith("}"))
			.map((segment) => segment.slice(1, -1)),
	);

	if (names.size === 0) {
		return undefined;
	}

	const parameterSchemas = new Map(
		(operation.parameters ?? [])
			.filter((parameter) => parameter.in === "path" && parameter.name)
			.map((parameter) => [parameter.name as string, parameter.schema]),
	);

	const props = Array.from(names)
		.sort()
		.map((name) => `${JSON.stringify(name)}: ${zodForSchema(parameterSchemas.get(name))}`)
		.join(", ");

	return `z.object({ ${props} })`;
}

function schemaForParameters(operation: OpenApiOperation, location: string): string | undefined {
	const parameters = (operation.parameters ?? []).filter(
		(parameter) => parameter.in === location && parameter.name,
	);

	if (parameters.length === 0) {
		return undefined;
	}

	const props = parameters
		.map((parameter) => {
			const schema = zodForSchema(parameter.schema);
			const optional = parameter.required ? "" : ".optional()";
			return `${JSON.stringify(parameter.name)}: ${schema}${optional}`;
		})
		.join(", ");

	return `z.object({ ${props} })`;
}

function schemaForRequestBody(operation: OpenApiOperation): string | undefined {
	const schema = requestBodySchema(operation);
	return schema ? zodForSchema(schema) : undefined;
}

function schemaForResponse(operation: OpenApiOperation) {
	const entry =
		Object.entries(operation.responses ?? {}).find(([status]) => status.startsWith("2"))
		?? Object.entries(operation.responses ?? {})[0];
	const status = entry ? Number(entry[0]) : 200;
	const schema = firstJsonContent(entry?.[1].content)?.schema;
	const zodSchema = schema ? zodForSchema(schema) : "z.unknown()";

	return {
		status: Number.isFinite(status) ? status : 200,
		schema: zodSchema,
		schemaSource: schema,
		placeholder: placeholderForSchema(schema),
	};
}

function requestBodySchema(operation: OpenApiOperation): OpenApiSchema | undefined {
	return firstJsonContent(operation.requestBody?.content)?.schema;
}

function firstJsonContent(content: OpenApiContent | undefined) {
	return content?.["application/json"] ?? Object.values(content ?? {})[0];
}

function zodForSchema(schema: OpenApiSchema | undefined): string {
	if (!schema) {
		return "z.unknown()";
	}

	if (schema.$ref) {
		return refName(schema.$ref);
	}

	if (schema.type === "array") {
		return `z.array(${zodForSchema(schema.items)})`;
	}

	if (schema.type === "object" || schema.properties) {
		const required = new Set(schema.required ?? []);
		const props = Object.entries(schema.properties ?? {})
			.map(([name, value]) => {
				const optional = required.has(name) ? "" : ".optional()";
				return `${JSON.stringify(name)}: ${zodForSchema(value)}${optional}`;
			})
			.join(", ");

		return `z.object({ ${props} })`;
	}

	if (schema.type === "integer" || schema.type === "number") {
		return "z.number()";
	}

	if (schema.type === "boolean") {
		return "z.boolean()";
	}

	return "z.string()";
}

function placeholderForSchema(schema: OpenApiSchema | undefined): string {
	if (schema?.type === "array") {
		return "[]";
	}

	if (schema?.type === "object" || schema?.properties) {
		const entries = Object.entries(schema.properties ?? {}).map(
			([name, value]) => `${JSON.stringify(name)}: ${placeholderForSchema(value)}`,
		);

		return `{ ${entries.join(", ")} }`;
	}

	if (schema?.type === "integer" || schema?.type === "number") {
		return "0";
	}

	if (schema?.type === "boolean") {
		return "false";
	}

	if (schema?.type === "string") {
		return '""';
	}

	return "null";
}

function addReferencedComponents(
	schemaExports: Map<string, string>,
	schema: OpenApiSchema | undefined,
	document: OpenApiDocument,
): void {
	for (const ref of refsInSchema(schema)) {
		const name = refName(ref);
		const component = document.components?.schemas?.[name];

		if (!component || schemaExports.has(name)) {
			continue;
		}

		addReferencedComponents(schemaExports, component, document);
		schemaExports.set(name, zodForSchema(component));
	}
}

function refsInSchema(schema: OpenApiSchema | undefined): string[] {
	if (!schema) {
		return [];
	}

	return [
		...(schema.$ref ? [schema.$ref] : []),
		...refsInSchema(schema.items),
		...Object.values(schema.properties ?? {}).flatMap((property) => refsInSchema(property)),
	];
}

function refName(ref: string): string {
	const name = ref.split("/").at(-1);

	if (!name) {
		throw new Error(`Unsupported OpenAPI $ref: ${ref}`);
	}

	return pascalCase(name);
}

function validateGeneratedIdentifier(name: string, context: string): void {
	if (!/^[$A-Z_a-z][$\w]*$/.test(name)) {
		throw new Error(
			`Invalid generated TypeScript identifier ${name} from ${context}. Rename it before scaffolding.`,
		);
	}
}

function pascalCase(value: string): string {
	const text = value.replaceAll(/[^a-zA-Z0-9]+/g, " ").trim();

	if (!text) {
		return "Operation";
	}

	return text
		.split(/\s+/)
		.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
		.join("");
}

function writeFile(filePath: string, content: string): void {
	mkdirSync(dirname(filePath), { recursive: true });
	writeFileSync(filePath, content);
}

function readManifest(cwd: string): Manifest | undefined {
	const file = join(cwd, ".routa/manifest.json");

	if (!existsSync(file)) {
		return undefined;
	}

	return JSON.parse(readFileSync(file, "utf8")) as Manifest;
}

function writeManagedFile(
	cwd: string,
	path: string,
	content: string,
	previousManifest: Manifest | undefined,
): void {
	const absolutePath = join(cwd, path);

	if (existsSync(absolutePath)) {
		const previous = previousManifest?.generated.find((file) => file.path === path);

		if (!previous) {
			throw new Error(`Refusing to overwrite unmanaged file: ${path}`);
		}

		if (previous.sha256 && sha256(readFileSync(absolutePath, "utf8")) !== previous.sha256) {
			throw new Error(`Refusing to overwrite modified generated file: ${path}`);
		}
	}

	writeFile(absolutePath, content);
}

function sha256(content: string): string {
	return createHash("sha256").update(content).digest("hex");
}
