// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, createRouteRoot } from "@routa-ts/core";
import { ListAuditEventsQuery, ListAuditEventsResponse } from "./schemas.js";

const route = createRouteRoot("/admin/audit-events");

export default route({
	get: createRoute({
		input: {
			query: ListAuditEventsQuery,
		},
		responses: {
			success: {
				status: 200,
				schema: ListAuditEventsResponse,
			},
		},
		run: ({ ctx, input }) => {
			const limit = input.query.limit ?? 1;

			return {
				type: "success",
				data: {
					events: Array.from({ length: limit }, (_, index) => ({
						id: `audit_${index + 1}`,
						actorId: ctx.admin.role,
						action: "project.read",
					})),
				},
			};
		},
	}),
});
