// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const ListAuditEventsQuery = z.object({ limit: z.int().optional() });

export const AuditEvent = z.object({
	id: z.string(),
	actorId: z.string(),
	action: z.string(),
});

export const ListAuditEventsResponse = z.object({ events: z.array(AuditEvent) });
