// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, defineRoute } from "@routa/core";
import type { z } from "zod";
import {
	CreateUserBody,
	CreateUserResponse,
	ListUsersQuery,
	ListUsersResponse,
} from "./schemas.js";

export default defineRoute({
	get: createRoute({
		input: {
			query: ListUsersQuery,
		},
		responses: {
			success: {
				status: 200,
				schema: ListUsersResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: { users: [] } as unknown as z.output<typeof ListUsersResponse>,
			};
		},
	}),
	post: createRoute({
		input: {
			body: CreateUserBody,
		},
		responses: {
			success: {
				status: 201,
				schema: CreateUserResponse,
			},
		},
		run: ({ input }) => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: {
					id: "user_new",
					email: input.body.email,
					name: input.body.name,
					active: true,
				} as unknown as z.output<typeof CreateUserResponse>,
			};
		},
	}),
});
