// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const ListUsersQuery = z.object({
	limit: z.coerce.number().int().optional(),
	search: z.string().optional(),
});

export const User = z.object({
	id: z.string(),
	email: z.string(),
	name: z.string(),
	active: z.boolean(),
});

export const ListUsersResponse = z.object({ users: z.array(User) });

export const CreateUserInput = z.object({
	email: z.string(),
	name: z.string(),
});

export const CreateUserBody = CreateUserInput;

export const CreateUserResponse = User;
