// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { createRoute, defineRoute } from "@routa/core";
import type { z } from "zod";
import {
	DeleteUserParams,
	DeleteUserResponse,
	GetUserParams,
	GetUserResponse,
	UpdateUserBody,
	UpdateUserParams,
	UpdateUserResponse,
} from "./schemas.js";

export default defineRoute({
	get: createRoute({
		input: {
			params: GetUserParams,
		},
		responses: {
			success: {
				status: 200,
				schema: GetUserResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: null as unknown as z.output<typeof GetUserResponse>,
			};
		},
	}),
	patch: createRoute({
		input: {
			params: UpdateUserParams,
			body: UpdateUserBody,
		},
		responses: {
			success: {
				status: 200,
				schema: UpdateUserResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: null as unknown as z.output<typeof UpdateUserResponse>,
			};
		},
	}),
	delete: createRoute({
		input: {
			params: DeleteUserParams,
		},
		responses: {
			success: {
				status: 204,
				schema: DeleteUserResponse,
			},
		},
		run: () => {
			// TODO: call application-owned business logic.
			return {
				type: "success",
				data: null as unknown as z.output<typeof DeleteUserResponse>,
			};
		},
	}),
});
