// Generated by Routa.
// Safe to edit, but regeneration may update this file after preview.
// Source: openapi.yaml

import { z } from "zod";

export const GetUserParams = z.object({ userId: z.string() });

export const User = z.object({
	id: z.string(),
	email: z.string(),
	name: z.string(),
	active: z.boolean(),
});

export const GetUserResponse = User;

export const UpdateUserParams = z.object({ userId: z.string() });

export const UpdateUserInput = z.object({
	email: z.string().optional(),
	name: z.string().optional(),
	active: z.boolean().optional(),
});

export const UpdateUserBody = UpdateUserInput;

export const UpdateUserResponse = User;

export const DeleteUserParams = z.object({ userId: z.string() });

export const DeleteUserResponse = z.unknown();
